### ISSUE TITLE
BitmapFont#type incorrect

### ISSUE THREAD

**Issue by Maligan** [Gamua/Starling-Framework#1001]
Hi, Daniel!

I write about new feature BitmapFont type - now it is defined incorect because BitmapFont#parseFontXml 
 check
`if (fontXml.distanceFiled)`
Constantly return true, because `distanceFiled = {XMLList}` is empty XML list

**Comment by PrimaryFeather** [comment]
Oh wow, I obviously only used distance field fonts since I implemented that feature. :wink:
Thanks a lot for the heads-up! I just fixed this.
