### ISSUE TITLE
Doc: Does RenderTexture.draw() still ignore filters on the object?

### ISSUE THREAD

**Issue by Adolio** [Gamua/Starling-Framework#1005]
In RenderTexture.draw() method headers:

Is `"Note that any filters on the object will currently be ignored."` still the case in Starling 2.x?

https://github.com/Gamua/Starling-Framework/blob/9554497f9be8574a4159406503365366155cd399/starling/src/starling/textures/RenderTexture.as#L156

**Comment by PrimaryFeather** [comment]
Actually, that's no longer true, you're right! Thanks once more! :smile:

**Comment by Adolio** [comment]
You're welcome! Happy to help on this since I'm currently digging into it. 😊
Once more your API is always real pleasure to play with!

**Comment by PrimaryFeather** [comment]
Thanks, Aurélien! ☺️
