### ISSUE TITLE
Texture.fromEmbeddedAsset() should allow the Class to instantiate BitmapData too

### ISSUE THREAD

**Issue by joshtynjala** [Gamua/Starling-Framework#1011]
An image file embedded with [Embed] metadata instantiates a flash.display.Bitmap. In Animate CC, if you add an image file to the library and set "Export for ActionScript", the symbol will be exported as a class that extends flash.display.BitmapData instead.

I recommended someone use Texture.fromEmbeddedAsset() in [this thread](https://forum.starling-framework.org/topic/use-graphics-from-adobe-animate-library-instead-of-embedding), but it turned out that they couldn't do that because a symbol from Animate's library extended BitmapData instead of Bitmap.

**Comment by PrimaryFeather** [comment]
Thanks a lot for making me aware of this, Josh! Indeed, the method has to support this.
It should now work as expected.
