### ISSUE TITLE
Optimize display object ENTER_FRAME event

### ISSUE THREAD

**Issue by hardcoremore** [Gamua/Starling-Framework#1016]
https://github.com/Gamua/Starling-Framework/blob/7918257f0051d8e2f51d6cb0cf418aa7cba671a8/starling/src/starling/display/DisplayObjectContainer.as#L511

It seams like it is a good idea to check here if object is visible and eventType is ENTER_FRAME and if both are true skip dispatching ENTER_FRAME event for this object. Why would invisible objects need ENTER_FRAME event.

This is killing performance as currently in my game I have around 1000 objects and I am making them invisible as they are not in the viewport and that seams to not matter because starling is allocating around 50-60MB of memory for about 2 minutes of play and then my frame rate drops heavily while GC cleans it.

It all happens because every display object is dispatching ENTER_FRAME event on every frame even though they are invisible and memory keeps growing like crazy.

I guess only solution is that I remove object from stage if is not visible and add it again when it becomes visible. It looks like setting visible to false alone is not enough.

What do you think Daniel?

**Comment by PrimaryFeather** [comment]
This method is [overridden](https://github.com/Gamua/Starling-Framework/blob/7918257f0051d8e2f51d6cb0cf418aa7cba671a8/starling/src/starling/display/Stage.as#L159) inside `Stage.as`. It manages a special list for all objects that are listening to `ENTER_FRAME` events.

So if you've got many objects that are invisible and listen to `ENTER_FRAME` events, I recommend you remove that listener while they are invisible or you remove them from the display list altogether during that time. That would have some other advantages, too; e.g. Starling wouldn't need to iterate over them in each frame to check for their visibility.

**Comment by hardcoremore** [comment]
I have already done that but Starling keeps allocating massive amounts of memory.

Take a look at this. I have modified Starling DisplayObject class dispatchEvent method to this:

public override function dispatchEvent(event:Event):void
{
    if (event.type == Event.REMOVED_FROM_STAGE && stage == null)
    {
        return; // special check to avoid double-dispatch of RfS-event.
    }
    else
    {
        if(c < 20000)
        {
            super.dispatchEvent(event);
            c++;
        }
        else if(this is Stage)
        {
            super.dispatchEvent(event);
        }
    }
}

This 20000 gives me enough time to load the level and play it.

So ENTER_FRAME is being dispatched only for Stage object. I have removed all feathers components from stage as well. Game logic is not run as well, Box2D is not run also. This is just Starling running and is limited to run ENTER_FRAME only for Stage object nothing more. No other code is run.

For about 2 minutes of playing 30MB is generated and when GC collects it it drops my frame rate.

Take a look at this Scout profile:
https://goo.gl/Xgaqdj

Select more than 1 second on the timeline and look at Trace Log tab on the right there will be printed standard memory usage (NOT GPU memory). I trace memory usage on every second.

If you look at around 30 second of play memory is 144MB and if you look at the end memory is 174, Why is so much memory being generated.


This is my game looks during this test. You can see no ui is being present. I am not controlling anything I have just played level. When level is played display and physics objects are created. However Box2D is not running only starling is running.

![image](https://user-images.githubusercontent.com/1597791/35112981-2f4365b2-fc80-11e7-9709-6c30d8e4ac04.png)

**Comment by PrimaryFeather** [comment]
I still don't understand what's happening here, and why you think that the EnterFrameEvent has something to do with it.

* There is only ONE _EnterFrameEvent_ instance that's reused for all display objects, for all frames.
* Dispatching an event does not allocate any memory.

In your Scout file, I selected 300 frames and had a look at the "Memory Allocations" tab:

<img width="674" alt="screen shot 2018-01-19 at 09 51 05" src="https://user-images.githubusercontent.com/547347/35142419-833f9acc-fcfe-11e7-9600-ce080f5437fc.png">

As you can see, the majority of memory is allocated by `StardustStarlingRenderer`. The 600 events you're seeing are actually those of the classic display list. 

I also can't see any garbage collection spikes in your Scout file.

I don't know why `System.totalMemory` is rising like this, but it doesn't seem to be ActionScript allocations — Scout says that between frame 300 and 6000, only < 800 kB of memory are allocated, (most of which are _native_ EnterFrameEvents_).

<img width="678" alt="screen shot 2018-01-19 at 10 01 39" src="https://user-images.githubusercontent.com/547347/35142820-d2907ae6-fcff-11e7-9677-0161daa8a722.png">

In general, I wouldn't put too much trust into `System.totalMemory`. I remember several cases in the past where it simply reported misleading values.

**Comment by hardcoremore** [comment]
Hi Daniel,

Sorry this is not because of ENTER_FRAME event. The thing is that I do not know what to fix since Adobe Scout is not giving me any useful info.

I have open a new thread on the forum with detailed info here:

https://forum.starling-framework.org/topic/help-unable-to-reduce-memory-allocation#post-110570

I would like to hear your opinion on the Scout profile I have posted there.

You can close this issue.


Thanks,

Caslav

**Comment by PrimaryFeather** [comment]
Okay, thanks for the clarification! I added some comments in the forum thread.
