### ISSUE TITLE
AssetManager.loadQueue never completes

### ISSUE THREAD

**Issue by Constans** [Gamua/Starling-Framework#1017]
I'm having an issue with AssetManager.loadQueue ratio never reaching to 1.0.

This happens on AIR 28 with the latest Starling release and Android 7.0 or 8.0. The device I use is HTC 10.

In order to reproduce it, I start  the app with the SoftKeyboard on screen (searching the app on my phone).

If I start the app from the shortcut (without the SoftKeyboard on), the ratio reaches 1, so the app moves on from the preloading screen.

The difference between the 2 is that there is a **[Starling] Context restored.** triggered in the loading queue process.

Any directions on how to resolve this would be appreciated. 
Thank you!

**Comment by PrimaryFeather** [comment]
Thanks for the report!

Quick question: are you very close to the release, or is there still some time? I'm currently rewriting the AssetManager from scratch, so there's a chance this will be fixed with the new version. It should be out in a few weeks max.

**Comment by Constans** [comment]
Already released, though the "official" launch will be somewhere in the next month.

I've discovered the issue while testing/solving other issues.
I'll apply workaround fix until then if there is no other solution. 

That's great news regarding the rewrite and I'm looking forward for the update!

**Comment by Constans** [comment]
As a quick solution, for now I'll purge the AssetsManager queue every time the Context Restore gets triggered while loading and re-queue the assets.  

Not the nicest of solutions, but works!

**Comment by PrimaryFeather** [comment]
The preview version of the new AssetManager is now available — see [this forum post](https://forum.starling-framework.org/topic/beta-new-assetmanager). Could you try if the new version solves your problem?

* If it does — great! :smile:
* If it does not, we can start working on a minimal example for me to reproduce the issue. 

Thanks in advance for trying it out!

**Comment by Constans** [comment]
Hello Daniel,

Been really busy these days, couldn't focus much today. 

I'll give it a spin asap and get back to you with a confirmation or the contrary.

Thank you!

**Comment by Constans** [comment]
Tried a fast glue on the **assets** package in the current project and it seems that the change is dependent on other class changes in the project (**Texture** for example).

I will try with Starling uncompiled into a library in a test project, though I'll be able to do that in the weekend.

**Comment by PrimaryFeather** [comment]
My personal tests indicate that this doesn't happen with the latest AssetManager, and I didn't get any more reports about it. Thus, I'm closing this issue!
