### ISSUE TITLE
Feature Request: Add "Enhanced" to profiles requestContext3D tries when "auto" is supplied

### ISSUE THREAD

**Issue by JohnBlackburne** [Gamua/Starling-Framework#1019]
You can request "Enhanced" manually but it makes sense to add it to the list it tries for "auto". It will mean you can still just specify "auto" and get the best. It will also be helpful to know how often it uses the "Enhanced" profile, for any developers interested in using the new features added with this profile. E.g. I use the following to grab the profile which I print out if I enable debug printing:

`str = "Profile: " + gStarling.profile;`

**Comment by PrimaryFeather** [comment]
Thanks for the reminder, John! Done.
