### ISSUE TITLE
Starling won't play video on Google Chrome (Desktop)

### ISSUE THREAD

**Issue by AlexUrrutia** [Gamua/Starling-Framework#1020]
**Target: Flash player on Desktop Browsers:
it works on Safari, Firefox, but it does not work on Google Chrome, it plays audio only** 

`var player:VideoPlayer = new VideoPlayer();
        player.setSize(320, 300);
        player.videoSource = "bunny.mp4";
        this.addChild(player);
        var loader:ImageLoader = new ImageLoader();
        player.addChild(loader);`

![chrome](https://user-images.githubusercontent.com/7042361/36342135-c57ece96-13c7-11e8-9b33-df95894426e1.png)
![safari](https://user-images.githubusercontent.com/7042361/36342136-c6a2f4dc-13c7-11e8-9958-2718f68913bb.png)

**Comment by PrimaryFeather** [comment]
We probably need to report this to Adobe or Google. Could you upload the video (or any video) that produces the error?

**Comment by AlexUrrutia** [comment]
it happens with any video mp4 or live video via rtmp, and Texture.FromNetStream as well

the video file: [https://s3.amazonaws.com/flaxbinpic/bunny.mp4](https://s3.amazonaws.com/flaxbinpic/bunny.mp4)

**Comment by PrimaryFeather** [comment]
I tested this on both MacOS and Windows and can confirm your findings.
For easier testing, I created a sample webpage that attempts to play back a video, to be found [here](http://gamua.com/media/starling/demos/video/). The source code is [on GitHub](https://gist.github.com/PrimaryFeather/19fa9fd0c2fcb0b44fd088411c84d274).

I'll forward this information to Adobe!

**Comment by AlexUrrutia** [comment]
Thank you, Let's hope they fix this ASAP

**Comment by PrimaryFeather** [comment]
Okay, I've received some information from Adobe about this issue. It seems that the alpha value in the video is zero in this Chrome version — for whatever reason. I'll try to get them to restore the old behavior, of course.

In the meantime, here's a workaround for you. First, enable `premultipliedAlpha` in the _ConcreteVideoTexture_ constructor by changing [this line](https://github.com/Gamua/Starling-Framework/blob/5a7be1c83c2b292b12d409cd63c28799723f16d3/starling/src/starling/textures/ConcreteVideoTexture.as#L36):

```as3
        public function ConcreteVideoTexture(base:VideoTexture, scale:Number=1)
        {
            super(base, Context3DTextureFormat.BGRA, base.videoWidth, base.videoHeight, false,
                  true, false, scale); // <-- first argument changed to 'true'
        }
``` 

Then you need to change the _BlendMode_ of the image that's displaying the video, like this:

```as3
image.blendMode = starling.display.BlendMode.NONE;
```

That should fix the issue on Chrome, and will have no negative side effects in other browsers. 

Again, this is just a workaround — I hope this helps for now. Cheers!

**Comment by AlexUrrutia** [comment]
@PrimaryFeather Thanks for the update, it seems to be working with this workaround, I can't understand why they set video alpha to zero, very strange

**Comment by PrimaryFeather** [comment]
I just received word from Adobe that this problem is now fixed! When I run the [demo video](link
http://gamua.com/media/starling/demos/video/) in the latest Chrome (which run with Flash version 31.0.0.122 for me), the video plays just fine.

Thus, I'll close this issue for now. If you could confirm the fix on your side, too, it would be appreciated, though. :smile:
