### ISSUE TITLE
Error on the AIR 29 and Starling 1.8

### ISSUE THREAD

**Issue by alevys** [Gamua/Starling-Framework#1024]
Hello! I tried to build desktop build on AIR29 on Windows 10 and Starling 1.8 and got this error. On OSX no problems, only windows! What the can be done with this?

https://ibb.co/fm8d9c

**Comment by PrimaryFeather** [comment]
Hm ... "internal error" is unfortunately the kind of error that's hard to pin down.

When you enable "starling.enableErrorChecking", is there maybe anything else to see?

Also, try if a different profile changes anything — perhaps "baseline" works better?

**Comment by roipeker** [comment]
Same here Daniel,
 
AIR 29.0.0.120, latest Starling commit from github.
All profiles are failing, running Windows 10 in VM (Parallels Desktop) on my Macbook.

I put the video memory to 2GB... same results.

starling.enableErrorChecking doesn't give me more info....

```
ArgumentError: Error #3672: Buffer creation failed. Internal error.
	at flash.display3D::Context3D/createVertexBuffer()
	at starling.rendering::VertexData/createVertexBuffer()[...\rendering\VertexData.as:904]
	at starling.rendering::Effect/uploadVertexData()[...\rendering\Effect.as:217]
	
```

**Comment by PrimaryFeather** [comment]
Please try what happens when you use the following compiler argument (using AIR 29): -swf-version=37

Does that change anything?

**Comment by PrimaryFeather** [comment]
Lacking any information on the proposed workaround, I'll close this issue now.
