### ISSUE TITLE
Video Issues on iOS (missing audio)

### ISSUE THREAD

**Issue by urthling** [Gamua/Starling-Framework#1029]
<body><p>The following plays properly on iPhone X and Android</p>
<p></p>
<p>Video is OK but the <strong>audio is missing</strong> on: iPhone 5S, iPhone 7+, iPhone 8+ (no other iPhone tested)</p>
<p></p>
<p>Tested using AIr 27/2.2 through 30/2.3</p>
<p>Testing using ffmpeg encode settings:</p>
<table class="table-bordered table-striped table table-presets" style="margin-bottom: 24px; border: 1px solid #dddddd; color: #444444; font-family: Roboto, 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;">
<tbody>
<tr style="background-color: #f9f9f9;">
<td class="centric" style="padding: 8px; border: 1px solid #dddddd; text-align: center;"><code style="font-family: Menlo, Monaco, Consolas, 'Courier New', monospace; font-size: 12.6px; color: inherit; background: transparent;">mp4</code></td>
<td class="centric" style="padding: 8px; border: 1px solid #dddddd; text-align: center;"><code style="font-family: Menlo, Monaco, Consolas, 'Courier New', monospace; font-size: 12.6px; color: inherit; background: transparent;">libfdk_aac</code></td>
<td class="centric" style="padding: 8px; border: 1px solid #dddddd; text-align: center;"><code style="font-family: Menlo, Monaco, Consolas, 'Courier New', monospace; font-size: 12.6px; color: inherit; background: transparent;">128000</code></td>
<td class="centric" style="padding: 8px; border: 1px solid #dddddd; text-align: center;"><code style="font-family: Menlo, Monaco, Consolas, 'Courier New', monospace; font-size: 12.6px; color: inherit; background: transparent;">44100</code></td>
<td class="centric" style="padding: 8px; border: 1px solid #dddddd; text-align: center;"><code style="font-family: Menlo, Monaco, Consolas, 'Courier New', monospace; font-size: 12.6px; color: inherit; background: transparent;">libx264</code></td>
<td class="centric" style="padding: 8px; border: 1px solid #dddddd; text-align: center;"><code style="font-family: Menlo, Monaco, Consolas, 'Courier New', monospace; font-size: 12.6px; color: inherit; background: transparent;">1200000</code></td>
<td class="centric" style="padding: 8px; border: 1px solid #dddddd; text-align: center;"><code style="font-family: Menlo, Monaco, Consolas, 'Courier New', monospace; font-size: 12.6px; color: inherit; background: transparent;">1024x768</code></td>
</tr>
</tbody>
</table>

<p></p>
<p><span>I also found a test stream that you can use to reproduce the issue described above: </span><a href="/external-link.jspa?url=https%3A%2F%2Fcontent.jwplatform.com%2Fmanifests%2Fyp34SRmf.m3u8" rel="nofollow" target="_blank" _jive_internal="true">https://content.jwplatform.com/manifests/yp34SRmf.m3u8</a></p>
<p>Taken from here: <a href="https://developer.jwplayer.com/tools/stream-tester/?playerversion=7" title="https://developer.jwplayer.com/tools/stream-tester/?playerversion=7">https://developer.jwplayer.com/tools/stream-tester/?playerversion=7</a></p></body>

There's also this taken from another bug related to video on this forum: https://s3.amazonaws.com/flaxbinpic/bunny.mp4

```
protected function test_triggeredHandler(event:Event):void
{
  vidClient = new Object();
  vidClient.onMetaData = onMetaData;
  nc = new NetConnection();
  nc.connect(null);
  ns = new NetStream(nc);
  ns.addEventListener(NetStatusEvent.NET_STATUS, onNetStatus);
  ns.client = vidClient;
  videoTexture=Texture.fromNetStream(ns , Starling.current.contentScaleFactor , onTextureComplete)
  ns.play("https://somevideo.mp4");
}
  private function onTextureComplete():void
  {
       videoImage = new Image(videoTexture)
       this.addChild(videoImage)
  }
  private function onMetaData():void
  {
       trace('on net onMetaData');
  }
  private function onNetStatus(event:NetStatusEvent):void
  {
       trace('on net status');
  }
```

**Comment by PrimaryFeather** [comment]
Hey @urthling,
from your description, this seems to be a bug in the AIR runtime, not Starling. Could you create the issue here instead? → https://github.com/Gamua/Adobe-Runtime-Support 
And don't forget to open a bug report on tracker.adobe.com, as well. 

Thanks in advance!

**Comment by urthling** [comment]
You bet - did as you suggested..  ty for heads up and of course for Starling! :)

**Comment by PrimaryFeather** [comment]
Perfect, thanks! :smile:
