### ISSUE TITLE
Question: terrain skinning

### ISSUE THREAD

**Issue by CrazyFlasher** [Gamua/Starling-Framework#1034]
Hi.
I have a game with physics terrain. I also have a list of vertices of this terrain.
I am trying different ways of skinning this terrain and currently would like to create visually something like this:
http://flashdaily.net/post/78833707199/free-form-2d-terrain-built-with-flash

So terrain will be filled with tiles. That's no problem. But how to draw tiles borders that will orient path and will be only visible on  horizontal surfaces (like on image)? What should I read and where should I dig?
![image](https://user-images.githubusercontent.com/1607138/42148325-72c8aa28-7dda-11e8-85d4-2802f48dbff4.png)

Can you help me with tools and solutions?

**Comment by JohnBlackburne** [comment]
Not really a Starling issue; briefly you need to organise your tile data into e.g. a grid. Then the edges of your blocks of tiles are on top of the topmost tiles in each column of your grid. Better to ask on the Starling forum than here.
