### ISSUE TITLE
TouchProcessor.enqueue creates a lot of arrays

### ISSUE THREAD

**Issue by subdan** [Gamua/Starling-Framework#1037]
Hello, Daniel.

I noticed that TouchProcessor class creates new array on every `enqueue` call.

` _queue.unshift([1, phase, _touchMarker.mockX, _touchMarker.mockY]);`

I think it will be better to create the array once and use it instead of creating new array on each `enqueue` call. Like this:

```
tempArray[0] = 1
tempArray[1] = phase
tempArray[2] = _touchMarker.mockX;
tempArray[3] = _touchMarker.mockY];
 _queue.unshift(tempArray);
```

**Comment by subdan** [comment]
I've found the same issue `https://github.com/Gamua/Starling-Framework/issues/1025`
So, the main issue is using **_queue.unshift(arguments);**
Could you please fix it?

**Comment by PrimaryFeather** [comment]
Yeah, this finally needs to be addressed. You'll get an update tomorrow!

**Comment by subdan** [comment]
Thanks!

**Comment by PrimaryFeather** [comment]
I just made that change — please have a look and let me know it that works for you!

**Comment by subdan** [comment]
Thank you, Daniel!
