### ISSUE TITLE
Sample build settings

### ISSUE THREAD

**Issue by JohnBlackburne** [Gamua/Starling-Framework#1047]
Just trying building the sample in /samples/demo_web and I had to change two things to get it to work

Change the dependencies line to 

        classpath group: 'org.gradlefx', name: 'gradlefx', version: '1.4.0'

Change one of the additionalCompilerOptions to

       '-target-player=19.0',

Obviously Starling needs Flash 19 or later now. The dependencies line is from the gradlefx documentation.

**Comment by JohnBlackburne** [comment]
Also to get it to build a version that works I needed to change one more of the additionalCompilerOptions:

        '-swf-version=30'

That’s the version matching Flash Player 19

**Comment by PrimaryFeather** [comment]
You're totally right, thanks a lot for the heads-up! I totally forgot that there even was a gradle script available for the samples. :wink: Now it's working again!
