### ISSUE TITLE
Please add the possibility to configure multi-Touch at run-time

### ISSUE THREAD

**Issue by ronyarbiv** [Gamua/Starling-Framework#1048]
Hi,

Thank yous so much for Starling :)
It will be amazing if you will add the possibility to configure multi-Touch at run-time.

[https://forum.starling-framework.org/topic/multitouch-programmatically-enabled-disabled](url)

Best wishes,
Rony

**Comment by PrimaryFeather** [comment]
I'm already working on it! Thanks for setting up the issue! :smile:

**Comment by PrimaryFeather** [comment]
You can now enable or disable multitouch anytime via the static `Starling.multitouchEnabled` property. :smile: Thanks again for the reminder!

**Comment by ronyarbiv** [comment]
That's amazing!!
Thank you so much:)

Rony
