### ISSUE TITLE
DisplayObject drawToBitmapData no transparency on Android

### ISSUE THREAD

**Issue by CrazyFlasher** [Gamua/Starling-Framework#1049]
Starling release 2.4
AIR SDK 30
Trying both with `Context3DProfile.BASELINE` and `Context3DProfile.BASELINE_CONSTRAINED`

**Fine on Desktop**
![image](https://user-images.githubusercontent.com/1607138/50204768-94d84c80-036e-11e9-9a57-ec7d8ee3b047.png)

**No transparency on Android**
![image](https://user-images.githubusercontent.com/1607138/50204732-783c1480-036e-11e9-9a72-e53fdf59749d.png)

**Comment by PrimaryFeather** [comment]
I'm happy to hear you found the solution!

To be honest, I don't know if it makes a difference performance-wise. My guess is that it shouldn't, given the great GPUs of modern devices — but it's just a best guess.
