### ISSUE TITLE
Filters are missing support for antialiasing

### ISSUE THREAD

**Issue by johnridges** [Gamua/Starling-Framework#1051]
When a filter draws the DisplayObject into its temporary texture, the anti-aliasing is always 0. This means that filtered objects can't be anti-aliased, whereas unfiltered objects can be using the global antiAliasing setting. It would be nice if filters had an "antiAliasing" property like RenderTexture does.

**Comment by PrimaryFeather** [comment]
Hey John!
You mean like [this property](link
http://doc.starling-framework.org/current/starling/filters/FragmentFilter.html#antiAliasing)? :wink:

Or doesn't that work for you? Just let me know!

**Comment by PrimaryFeather** [comment]
Lacking a reply, I guess that property fixed it for you. :wink: 
I'll close this issue!
