### ISSUE TITLE
How to compare 2.4.2 to 2.4.1

### ISSUE THREAD

**Issue by chrisvelevitch** [Gamua/Starling-Framework#1052]
Up until recently, I've been using 2.4.1 and then I updated to 2.4.2 which resulted in my project no longer compiling. I switched back to 2.4.1 and the problem goes away. I wanted to see what the differences are between the two only to be disappointed in that there no branches for either version.

Where do I find the code bases for 2.4.1 and 2.4.2?

**Comment by JohnBlackburne** [comment]
Here’s a comparison of 2.4.1 to the current master:

https://github.com/Gamua/Starling-Framework/compare/a1ae146...master

Select 'files changed' to view individual changes in files. There are a lot of them though. If you are seeing compile errors post them, as that will narrow things down greatly.

**Comment by PrimaryFeather** [comment]
Yeah, please let me know the exact compiler errors you're getting! Thanks in advance!

**Comment by chrisvelevitch** [comment]
@JohnBlackburne So you are saying `master` is `2.4.2` as there hasn't been any new commits since `2.4.2` was released? And where does it say commit `a1ae146` is `2.4.1`? Isn't it best practice to tag the commit that was used to create a release with the release number? I don't see and tags for `2.4.1` and `2.4.2`.

@PrimaryFeather The compile error is:-
```
Error:(2004, 37) Class<starling.display.Mesh> has no field createDefaultStyle (Suggestions: set_defaultStyle, get_defaultStyle)
```
but looking closely at that class, I don't understand why I'm getting the error.

**Comment by JohnBlackburne** [comment]
createDefaultStyle is a static function. You need to call it like this

    Mesh.createDefaultStyle(mesh)

not

    mesh.createDefaultStyle()

which will generate an error like that

**Comment by PrimaryFeather** [comment]
No problem! :smile:
