### ISSUE TITLE
Filter Chain: Null Object Reference when empty

### ISSUE THREAD

**Issue by Adolio** [Gamua/Starling-Framework#1063]
Hi Daniel!

I just discovered that `FilterChain` doesn't like to be empty and I was wandering if this was intended by design?

He is a simple code to reproduce:
```as3
var quad:Quad = new Quad(1, 1);
quad.filter = new FilterChain();
addChild(quad);
```

Best,
Aurélien

**Comment by PrimaryFeather** [comment]
Excellent point, Aurélien! I fixed that right away. Now, an empty _FilterChain_ just acts like a standard _FragmentFilter_ — which should make some situations easier to handle.

Thanks for making me aware of this!

**Comment by Adolio** [comment]
😃 Thanks a lot Daniel!
