### ISSUE TITLE
Flash DisplayObjects triggering touch began events in Starling?

### ISSUE THREAD

**Issue by jgranick** [Gamua/Starling-Framework#1064]
I've received this pull request:

https://github.com/openfl/starling/pull/141

Does this occur in the Flash version of Starling?

If Flash DisplayObjects do still trigger events on Starling below it would be great to know if this kind of change would be desirable here in the ActionScript version of Starling, or if this is desired behavior or possibly OpenFL is working differently in this area

Thank you for your help!

**Comment by jgranick** [comment]
Oh, so `nativeOverlayBlocksTouches` is what this is for?

**Comment by PrimaryFeather** [comment]
Hey Joshua,
sorry for the late reply! Somehow this message got lost in the pre-holiday madness. :wink:

The property `nativeOverlayBlocksTouches` makes `flash.display` DisplayObjects behave just like you would expect them to behave if they were `starling.display` DisplayObjects, i.e. if you click on such an object, the objects beneath won't receive any Touch events.

With that property disabled, both Flash and Starling will receive the mouse/touch event, which makes it rather difficult to handle properly.

In both cases, if you click on outside the `flash.display` objects, Starling will receive the touches just as usual.

Is that what you wanted to know?
Cheers!

**Comment by jgranick** [comment]
Okay I think that makes sense

So if you want a Flash display object to block touches/clicks to Starling then you must add it to the `nativeOverlay` `Sprite`?

**Comment by PrimaryFeather** [comment]
Yes, that behavior is currently implemented only for the native overlay.
