### ISSUE TITLE
Call to a possibly undefined method AccessibilityProperties. When Run

### ISSUE THREAD

**Issue by TangMonk** [Gamua/Starling-Framework#1065]
I am follwing tutorial to create a Startup.as and a Game.as:

Startup:

```
package  {
	
	import flash.display.Sprite;
	import starling.core.Starling;

	
	public class Startup extends Sprite
	{
		private var _starling:Starling;

		public function Startup()
		{
			_starling = new Starling(Game, stage);
			_starling.start();
		}
	}
}

```

Game.as:

```
package{


	import starling.display.Sprite;
	import starling.text.TextField;

	public class Game extends Sprite
	{
		public function Game()
		{
			var textField:TextField = new TextField(400, 300, "Welcome to Starling!");
			addChild(textField);
		}
	}

}	
```

When I run, the error throw:
```
Startup.as, Line 13, Column 29	1120: Access of undefined property Game.
Startup.as, Line 3, Column 26	1180: Call to a possibly undefined method AccessibilityProperties.
```

![image](https://user-images.githubusercontent.com/3498786/73605637-a5cc3780-45db-11ea-820d-4f9e06600348.png)

I have proper config the path:

![image](https://user-images.githubusercontent.com/3498786/73606513-f47ecf00-45e5-11ea-814e-ab0e758d31cd.png)
![image](https://user-images.githubusercontent.com/3498786/73606515-f9438300-45e5-11ea-91fc-cd7448f886d6.png)

I am using Animate 2020

**Comment by PrimaryFeather** [comment]
I saw that you were already able to fix this via [help fro the Starling Forum](https://forum.starling-framework.org/d/22226-cannot-initialize-starling-in-animate-cc-2020/2). Glad to see that!

So I'm closing this issue.

**Comment by TangMonk** [comment]
Thanks!
