### ISSUE TITLE
Button touch bounds is offset

### ISSUE THREAD

**Issue by Dimensionscape** [Gamua/Starling-Framework#1066]
![offset](https://user-images.githubusercontent.com/26172437/74244849-13e5be00-4cb0-11ea-96d6-8bbc4a8af303.jpg)

In 2.6, the area that receives touch on starling buttons is offset and interferes with other button display objects.

**Comment by PrimaryFeather** [comment]
Ah ... damn, I should have made that default for the minimum touch-size smaller for desktop. Thanks for the heads-up! I'll fix that for you.

**Comment by PrimaryFeather** [comment]
I changed `minHitAreaSize` of the _Button_ class to 16 (from 44) when on Desktop.
What do you say — does that work out?

Cheers!
