### ISSUE TITLE
Textured mesh

### ISSUE THREAD

**Issue by CrazyFlasher** [Gamua/Starling-Framework#1070]
Is it possible to achieve something like this without Spine, DragonBones and etc.?

 https://pixijs.io/examples/#/mesh-and-shaders/textured-mesh-basic.js

**Comment by JohnBlackburne** [comment]
Yes. It’s not a Starling issue though. It’s a more general problem in animation; you could ask on the Starling forums, or on a more general forum.

**Comment by PrimaryFeather** [comment]
Thanks for creating the thread in the forum! ([Here](https://forum.starling-framework.org/d/22266-texured-mesh-animation), for reference.) This question is indeed better suited for the forum.
