### ISSUE TITLE
Glow Filter: Color issue

### ISSUE THREAD

**Issue by Adolio** [Gamua/Starling-Framework#1074]
Hi Daniel,

I just discovered an issue with the new `GlowFilter` version from Starling version `2.6`. Apparently the new implementation doesn't support white color anymore (and maybe other colors).

In `2.5.1`:
![Screen Shot 04-10-20 at 12 06 AM](https://user-images.githubusercontent.com/1126990/78945087-bc04e100-7abf-11ea-98d2-b13b84b9672f.PNG)

In `2.6`:
![Screen Shot 04-10-20 at 12 08 AM](https://user-images.githubusercontent.com/1126990/78945089-bc9d7780-7abf-11ea-897c-3d4135e5e30c.PNG)

Code to reproduce:
```as3
package
{
	import starling.display.Quad;
	import starling.display.Sprite;
	import starling.filters.GlowFilter;
	import starling.core.Starling;
	
	public class GlowTest extends Sprite
	{
		public function GlowTest()
		{
			Starling.current.stage.color = 0x555555;
			
			var q:Quad = new Quad(100, 100, 0x0);
			q.filter = new GlowFilter(0xffffff);
			q.x = (Starling.current.stage.stageWidth - q.width) * 0.5;
			q.y = (Starling.current.stage.stageHeight - q.height) * 0.5;
			addChild(q);
		}
	}
}
```

Best,
Aurélien

**Comment by PrimaryFeather** [comment]
Hey Aurélien!
Hm, that's strange. In the Starling Demo scene where I'm showing filters, it works fine. However, when I run your demo, I can reproduce the error.

I'll look into it – thanks a lot for the heads-up!

**Comment by PrimaryFeather** [comment]
I've got it! The problem was that I didn't always assign the `replaceColor` setting of the filter effect. The same happened on the _DropShadowFilter_.

It's now fixed. Thanks again for making me aware of this, Aurélien!

**Comment by Adolio** [comment]
Excellent! Thanks again Daniel for you fast reaction! 😀

I'm taking the opportunity to ask you if there is any easy way to get access to the `swc` library of the current `master`? Thanks in advance for your help.

**Comment by PrimaryFeather** [comment]
You're welcome, Aurélien! 

Hm, unfortunately there isn't any pre-compiled SWC for non-released versions. You have to build it yourself, or reference Starling's source code / project directly (that's what I always do).

**Comment by Adolio** [comment]
Alright, I will try build it myself or I might fallback to a classpath addition until `2.6.1` get released (if that's your plans).

See you :) !

**Comment by PrimaryFeather** [comment]
Ah, you know what? I made a quick (but untested!) build for you:
https://web.tresorit.com/l#o_NimMyruWmJuCtWLtj-lA

I hope that helps! 😄 
Cheers!

**Comment by Adolio** [comment]
Thanks a lot 😊
