### ISSUE TITLE
native overlay now block touch and mouse input

### ISSUE THREAD

**Issue by pol2095** [Gamua/Starling-Framework#1075]
Hello,

since Starling 2.5, Objects that are part of the native overlay now block touch and mouse input, just like Starling display objects would, but is-it possible to deactivate this ?

`stage.starling.nativeOverlay.mouseEnabled = false;`
doesn't work ?

Thanks

**Comment by PrimaryFeather** [comment]
I'm sure you already found the solution (and thus closed this issue), but just for reference if someone else lands on this page: the relevant property is found on the Starling instance, and it's called [nativeOverlayBlocksTouches](https://doc.starling-framework.org/current/starling/core/Starling.html#nativeOverlayBlocksTouches).
