### ISSUE TITLE
AssetManager problem

### ISSUE THREAD

**Issue by Mintonist** [Gamua/Starling-Framework#1080]
Hi!

UPD. Sorry about previous problem descr - I'm confused trying to find the reason. Here is original problem:

I noticed strange thing with my spritesheets.

I have 4 files created by TexturePacker:
![2020-09-12_022239](https://user-images.githubusercontent.com/9267850/92980424-da23a280-f49e-11ea-80cb-30d5a54849e0.png)
And my game screen looks like:
![2020-09-12_120618](https://user-images.githubusercontent.com/9267850/92992072-b7ba7500-f4f0-11ea-9599-9d363c69bdfa.png)
Right version must be:
![2020-09-12_120650](https://user-images.githubusercontent.com/9267850/92992078-c3a63700-f4f0-11ea-9d54-3cee662cdd61.png)

I noticed that all textures from gui2 atlas aren't visible. 

Link to these files - https://www.dropbox.com/t/4nOMVUJb4960o8gg

Any ideas?)

**Comment by esdebon** [comment]
Maybe your file gui_1.xml have the wrong name in the imagePath

<TextureAtlas imagePath="gui_2.png" width="2048" height="2048">

instead

<TextureAtlas imagePath="gui_1.png" width="2048" height="2048">

**Comment by Mintonist** [comment]
esdebon, sorry! I'm confused trying to find the reason. I updated post with original problem:

**Comment by PrimaryFeather** [comment]
What's the trace output shown while the asset manager is processing the files? Is there anything suspicious?

**Comment by Mintonist** [comment]
[trace] [AssetManager] Enqueuing 'gui_1.png'
[trace] [AssetManager] Enqueuing 'gui_1.xml'
[trace] [AssetManager] Enqueuing 'gui_2.png'
[trace] [AssetManager] Enqueuing 'gui_2.xml'
[trace] [AssetManager] Enqueuing 'Troika.png'
[trace] [AssetManager] Enqueuing 'Troika.fnt'
[trace] [AssetManager] Enqueuing 'graphics.json'
[trace] [AssetManager] Adding xml 'gui_1'
[trace] [AssetManager] Adding xml 'gui_2'
[trace] [AssetManager] Adding texture 'gui_2'
[trace] [AssetManager] Adding xml 'Troika'
[trace] [AssetManager] Adding object 'graphics'
[trace] [AssetManager] Adding texture 'gui_1'
[trace] [AssetManager] Adding texture 'Troika'
[trace] [Starling] Warning: frames inside the texture's region are unsupported.
[trace] [AssetManager] Adding textureAtlas 'gui_1'
[trace] [AssetManager] Adding textureAtlas 'gui_2'
[trace] [AssetManager] Adding bitmapFont 'Troika'

What about is this warning? If I use another scale (all image fit one atlas) - warning exist but all looks fine in game.(https://www.dropbox.com/t/OhzBqVXKzybmhCmE).

**Comment by PrimaryFeather** [comment]
Hm, I think that warning only means that _too much_ of a certain texture will be displayed, so that's probably not it.

What's really strange is that you don't get any null reference exception. If the textures couldn't be accessed, you'd definitely get some of those.

Another question: if you set `Starling.current.enableErrorChecking = true`, do you get any additional output?

**Comment by Mintonist** [comment]
Only this:
[Starling] Full mask support requires 'depthAndStencil' to be enabled in the application descriptor.

**Comment by PrimaryFeather** [comment]
That's unrelated to this problem, but you should definitely enable "depthAndStencil" in your application descriptor, like [here](https://github.com/Gamua/Starling-Framework/blob/64ebb1d22d3ff5b7b71e8a3b8e1202e4e1a9d83c/samples/scaffold_mobile/src/Scaffold_Mobile-app.xml#L28).

As for our main problem, I'm slowly running out of ideas. 😕
If you add those same two texture atlases to a separate, new project: does that work? Or are still just the images of one of the atlases visible?

**Comment by Mintonist** [comment]
Mystery thing!
I rename "gui_2" files to "test" and it works!

In my other project I have "gui_1" and "gui_2" files and have no sucj problems. Seems because combinations of file names and texture names inside spritesheets.

**Comment by PrimaryFeather** [comment]
This is really weird. I can't think of an explanation of this behavior right now ... those names really shouldn't make a difference ...!

However, I'm happy to hear that you found a workaround, at least – the most important thing is that you're not blocked by this!
