### ISSUE TITLE
Reverse delay for Tween

### ISSUE THREAD

**Issue by Mintonist** [Gamua/Starling-Framework#1081]
Hi!

"reverse" flag is very useful for me. But I need different delays for forward and back animation. For example - heartbeat.
Not likely to be used with TweenMax etc.

One more helpfully thing. It is "autohide" flag for auto set visible=false at the end of animation. And visible=true on beginning.
Or you may add callbacks "onRepeatStart" / "onRepeatFinish".

Thx!

**Comment by PrimaryFeather** [comment]
Agreed, that sounds useful! Thanks for the suggestion!

**Comment by Mintonist** [comment]
One more suggestion)
Do you think about TweenChain as series of tweens? It can be repeated, reversed, delayed - all as single Tween.

**Comment by Mintonist** [comment]
https://github.com/Gamua/Starling-Framework/pull/1117
