### ISSUE TITLE
Juggler: String allocation when using IAnimatable as a Dictionary key

### ISSUE THREAD

**Issue by Adolio** [Gamua/Starling-Framework#1098]
Hey Daniel,

While doing few optimizations by tracking down all possible allocations in my game, I noticed that the `Juggler` class is actually allocating quite a lot of `String` in my case.

Apparently, AIR is automatically calling the `toString()` method of an object when it used as a key in a `Dictionary`: https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/utils/Dictionary.html

From Scout:
![Scout_Juggler_String_Allocations](https://user-images.githubusercontent.com/1126990/177050581-3673fc84-fd2a-424f-80b7-bb02f5e17ac7.png)

Line in question in the `Juggler` class:
![Juggler_Allocation_Cause](https://user-images.githubusercontent.com/1126990/177050595-2f567563-5345-4bdf-94a1-8a165941b86f.png)

@PrimaryFeather Do you remember if this dictionary optimization was important the framework or if I could somehow change the code to simply browse the list instead of having the object being indexed?

My goal here is to have more control over the allocations but more importantly for the performance drops related to the garbage collector "passage" 😉

Thanks in advance for your help!

Best,
Aurélien

**Comment by Adolio** [comment]
Since code worth hundred of words, here is an early change proposal: https://github.com/Adolio/Starling-Framework/tree/juggler-memory-imp (to be tested..) 🙂

**Comment by PrimaryFeather** [comment]
Hey Aurélien!

As far as I remember, there's no specific reason I used the Dictionary in that case – probably I thought it would just be the most efficient way to do it, but that's definitely not the case if AIR is allocating lots of Strings for such an operation. 😱

So you're way of doing it is definitely preferable! I don't see any downsides. Could you maybe turn this into a pull request? Then I'll happily merge that change into the master branch.

Thanks a lot for making me aware of this! 👍

**Comment by Adolio** [comment]
Thanks for your answer Daniel :)

Here is the PR: https://github.com/Gamua/Starling-Framework/pull/1099

Happy review!

**Comment by PrimaryFeather** [comment]
Thanks a lot for the pull request! In the meantime, it has been merged – so I think we can close this issue! 😄 
Thanks again!
