### ISSUE TITLE
[Request] Re-add Web Demo source

### ISSUE THREAD

**Issue by Fancy2209** [Gamua/Starling-Framework#1111]
It's a great resource for working on flash emulators, could it be re-added to the repo?

**Comment by PrimaryFeather** [comment]
If you think that makes sense, we can do that! 

Could you maybe create a pull request with that change, with a short explanation inside the README file of that directory? Then I'll merge that right away.

**Comment by Fancy2209** [comment]
Sounds good, will do it when I ASAP
