### ISSUE TITLE
Dead link in tests/README.md (+ other documentation issue(s))

### ISSUE THREAD

**Issue by JL2210** [Gamua/Starling-Framework#1114]
The link in tests/README.md to an archive with the required libraries to run the tests (http://goo.gl/KypNQT) redirects to a Google Drive file that no longer exists.

Not making a new issue for this because I don't feel it's warranted (also can't find a separate repo for [the manual](https://manual.starling-framework.org/en/#_intellij_idea)?): IntelliJ Idea Ultimate is also available for Linux.

**Comment by PrimaryFeather** [comment]
Ah, thanks for making me aware of this, @JL2210! I replaced the link with a new one. 👍
