### ISSUE TITLE
Scrolling under mask

### ISSUE THREAD

**Issue by Mintonist** [Gamua/Starling-Framework#1116]
Is it a bug with scrolling under mask or not?)

My display objects layers in Animate:
![image](https://github.com/user-attachments/assets/5de0fa25-0a00-479e-b128-35942728abdf)

I write own converter from Animate .swf to Starling display objects.

I set mask in my code:
`mc_main.mask = mc_mask;`

and make my own scrolling logic by changing `mc_main.x` value.

All is good except children's hover and Event.TRIGGERED area. See attached video:
https://github.com/user-attachments/assets/205c961e-ba7e-49b2-9553-975e4f1737b9

Any ideas?)

**Comment by PrimaryFeather** [comment]
Hey @Mintonist!

Sorry to hear about those issues! I haven't heard of that problem before. Do you think it's possible to reproduce this in a compact example, to be able to get to the root of the problem?

Thanks in advance!

**Comment by Mintonist** [comment]
Hi @PrimaryFeather !
Demo project - 
[DemoStarling_2024.11.08.zip](https://github.com/user-attachments/files/17677286/DemoStarling_2024.11.08.zip)

**Comment by PrimaryFeather** [comment]
Hey @Mintonist,
I think I found the problem! The mask hit test logic reused a helper `Point` to avoid temporary objects. And your specific setup caused this code to be called recursively, which caused that point to be changed when it shouldn't be. 😉 

I removed that static helper point and replaced it with a point from the object pool. This is much safer - and, hurray, it also fixes your problem. At least in the demo you sent me. 😃 

Please try out if this also works for your actual game. But I'm optimistic that this was it.

Thanks for making me aware of this! Funny that this didn't pop up earlier. 🙏

**Comment by Mintonist** [comment]
Yes, now it works properly!)
Thx!
