### ISSUE TITLE
multitouchEnabled to true disable the TRIGGERED event

### ISSUE THREAD

**Issue by avilaviad** [Gamua/Starling-Framework#216]
When adding the flag 'Starling.multitouchEnabled = true' it disable the TRIGGERED events of buttons and also the downState auto effect.

**Comment by fideldonson** [comment]
I am able to reproduce this issue with a minimal project i have set up in Adobe Animate, Flash Builder 4.7 and Flashdevelop. All with fully updated starling swcs and air sdks.
Let me know if you want the code.

**Comment by PrimaryFeather** [comment]
Yes, that would be great! Thanks a lot in advance.

**Comment by Lucapresidente** [comment]
Any news about this issue? I've experienced that on Flash Builder 4.7 only in the emulator, with two different projects, a mobile app made with feathers and a game made with Citrus Engine when I upgraded to Air 22 (or 23)

**Comment by PrimaryFeather** [comment]
@Lucapresidente, could you try to reproduce the problem in a minimal sample project? Then I could look into it.

**Comment by Lucapresidente** [comment]
here it is, I've tested it with Air 22, 23, 24. Adobe Flash Builder 4.7
[Multitouch.zip](https://github.com/Gamua/Starling-Framework/files/820898/Multitouch.zip)

**Comment by PrimaryFeather** [comment]
Thanks! I will look into it during the next few days.
