### ISSUE TITLE
Batch drawTriangles with different textures.

### ISSUE THREAD

**Issue by xLite** [Gamua/Starling-Framework#219]
Essentially, what is contained within this excellent article: http://blog.flash-core.com/?p=493

Batch sprite groups that use up to 4 different textures in 1 call. Considering you find performance a constant goal for starling, adding the option for this could come in very handy to those who know what they're doing. When so, they could simply set something like `enableMultiTextureBatching`. I guess the details would be up to you.

Anyway, just  figured I'd bring this article to your attention. Hope it turns out to be useful! :smiley:

**Comment by PrimaryFeather** [comment]
In Starling 2, that's now finally feasible. Right now, it's implemented as an experimental extension: [Cross-Texture Batching](http://wiki.starling-framework.org/extensions/cross-texture-batching). Once it's stable, it might be added to the standard release, though.
