### ISSUE TITLE
GlowFilter and DropShadowFilter implementation

### ISSUE THREAD

**Issue by k0t0vich** [Gamua/Starling-Framework#253]
Daniel, Hi
I implemented two classes
https://github.com/k0t0vich/Starling-Framework/blob/master/starling/src/starling/filters/DropShadowFilter.as
and
https://github.com/k0t0vich/Starling-Framework/blob/master/starling/src/starling/filters/GlowFilter.as
 You can get it.

**Comment by PrimaryFeather** [comment]
I know it has taken a while, but I did remember your suggestions and implemented it like that in Starling 2. So, `DropShadow` and `Glow` are now finally in their own classes. (And it's now even feasible to add things like "innerShadow" to that in the future, thanks to the completely overhauled filter API in Starling 2.
