### ISSUE TITLE
FragmentFilter Textures Converted to Powers of Two Produce Unexpected Results

### ISSUE THREAD

**Issue by devon-o** [Gamua/Starling-Framework#260]
This isn't a bug, but as mentioned in the title, this can produce some unexpected results in any shaders relying on UV coordinates.

It may take a bit of explanation so please bear with me.

In the calculateBounds method of FragmentFilter.as, the bounding rectangle surrounding the filtered display object is calculated. The width and height of that rectangle is then bumped up to the next power of two. The texture that is filtered (and sent to to FragmentFilter's activate() method) is set to those dimensions.

Now say, for an example, I have a game with a character that for some stupid reason is 129 pixels tall. That character is standing in a pool of water, so I write a fragment shader to use as a filter. I pass the value .5 to that shader as I only want to apply the effect to the lower half of the texture (don't want the hero to drown :) ). The problem is, since the texture is now bumped up to the next power of 2, it now has a height of 256 so my water level, rather than being at the (129 * .5) pixel mark is now at the 128 (256 * .5) pixel mark. Assuming the filter effect is visible at all, it only affects the bottom row of pixels of my filtered image - not the whole bottom half of the character as I would have hoped.

As a work around, if you know the dimensions of your filtered object you can send a ratio to the  shader - something like (.5 * actualHeight) / texture.height for example. If you don't know the actual size of your filtered object though (say you have scaling in place where objects are scaled by a user controlled camera or whatever) you can be in real trouble.

One solution would be to not bump up the object's bounds to the next power of 2. Simply commenting out the 2 lines of code which does that solves all problems. However, if that mod was added for future proofing or performance optimization, well, removing it would not be good.

Another idea is perhaps to temporarily save the object's bounds prior to the POT operation and send it to the FragmentFilter's activate() method. That way when writing your own filters you would have access to both a Rectangle instance representing the display objects actual dimension (height of 129 pixels in my example) and the Texture instance (with a height of 256 in my example). Then for UV calculations you can do something like I did above.

Something look at and consider anyway.

Thank you,
-Devon

**Comment by PrimaryFeather** [comment]
While Starling 2 still bumps up the texture a bit (to the next multiple of 64 pixels), you can now access the original bounds of the object, at runtime. Thus, the fragment filter doesn't need to rely on the texture size, but can work with the actual object size.

In other words: I'm closing this issue now. :wink:
