### ISSUE TITLE
[Suggestion] Extendible Movieclips

### ISSUE THREAD

**Issue by erengoc** [Gamua/Starling-Framework#266]
We can add Sound class to any frame of a Movieclip and it is cool. But it would be cooler if can set custom actions to any frame.

Let's say we have an IFrameAction interface with execute method. Sound class may implement it. Or i can create new class that dispatches a custom event on execute method. So i would dispatch event on any frame i want.

Instead of :
var sound:Sound = mSounds[mCurrentFrame];
if (sound) sound.play();

this:
var actions:Vector.<IFrameAction> = mActions[mCurrentFrame];
if(actions)
{
     for(bla bla) (actions[bla] as IFrameAction).execute();
}

I would do this by extending the MovieClip class but all properties are private.

**Comment by PrimaryFeather** [comment]
Starling 2 now contains exactly those "frame actions".
So, after 3 years: mission accomplished! :bowtie:
