### ISSUE TITLE
clipRect with flatten

### ISSUE THREAD

**Issue by SamYStudiO** [Gamua/Starling-Framework#290]
When using clipRect with flatten cliprect is removed. Don't know if this is done on purpose but with feathers scroller for example you cannot use flatten since scroll content will no longer be cropped.

**Comment by PrimaryFeather** [comment]
Problems like this were part of my decision to remove `flatten` in Starling 2 and replace it by an automated render cache, as well as the powerful `MeshBatch` class. 

In other words: issue closed. :wink:
