### ISSUE TITLE
Pixel snapping

### ISSUE THREAD

**Issue by SamYStudiO** [Gamua/Starling-Framework#295]
Could you consider adding a optimize way to round all objects coordinates to nearest pixel?
Actually with non retina/hd display we got blurry image when they re not round to pixel

**Comment by PrimaryFeather** [comment]
3 years later, this finally happened. :bowtie: 

In Starling 2, you can enable `pixelSnapping` on any Mesh (Quad, Image) to have them snap to the nearest pixel.
