### ISSUE TITLE
Browser zoom scaling problem after reload

### ISSUE THREAD

**Issue by kojot1234** [Gamua/Starling-Framework#324]
When scaling the page up (100% and above) without listening to any resize events, the swf content holds the correct scale and isn't scaled up or down. However if the browser zoom level is set to below 100%, and then the project is loaded (or refreshed), the content becomes scaled up. Problem with mClippedViewPort occurs because mNativeStage.stageWidth and mNativeStage.stageHeight are different from the original viewport dimensions. Te touch listeners are in the right spots though. Replacing mClippedViewPort with current mViewPort size fixes the problem, but this probably isn't the right solution to this issue.

Stalring.as - Line 435:
mClippedViewPort = mViewPort.intersection(
   new Rectangle(0, 0, mNativeStage.stageWidth, mNativeStage.stageHeight)); // incorrect scale

//mClippedViewPort = mViewPort; // correct scale

**Comment by PrimaryFeather** [comment]
Lacking additional updates (and since I think this probably was more a Flash plugin bug), I'll close this issue now. Feel free to open it again if you want to continue this discusson.
