### ISSUE TITLE
Add startDrag & stopDrag methods for Sprites

### ISSUE THREAD

**Issue by PrimaryFeather** [Gamua/Starling-Framework#37]

**Comment by Eketol** [comment]
Still waiting :)

**Comment by 22Round** [comment]
+1 for waiting

**Comment by PrimaryFeather** [comment]
I must say I'm no longer sure this is really necessary, since dragging can be achieved as simple as the following:

```as3
sprite.addEventListener(TouchEvent.TOUCH, onTouch);

private function onTouch(event:TouchEvent):void
{
    var target:DisplayObject = event.target as DisplayObject;
    var touch:Touch = event.getTouch(target, TouchPhase.MOVED);

    if (target && touch)
    {
        var movement:Point = touch.getMovement(this);
        target.x += movement.x;
        target.y += movement.y;
    }
}
```

This was more complicated in the past, when there was no `getMovement()` method. But now — it seems very simple; and most of the time, you need to adapt the code somehow, anyway, so the default implementation wouldn't cut it for you.

Are there more opinions on this?

**Comment by illuzor** [comment]
I`m agree. No need for dragAndDrop now

**Comment by Eketol** [comment]
Thanks PrimaryFeather, that worked for me!

**Comment by PrimaryFeather** [comment]
Perfect, thanks for the feedback!
I'll close this issue then.
