### ISSUE TITLE
Faster TrueType font rendering

### ISSUE THREAD

**Issue by IonSwitz** [Gamua/Starling-Framework#440]
I have looked a bit into TrueType font rendering, and I think I have some performance improvements, that I would love Daniel's take on. I have run these things through Scout extensively, and each of the fixes yield measurable results.  These changes makes my test case (below) run TWICE as fast on my stationary PC, from 24,1 to 45.9 FPS measured over 60 frames (frame 200-260) in Scout. It would be interesting to know what difference it could make on a mobile device, if any.

The benefits come from caching of state and the BitmapData that Starling uses to render the TrueType text to.

I have identified and improved 3 different areas that each chewed up some time for us:

1) the test to see if we have "drawWithQuality" only needs to be done once.
2) setting embedFont = true and then = false takes a bit of CPU, so only check once per font name. 
3) reusing the BitmapData, if possible.

So, adding this to the class TextField, after the declaration of sNativeTextField:

		// some static helpers to reduce runtime checks.
		private static var sHasTestedForDrawWithQuality:Boolean = false;
		private static var sHasDrawWithQuality:Boolean = false;
		private static var sBitmapData:BitmapData = null;
		private static var sEmbedFontNames:Dictionary = new Dictionary();
        
and then:

        
        // TrueType font rendering
        
        private function createRenderedContents():void
        {
            if (mQuadBatch)
            {
                mQuadBatch.removeFromParent(true); 
                mQuadBatch = null; 
            }
            
            if (mTextBounds == null) 
                mTextBounds = new Rectangle();
            
            var scale:Number  = Starling.contentScaleFactor;
            var bitmapData:BitmapData = renderText(scale, mTextBounds);
            var format:String = "BGRA_PACKED" in Context3DTextureFormat ? 
                                "bgraPacked4444" : "bgra";
            
            mHitArea.width  = bitmapData.width  / scale;
            mHitArea.height = bitmapData.height / scale;
            
            var texture:Texture = Texture.fromBitmapData(bitmapData, false, false, scale, format);
            texture.root.onRestore = function():void
            {
                texture.root.uploadBitmapData(renderText(scale, mTextBounds));
            };
            
         //   bitmapData.dispose();
            
            if (mImage == null) 
            {
                mImage = new Image(texture);
                mImage.touchable = false;
                addChild(mImage);
            }
            else 
            { 
                mImage.texture.dispose();
                mImage.texture = texture; 
                mImage.readjustSize(); 
            }
        }

and

        private function renderText(scale:Number, resultTextBounds:Rectangle):BitmapData
        {
            var width:Number  = mHitArea.width  * scale;
            var height:Number = mHitArea.height * scale;
            var hAlign:String = mHAlign;
            var vAlign:String = mVAlign;
            
            if (isHorizontalAutoSize)
            {
                width = int.MAX_VALUE;
                hAlign = HAlign.LEFT;
            }
            if (isVerticalAutoSize)
            {
                height = int.MAX_VALUE;
                vAlign = VAlign.TOP;
            }
            
            var textFormat:TextFormat = new TextFormat(mFontName, 
                mFontSize * scale, mColor, mBold, mItalic, mUnderline, null, null, hAlign);
            textFormat.kerning = mKerning;
            
            sNativeTextField.defaultTextFormat = textFormat;
            sNativeTextField.width = width;
            sNativeTextField.height = height;
            sNativeTextField.antiAliasType = AntiAliasType.ADVANCED;
            sNativeTextField.selectable = false;            
            sNativeTextField.multiline = true;            
            sNativeTextField.wordWrap = true;            
            sNativeTextField.text = mText;
			
			if ( sEmbedFontNames[mFontName] == null )
				sNativeTextField.embedFonts = true;
			else
				sNativeTextField.embedFonts = sEmbedFontNames[mFontName];
				
            sNativeTextField.filters = mNativeFilters;
            
            // we try embedded fonts first, non-embedded fonts are just a fallback
			if (sNativeTextField.embedFonts == true && ( sNativeTextField.textWidth == 0.0 || sNativeTextField.textHeight == 0.0 ))
			{
				sNativeTextField.embedFonts = false;
				sEmbedFontNames[mFontName] = false;
			}
			
            formatText(sNativeTextField, textFormat);
            
            if (mAutoScale)
                autoScaleNativeTextField(sNativeTextField);
            
            var textWidth:Number  = sNativeTextField.textWidth;
            var textHeight:Number = sNativeTextField.textHeight;
     
            if (isHorizontalAutoSize)
                sNativeTextField.width = width = Math.ceil(textWidth + 5);
            if (isVerticalAutoSize)
                sNativeTextField.height = height = Math.ceil(textHeight + 4);
            
            // avoid invalid texture size
            if (width  < 1) width  = 1.0;
            if (height < 1) height = 1.0;
            
            var xOffset:Number = 0.0;
            if (hAlign == HAlign.LEFT)        xOffset = 2; // flash adds a 2 pixel offset
            else if (hAlign == HAlign.CENTER) xOffset = (width - textWidth) / 2.0;
            else if (hAlign == HAlign.RIGHT)  xOffset =  width - textWidth - 2;
            
            var yOffset:Number = 0.0;
            if (vAlign == VAlign.TOP)         yOffset = 2; // flash adds a 2 pixel offset
            else if (vAlign == VAlign.CENTER) yOffset = (height - textHeight) / 2.0;
            else if (vAlign == VAlign.BOTTOM) yOffset =  height - textHeight - 2;
            
            //var bitmapData:BitmapData = new BitmapData(width, height, true, 0x0);
			if ( sBitmapData != null )
			{
				if ( sBitmapData.width < width || sBitmapData.height < height ) 
				{
					sBitmapData.dispose();
					sBitmapData = null;
				}
				else
					sBitmapData.fillRect(sBitmapData.rect, 0);
			}
			if ( sBitmapData == null )
				sBitmapData = new BitmapData(width, height, true, 0x0);
				
            var drawMatrix:Matrix = new Matrix(1, 0, 0, 1, 0, int(yOffset) - 2); 
			
			// Beginning with AIR 3.3, we can force a drawing quality. Since "LOW" produces
            // wrong output oftentimes, we force "MEDIUM" if possible.
			if ( sHasTestedForDrawWithQuality == false )
			{
				sHasTestedForDrawWithQuality = true;
				
				var drawWithQualityFunc:Function = 
					"drawWithQuality" in sBitmapData ? sBitmapData["drawWithQuality"] : null;
				if ( drawWithQualityFunc )
					sHasDrawWithQuality = true;
			}
			if  ( sHasDrawWithQuality )
			{
				sBitmapData.drawWithQuality(sNativeTextField, drawMatrix, 
                                         null, null, null, false, StageQuality.MEDIUM);
			}
			else
				sBitmapData.draw(sNativeTextField, drawMatrix);
            
            sNativeTextField.text = "";
            
            // update textBounds rectangle
            resultTextBounds.setTo(xOffset   / scale, yOffset    / scale,
                                   textWidth / scale, textHeight / scale);
            
            return sBitmapData;
        }
        

Here's the test case I have been using:

private var fontVector:Vector.<TextField> = new Vector.<TextField>;
		
private function onAdded ( e:Event ):void
{
    var tf:TextField;
	for (var i:int = 0; i < 40; i++) 
	{
		tf = new TextField(300, 30, "here some text " + i, "Helvetica", 16, 0xFFFF00);
		tf.x = 10 * i;
		tf.y = 10 * i;
		addChild(tf);
		fontVector.push(tf);
	}
     addEventListener(EnterFrameEvent.ENTER_FRAME, onEnterFrame);
}

private function onEnterFrame(event:EnterFrameEvent) : void
{
	var tf:TextField;
	for (var i:int = 0; i < 40; i++) 
	{
		tf = fontVector[i];
		tf.text = "Update " + getTimer();
	}
}

**Comment by PrimaryFeather** [comment]
In Starling 2, the `embedFonts` check is now done via `Font.enumerateFonts` (the result of which is cached), so this performance issue should be gone.

However, I also removed the `nativeFilters` property. I know this will be a bummer for some users, but I think the new filters API is powerful enough to replace that. Having the native filters has some side effects concerning margins and offsets, and I wanted to not waste too much time on that (and rather spend that on the filter API instead).

I'm still not caching the bitmapData, because of the reasons stated above. 

In any case, I think after more than two years, it's time to close this issue. Thanks again for your suggestions!!
