### ISSUE TITLE
StageText with Starling

### ISSUE THREAD

**Issue by eitho** [Gamua/Starling-Framework#441]
Hello guys!
I need help. In all my mobile projects on Android 4.3 (Nexus 4) i have a problem with flash.text.StageText. When StageText is focus out application is crashing. I create test project for test this issue (https://www.dropbox.com/s/os1fzg2q692llwy/StageTextTestProject.zip). When in project comment line 60 in TextInputTestProject.as the StageText work perfect but if don't comment this line the app is crashing. In line 60 i just call method for init Starling:
```ActionScript
private function initStarling():void
{
	var viewPort:Rectangle = createViewport();

	_starling = new Starling(Main, stage, viewPort);
	_starling.addEventListener(starling.events.Event.ROOT_CREATED, function():void
	{
		_starling.start();
	});
}
```
Please can somebody tell me what i do wrong. I need help ASAP.

p.s. sorry for my bad english

**Comment by PrimaryFeather** [comment]
Since this is not a Starling issue, and there's not much I can do about it (except lobbying to get this fixed in AIR), I'll close this issue here.
