### ISSUE TITLE
ClipRect and pivot

### ISSUE THREAD

**Issue by ffelini** [Gamua/Starling-Framework#444]
If we have a sprite with some images in there and we set the clipRect for instance a half of its size everything is good. ClipRect is set properly and if we move some of his children that are out of this "viewPort" to the clipping area then it is drawn proprly also.

The problem is with pivots of the clipped sprite. 
If we animate the pivots properties of an clipped sprite then nothig out of this clipping area that moves to the clipping are is rendered.

Don't know if it is a bug of possible limitation of the clipping implementation :)

**Comment by PrimaryFeather** [comment]
Hm, sorry, it seems that issue somehow slipped my attention. Sorry for that!
The good news is that it shouldn't be a problem in Starling 2, since clipRects are no longer available. :wink: Well, in fact they are now just an optimization of the `mask` property.
