### ISSUE TITLE
Flattened Sprite with TextField loses texture when text changes.

### ISSUE THREAD

**Issue by okuligowski** [Gamua/Starling-Framework#452]
I have Sprite with TextField added to it. This Sprite contains more than one object, so I use flatten(). When text on that TextField changes, and I dont use flatten() again, Starling throws "Error #3663: Sampler 0 binds an undefined texture". Expected result is that changes on that text are not visible until flatten(), or Starling should throw more understandable error.

**Comment by PrimaryFeather** [comment]
Since there's no more `flatten` in Starling 2, well, this is kinda solved. :wink:
