### ISSUE TITLE
Implied syncing between RenderSupport.blendMode and calls to render QuadBatch(and maybe Quad)

### ISSUE THREAD

**Issue by jamikado** [Gamua/Starling-Framework#458]
So I am raising this as a potential 'gotcha' in code. Maybe you don't want to change how this works, and maybe this implied syncing with the active RenderSupport.blendMode does need to be enforced by developer code externally, but I technically think the way blendMode is passed around when calls to render (and optionally batch) QuadBatch and Quad are unnecessarily tied to the active state of RenderSupport.blendmode when it doesn't have to be.

I came across this peculiarity while trying to use QuadBatches as containers for content in a Sprite but not having them be directly in the DisplayList but just use them in rendering.

A technique you mention a few times in the forums like at:
http://forum.starling-framework.org/topic/rendering-issues-w-custom-displayobject
where I was testing a rewrite of the Spine SkeletonSprite to use this QuadBatch technique to separate the creation of cached skeleton QuadBatches only during an update and outside the normal render() calls.

The rub comes along when you might try and build up an array of QuadBatches that you use for rendering (like the internal use of an array of QuadBatches in RenderSupport), as you might have a parent sprite container that needs to hold not just one QuadBatch but an array (checking if state changes required in a more complicated rendering use requires multiple QuadBatches).

The issue is that there are a few places in Starling code where using a QuadBatch which might store its own custom blendMode value is getting ignored by RenderSupport unless you separately also update support.blendMode before calling QuadBatch.render.

For example: in QuadBatch.render() line 454, there is:

```as3
renderCustom(support.mvpMatrix, alpha * parentAlpha, support.blendMode);
```

so when a QuadBatch is not batchable it is getting its renderCustom() called with the current value of support.blendMode instead of even passing its own potential current custom blendMode.

Now I understand that the default RenderSupport render loop sets the current blendMode off a DisplayObject.blendMode call before rendering it, but given the code above where an explicit QuadBatch is asked to render, doesn't it make more sense to support its direct blendMode value such as using instead:

```as3
renderCustom(support.mvpMatrix, alpha * parentAlpha, 
    this.blendMode && this.blendMode != BlendMode.AUTO ? this.blendMode : support.blendMode);
```

Additionally, in RenderSupport on both batchQuadBatch() and batchQuad() there is first a check of isStateChange() where one of the comparisons is comparing the QuadBatch(Quad) blendMode against the current support.blendMode to make sure whether there is a state change or not, but then when the actual QuadBatch or Quad gets added, only mBlendMode (RenderSupport) and not the actual blendMode value that is stored in the QuadBatch or Quad is used.

It seems to me the current system essentially forces the proper setting of the active support.blendMode before trying to use QuadBatch or Quads directly during rendering calls, but I think this extra external setting could be avoided if the code just made an attempt of using the blendMode from the QuadBatch or Quad instead of always whatever the current RenderSupport blendMode value is.

So going back to my example where I am using an array of QuadBatches (not in the display list), I can make things work by doing:

```as3
var numUsedBatches:int  = mCurrentQuadBatchID + 1;
var thisQuadBatch:QuadBatch;
for (var i:int=0; i<numUsedBatches; ++i) {
    thisQuadBatch = mQuadBatches[i];
    support.blendMode = thisQuadBatch.blendMode;
    thisQuadBatch.render(support, alpha);
}
```
but I would think the extra call to make sure I set the active support.blendMode is just a workaround because calling QuadBatch.render() isn't doing this for me automatically?

Maybe this isn't a big issue for most custom rendering code now, but I wonder if it could be something that trips people up in the future.

Thanks

**Comment by PrimaryFeather** [comment]
I cleaned up all of this in Starling 2, so I think we can close this issue. :smile:

**Comment by jamikado** [comment]
Awesome!
