### ISSUE TITLE
visibleAreaChildrenList - Performance boost suggestion

### ISSUE THREAD

**Issue by ghost** [Gamua/Starling-Framework#478]
Hi,

Inside DisplayObjectContainer render loop you iterate over all the children and check if they got visible area(hasVisibleArea), and only render them if you get a positive answer.

You can get performance boost if you will manage visibleAreaChildrenList. This way you will reduce your rander cycle. 

I did something like this once. It's not a big boost but it's helping.

Note that to implement this you need a mapping between child and his index in the parent(I just stored this data in the child itself), so when the child become visible you need to place him in proper position in the visible list queue according to his actual index in the parent.

Right now I am developing a tool that use GridList and I need to add layers to it. In my specific case I will have hundreds of invisible children.

I think that every app has good potential for 10%-20% of invisible displayObjects.

**Comment by PrimaryFeather** [comment]
In Starling 2, that's a little faster than before, because Starling stores an internal `private var _hasVisibleArea:Boolean` rectangle instead. That makes all such calculations faster.
