### ISSUE TITLE
30 FPS stuttering while 60 FPS runs fine.

### ISSUE THREAD

**Issue by IonSwitz** [Gamua/Starling-Framework#484]
Following up this discussion thread from the Starling Forum with an Issue here at GitHub.

I am not sure this is something that Daniel can fix in Starling, but something seems very very odd here.

http://forum.starling-framework.org/topic/30-fps-vs-60-fps-why-30-looks-jagged

Basically: For some of us, this happens: 

Set up a trivial Starling project, a Main file and something else.
Set SWF to 60 fps - observe smooth animations.
Set SWF to 30 fps - observe stuttering.

To investigate, I added a trace to see what the passedTime argument to advanceTime was, and at 30 FPS, I saw these fluctuations:

advanceTime: 0.04600000000000026
advanceTime: 0.019999999999999574
advanceTime: 0.03300000000000036
advanceTime: 0.02999999999999936
advanceTime: 0.034000000000000696
advanceTime: 0.03399999999999981
advanceTime: 0.03200000000000003
advanceTime: 0.03399999999999981

(Just a random sample of the frames, observe the difference, 0.046 vs 0.0199 )

So, I hooked up Scout, and I got this (observe the stuttering greyed out columns)

https://dl.dropboxusercontent.com/u/107200878/more30fpsStutter.jpg

BUT!

When I hacked further into the Starling class, and added another mContext.present() directly after the already existing one, the stuttering disappeared almost completely, animations run smooth again, and the variations in the printout became almost zero, as with 60 FPS.

https://dl.dropboxusercontent.com/u/107200878/30fpsWithDoubleRenderCalls.jpg

I wanted this to get Daniel's attention, even though it might not be something he can do about this, but this seems to be a Flash Player issue, not a Starling issue.

It should also be mentioned, that I have developed a Starling game (on the first release of 1.4.1 ) in a mixed environment, with Display List and Stage3D mixed, at 30 FPS without seeing this issue.

So this is spooky, in my view.

EDIT: Of course, a reproduction is always nice. This one is 26 lines long, a complete sample to reproduce the problem:

``` as3
package
{
    import flash.display.Sprite;
    import flash.display.StageAlign;
    import flash.display.StageScaleMode;
    import starling.core.Starling;
    [SWF( width="1200", height="800", backgroundColor="#000000", frameRate="30" )]
    public class Main extends flash.display.Sprite
    {
        private var starling    :Starling;
        public function Main()
        {
            stage.scaleMode = StageScaleMode.NO_SCALE;
            stage.align = StageAlign.TOP_LEFT;
            starling = new Starling( NullSprite, stage, null, null, "auto", "baselineConstrained" );
            starling.start();
        }
    }
}
import starling.display.Sprite;
class NullSprite extends starling.display.Sprite
{
    function NullSprite()
    {
    }
}
```

Build this, start up Scout, observe how irregular the patterns are. :( 

Naturally, there might be something special with my machine, and that of the others in the other thread, that cause this to happen. It might not be reproducible on other machines.

**Comment by caseyryan** [comment]
Unfortunately, the problem is still there and nothing seems to be able to fix it. I'm pretty sure it's an AIR bug. I tried with your update, Daniel, and it only partially decreased the number of grey peaks :( I'm testing on windows 7, on Android 5.0.2, and Android 4.4.2. They all give the same result.
P.s. right now I'm running AIR 21 Beta

**Comment by R24BRX** [comment]
Where would I place this code (in my main class or in the starling library)?

**Comment by PrimaryFeather** [comment]
The code above would replace the `onEnterFrame` method in `Starling.as`, so this requires modifying the Starling code. 

It should work almost the same in Starling 1.8 and 2.0. Let me know if you need any help getting it work with Starling 2.0.
