### ISSUE TITLE
Allow Image to have null texture

### ISSUE THREAD

**Issue by troygilbert** [Gamua/Starling-Framework#486]
I would love to be able to construct an instance of an Image class without having to provide a texture. The class currently throws an exception if the texture is null, but I can't see any reason to have this constraint in the underlying implementation of Image. It fact, it seems to degrade gracefully into a quad (as you'd expect). It also doesn't mirror the functionality/style of the Flash display list, where a Bitmap can definitely be put on the display list without having BitmapData associated with it.

**Comment by PrimaryFeather** [comment]
It took a while, but in Starling 2 this is finally possible. In fact, the setup is a little changed: all that you could do in Starling 1.x's `Image` class can now be done with `Quad`. That means that a Quad can have a texture, or not. `Image` is still there, but just to provide some additional methods that only make sense when you've got a texture.
