### ISSUE TITLE
TextField breaks words in half, instead of scaling them down

### ISSUE THREAD

**Issue by martin3361** [Gamua/Starling-Framework#506]
As also commented in the following forum thread: http://forum.starling-framework.org/topic/textfield-breaks-words-how-to-prevent-that

Way to reproduce:
1) create a starling.text.TextField with height of two lines, but width not enough to support single long word
2) set autoScale=true of the text field.

Observed behaviour: Word is broken in half
Expected behaviour: Word is scaled down to fit in width, instead of being broken in half.

![starlingwordbreak](https://f.cloud.github.com/assets/6729011/2431110/68eb9b12-ad1b-11e3-9615-2f98fc9dd514.png)

**Comment by neuronix** [comment]
![starling_textfield_break](https://cloud.githubusercontent.com/assets/219800/8410582/67a53822-1e7f-11e5-88bd-31f1f8a1ad73.jpg)

Hi Daniel, i'm using the latest starling 1.6 release and the issue is still present. I'm using a textfield with embedded TTF font. Issue is present with and without autoscale = true.

**Comment by PrimaryFeather** [comment]
Hm ... the original issue was about bitmap fonts, not true type. When using TTF, I'm using the standard Flash TextField. When "autoscale == true", I can only check if the text fits within the box, but I can't change how the wrapping occurs.

I just had another look at the Flash TextField API, and I find only "wordWrap". That property (which Starling enables) will add breaks if a word goes beyond the bounds of a line. However, if a single word does not fit into the line, it will split up even single words. However, there's no way for me to know that! I can only check the size of the output (see [this method](https://github.com/Gamua/Starling-Framework/blob/master/starling/src/starling/text/TextField.as#L354)). :pensive:

So I don't think I can do anything against that. Sorry!

**Comment by neuronix** [comment]
Ok, thanks for checking up on that! :)
