### ISSUE TITLE
Resize event width and height don't match stage.stageWidth and stage.height

### ISSUE THREAD

**Issue by mrpenguin** [Gamua/Starling-Framework#51]
With the following function:
private function event_stage_resize(event:ResizeEvent):void {
    trace(event.width + " " + this.stage.width + " " + this.stage.stageWidth);
}

I get completely different values for each.  The event.width actually matches the stage width and height.  I have no idea where the values come from for stage.width (it increases but doesn't actually match the size of the stage).  The stage.stageWidth value never changes from its original value.  This is an unexpected behavior.  In Flash, the stage.stageWidth will always reflect the actual size of the stage.

**Comment by algotechnologies** [comment]
@PrimaryFeather I love you man. You saved my life :D Very nice tutorial (Y)

**Comment by PrimaryFeather** [comment]
Haha, thanks for the compliments! I'm glad to hear it helped you, as well! :smile:

**Comment by algotechnologies** [comment]
Yes because it's different from native Flash api. But now I understand after your tutorial :) thanks
