### ISSUE TITLE
drawToBitmapData using a scale

### ISSUE THREAD

**Issue by divillysausages** [Gamua/Starling-Framework#525]
As mentioned in issue #517, when drawing the stage with a scale other than ```1.0```, the position of objects are offset on mobile (testing using an iPad mini & Galaxy S3).

Basically as ```scale``` approached ```0.5```, objects would be offset by the screen height; lower than ```0.5``` and they'd be off the screen.

2 things would fix it:

**1) Applying an offset when calling ```setOrthographicProjection()```**
This needs to be separated between desktop (only tested on windows though) and mobile (maybe using ```SystemUtil```?).

When setting up the ```RenderSupport```:
```
var scale:Number	= 0.5;
var w:Number		= Starling.current.stage.stageWidth;
var h:Number		= Starling.current.stage.stageHeight;
var bmd:BitmapData	= new BitmapData( w * scale, h * scale, false, 0x00000000 );

// create our render support
var rs:RenderSupport = new RenderSupport;
if( SystemUtil.isDesktop )
	rs.setOrthographicProjection( 0.0, 0.0, w * 1.0 / scale, h * 1.0 / scale);
else
	rs.setOrthographicProjection( 0.0, ( h - ( h * 1.0 / scale ) ), w * 1.0 / scale, h * 1.0 / scale);
```

The ```w * 1.0 / scale``` and ```h * 1.0 / scale``` is there to fix the ```clipRect``` problem mentioned in #517

The ```y``` offset for the orthographic projection is needed, as if the ```RenderSupport.renderTarget``` is ```null```, it'll render in the back buffer. Why it's necessary to correct the offset only for mobile, and only for the ```y``` axis is beyond me :smile: 

**2) Use a ```renderTarget``` for the ```RenderSupport```**:
If the ```renderTarget``` is ```null```, then it's rendered into the back buffer, so you can specify an empty target instead:

```
var scale:Number	= 0.5;
var w:Number		= Starling.current.stage.stageWidth;
var h:Number		= Starling.current.stage.stageHeight;
var bmd:BitmapData	= new BitmapData( w * scale, h * scale, false, 0x00000000 );

// create our render support
var rs:RenderSupport 	= new RenderSupport;
rs.renderTarget         = new RenderTexture( w * scale, h * scale, false, 0 );
rs.setOrthographicProjection( 0.0, 0.0, w, h );
```

If we use a ```RenderTexture```, then we don't have to set the ```width``` and ```height``` fix for the ```clipRects``` in the ```setOrthographicProjection``` call, though I'm not sure it's possible to get the resulting texture as a ```BitmapData```? Only the ```Context3D``` class seems to have a ```drawToBitmapData()``` method.

---

In an somewhat related note, I found that calling ```Starling.current.context.present()``` at the end of all this to actually *cause* a flicker rather than prevent one, when using the first fix, as, because you're rendering to the back buffer, it'll show one frame (the one you just rendered) with the scale messed up. 

You can either omit the call, or *re-render* the stage at scale ```1.0```. Something like this:

```
...
Starling.current.context.drawToBitmapData( bmd );

// re-render at 100% scale to avoid a screen flicker
rs.setOrthographicProjection( 0, 0.0, w, h );
rs.clear( this.stage.color );
stage.render( rs, 1.0 );
rs.finishQuadBatch();

Starling.current.context.present(); // required on some platforms to avoid flickering
```

This obviously has a downside of rendering twice just to get a screenshot.

**Comment by PrimaryFeather** [comment]
Since this sounds more like a stage3D issue, and since there hasn't been any progress for a while, I'm now closing this issue. Feel free to open it up again if you want to continue this discussion.
