### ISSUE TITLE
Proper IDs for mouse-based TouchEvents?

### ISSUE THREAD

**Issue by tconkling** [Gamua/Starling-Framework#530]
Is it possible to give proper, non-repeating IDs to TouchEvents that come from the mouse, rather than assigning ID 0 to all mouse touch events?

I frequently run into variations on the following scenario:
- input-listener-1 processes a mouseDown
- input-listener-2 processes the same mouseDown
- input-listener-1 processes the following mouseUp, and uses my input manager to "consume" the touch event, so that no other listeners receive it
- input-listener-2 receives a future, unrelated mouseUp and incorrectly assumes it's the same TouchEvent it was dealing with before because the ID is always 0

Obviously this situation could be solved by ensuring that all input-listeners are informed whenever an event is consumed by another listener - but this is (possibly) expensive, and is not necessary when dealing with "real" TouchEvents on a touchscreen device, where each new touch gets its own ID.

I'd love to not have to do extra book-keeping in the desktop version of my game.

I'd happily put together a pull request for this change if you don't have objections, Daniel.

**Comment by PrimaryFeather** [comment]
Since this discussion kind of broke off, you probably found another way to do this, Tim?
I'm closing this (and related issue #531), then.

**Comment by tconkling** [comment]
It's something I may revisit in the future, but my particular use case for this turned out not to be important!
