### ISSUE TITLE
Using composition instead of inheritance for MovieClip

### ISSUE THREAD

**Issue by Fraggle** [Gamua/Starling-Framework#542]
Hi,

I would suggest to use composition for MovieClip instead of directly extending Image so we can re-use the logic for advancing, looping, events.. while using another rendering method than just switching texture (for example, my use case, in the GAF library or Spline etc..).

A way could be to create an IAnimatable AnimationManager who knows about the number of frames, current frame etc.. and use one of theses in the MovieClip.
That way, we could create another Animated display object easily without rewriting a bunch of code.

**Comment by Fraggle** [comment]
Closing the issue :)

**Comment by PrimaryFeather** [comment]
Actually, I implemented your suggestion a while ago! :wink:
See this class inside the Adobe Animate extension: [MovieBehavior](link
https://github.com/Gamua/Starling-Extension-Adobe-Animate/blob/master/src/starling/extensions/animate/MovieBehavior.as) 

I'm planning to make this class be used by the standard MovieClip, too, and add it to vanilla Starling.

**Comment by PrimaryFeather** [comment]
Haha, yeah, it took a few years, but I hadn't forgotten about it! :bowtie:

Yes, the extension works rather well, actually! I hope Adobe adds a few more export options in the future, then this will be a great feature, even for other game engines.
