### ISSUE TITLE
AssetManager: Loading atlas XML without texture data

### ISSUE THREAD

**Issue by Varnius** [Gamua/Starling-Framework#556]
Would be handy if AssetManager could load atlas XML data even without enqueued texture data. So rather than discarding the atlas, it would put its data into your regular XML dictionary for later use. All this would be useful for preloading atlas XML data and then streaming ATF textures in real time without loading the XML each time you stream a texture.

**Comment by rgsone** [comment]
I have the same problem. I want load font atlas xml without texture data.
I set `keepFontXmls = true` and `keepAtlasXmls = true` but the Xml is still discard.

Here the code in AssetManager :
```
if (rootNode == "TextureAtlas")
{
    name = getName(xml.@imagePath.toString());
    texture = getTexture(name);
    if (texture)
    {
        addTextureAtlas(name, new TextureAtlas(texture, xml));
        removeTexture(name, false);

        if (_keepAtlasXmls) addXml(name, xml);
        else System.disposeXML(xml);
    }
    else log("Cannot create atlas: texture '" + name + "' is missing.");
}
```
Thanks

**Comment by PrimaryFeather** [comment]
So you say you enqueued the XML file (not the texture), and you can't access the XML file afterwards?

As the code you posted above shows, when there is no suitable texture, the XML should be simply kept inside the _AssetManager_ (the code won't enter the `if (texture)` part). What does the trace output say — is there anything suspicious?

**Comment by rgsone** [comment]
I think the XML is detected as a font XML atlas descriptor and the texture associated is not find, so the XML is skipped.
I test with one basique XML and a font atlas descriptor XM. When all are loaded, i look in XmlNames. The basique WML exists but the XML font atlas descriptor is missing.

**Comment by PrimaryFeather** [comment]
You are perfectly right! That `if (keep)` logic needs to move outside of the `if (texture)` clause. Thanks a lot for making me aware of that!

I just fixed that.

**Comment by rgsone** [comment]
Great, thank you !
