### ISSUE TITLE
QuadBatches out of display list cause errors after starling.dispose()

### ISSUE THREAD

**Issue by neuronix** [Gamua/Starling-Framework#571]
Quadbatches have this listener for restoring context. 
Starling.current.stage3D.addEventListener(Event.CONTEXT3D_CREATE, onContextCreated, false, 0, true);

It is removed in the dispose() method. However, if the quadbatch is not in the displaylist, calling starling.dispose() will not include the quadbatch and it will throw a missing context error when you create a new instance of starling (on the same stage3D).

This is a real issue for pooling displayobjects. One can of course just make them visible = false instead of removing them from the display list but that doesn't feel right.

This could be solved with a dispose event on Starling.current instead of parsing the display list.

**Comment by PrimaryFeather** [comment]
Since Starling 2, no display objects listen to `CONTEXT3D_CREATE` any longer (only helper classes like _Painter_, _Effect_, etc. — so this should no longer be an issue.
