### ISSUE TITLE
Allow GPU memory consumption calculation

### ISSUE THREAD

**Issue by henke37** [Gamua/Starling-Framework#584]
Add a new interface to get the GPU memory consumption for objects.

```actionscript
interface IGPUSizedObject {
function getGPUMemmoryConsumption():uint;
}
```

The main use for this is obviously getting the size of ConcreteTextures, but there are other objects that could be tracked.

**Comment by PrimaryFeather** [comment]
That's now part of the AIR SDK! 
https://helpx.adobe.com/flash-player/release-note/fp_21_air_21_release_notes.html#newfeatures

**Comment by henke37** [comment]
Not good enough I'm afraid. While certainly useful for quick checks and over time charts, it's no good for gathering details about individual resources. Can't tell which resource is the expensive one and fun people (not including me, yet) who want to attempt to automatic resource management can't use it.

**Comment by PrimaryFeather** [comment]
I know that Adobe plans to give you more information about those resources in future update, e.g. the memory consumption of individual textures. So we'll probably have a good solution for this soon. :smile:
