### ISSUE TITLE
Adding some HTML support to TextField?

### ISSUE THREAD

**Issue by alamboley** [Gamua/Starling-Framework#596]
Starling is lacking some features concerning the TextField: having several colors, bold, italic and size supports.

I discovered this class https://github.com/binouze/HTMLBitmapFonts and it isn't bad at all, but it's lacking latest Starling's updates.
It would be great to merge it into the Starling's TextField code.

**Comment by PrimaryFeather** [comment]
This was actually implemented with Starling 1.7, so I'm closing this issue now.
