### ISSUE TITLE
Use stencil buffers to perform masking.

### ISSUE THREAD

**Issue by henke37** [Gamua/Starling-Framework#610]
Stencil buffers are made for the purpose of masking, so why not do that?

This does depend on the ability to control buffer updating based on a texture value, which is not obviously supported in the Stage3D API.

**Comment by henke37** [comment]
Is this ready to be closed as done?

**Comment by PrimaryFeather** [comment]
Ah, you're right! While there are still some more small things I want to add, basic stencil masking is finished. I'll close it! :smile:
