### ISSUE TITLE
Allow QuadBatch to be replaced with a custom implementation

### ISSUE THREAD

**Issue by Varnius** [Gamua/Starling-Framework#619]
I'm currently struggling with making my [Starling deferred renderer](https://github.com/Varnius/StarlingRendererPlus) a standalone extension without the need for Starling fork to lurk around there somewhere containing the bits of modified code that I can't really override in the extension itself. Since I wanted the extension to work with regular Starling objects like Quad and Image without breaking batching, my only option was to modify QuadBatch and fork Starling to do so because currently there is no way to override the default QuadBatch. 

So what about adding a possibility for a developer to configure an instance of Starling to use a custom QuadBatch class which could simply be required to be a subclass with overridden functionality (because introducing an IQuadBatch interface would require much more work, I suppose)? Internally, this would require to replace all instances of:
```actionscript
new QuadBatch()
```
with a factory call like
```actionscript
QuadBatchFactory.getInstance()
```
which would return an instance of custom QuadBatch class if it's specified or default QuadRenderer otherwise.

I personally don't see any serious performance (or other) implications but I may be missing something, for example, compatibility with other extensions, like Feathers, where QuadBatch objects would be initialized using "new".

**Comment by tsangwailam** [comment]
http://forum.starling-framework.org/topic/spriteilluminator-2d-dynamic-lighting
It is good if this feature can be implement in Starling soon.

**Comment by PrimaryFeather** [comment]
I added some more information on my plans in that [forum post](http://forum.starling-framework.org/topic/spriteilluminator-2d-dynamic-lighting?replies=9#post-75930); in a nutshell: stencil masks are already done, so the rendering architecture overhaul is not far away.

**Comment by 22ROUND** [comment]
waiting

**Comment by ivanavdieienko** [comment]
I'm waiting so much
for custom QuadBatch!

**Comment by PrimaryFeather** [comment]
I'm hearing you, guys! I will do my best to speed things up, promised!

**Comment by b005t3r** [comment]
What I'd really like to see is Quads and QuadBatches being transformed into a group of three classes: VertexFormat, Geometry and Renderers, like I did here:

https://github.com/b005t3r/Starling-Extension-BatchRenderer

It makes adding new shaders (like the ones mentioned above) really easy, custom display object based on more complex geometry than quads are also easy to use and batching of all of this (custom and build-in display objects) is done almost automatically.

**Comment by PrimaryFeather** [comment]
Since the (deferred renderer)[http://forum.starling-framework.org/topic/rendererplus-for-starling-2] now works with an unmodified Starling 2, I'd say: mission accomplished! :beers:
