### ISSUE TITLE
Feature Request: Hook for showFatalError

### ISSUE THREAD

**Issue by vpmedia** [Gamua/Starling-Framework#631]
Hi,

I'm not making a PR since I want to discuss the feature before.

In short I would like to have some kind of notification for Starling fatal errors which are displayed using the following method

```
private function showFatalError(message:String):void
```
## Why:
- track fatal errors with analytics
- apply some styling for these errors messages (create own display object)
- trigger self recovery commands (like browser window/app self-restart)
## How:
- Option A:

> Use a custom StarlingFatalEvent with a Message payload
- Option B:

Add a custom function hook like:

> setFatalErrorHandler(method:Function) 

Thanks!

**Comment by henke37** [comment]
Do you think that you could make it optional to obey the default handling here? At the very least, there needs to be a way to show custom ui instead of the default one.

**Comment by vpmedia** [comment]
I think if you listen to FATAL_ERROR event, you can remove the children of nativeOverlay and show a custom UI.

**Comment by PrimaryFeather** [comment]
The easiest way to do this is to create a subclass of Starling that overrides the "stopWithFatalError" method. Simply call "stop(true)" and add your own UI to the classic display list.
