### ISSUE TITLE
Starling Graphics integration (Feature Request)

### ISSUE THREAD

**Issue by vpmedia** [Gamua/Starling-Framework#635]
Hi!

I would like to have Your and the Community opinion about integrating Graphics drawing into Starling framework. While StarlingGraphics extension exists, I would like to have a well tested, bug free and highly optimized version which updated regurarly and tuned to perform as best with the core Starling enhancements..
I feel this functionality more tied into a graphics/render engine compared to Asset Manager for example.

Thanks!

**Comment by vpmedia** [comment]
Hi!

I see there are updates (bd7a0249c8f9d7fe50473dd8a76aa8640efe2ebe) regarding the 
feature request, very nice, thank you!

Some feedback:

-as posted on the forum also the new starling.display.Shape class breaks compatibility with the graphics extenson, I've moved the extension outside the core starling package to solve this, I think thats the proper way..

-the new mask property breaks compatibility with the PixelMask extension, I've renamed the extensions property to masker..

-I'm still missing a line drawing feature to drop the graphics extension in my game framework and I've issues making a simple quad based solution:
https://dl.dropboxusercontent.com/u/1375050/starling-quad-lineto.png
Do you think it is something that will be implemented in the near future?
Also I would like to ask for some advice about GPU based solutions for this, as you can see in the screenshot there are gap issues with the connecting lines, also the line aliasing looks bad if rotated with small angles..

**Comment by PrimaryFeather** [comment]
Yeah, I'm sorry for that package/name clashes. As an alternative, I could rename the "Shape" class for now, until Starling 2.0, which will break a lot of code, anyway. ;-)

A line drawing feature is planned to be added to the Shape class, yes! I suppose this will require some tricky math, though, to avoid exactly the issues you are seeing. 

What you could do in your case is to use an image of a line in the correct width (not length), complete with 1-2 pixels transparent border. You'll see that when you rotate that, aliasing will be much better. Corners will still be a little difficult, though.

**Comment by IonSwitz** [comment]
The elbow joint math (the reason why the "corners" look bad) is solved in the Stroke class of the Starling Extension Graphics. The code lies in the buildGeometryPreAllocatedVectors() and createPolyLinePreAlloc() methods, which contain some of the most Scout:ed code paths that I have ever worked on :)

Making the elbows look good is pretty slow, unfortunately.

The problem with jaggies along the lines could be solved by drawing twice the number of triangles for each pass, with the outer vertices having a 0 alpha and the middle vertices have an alpha of 1, but that would require a double pass through the elbow math, and that is really expensive.

Solving anti-aliasing issues using only triangles is not simple, so a textured path is most likely the best way to go.

![jaggiescure](https://cloud.githubusercontent.com/assets/3709822/6358164/f5f59d38-bc69-11e4-9309-e275508f2da1.jpg)

**Comment by PrimaryFeather** [comment]
Thanks a lot for the overview about the "elbow joint math" (now I at least know how this is called! :grin:)! This is a part where I'll definitely let myself be heavily inspired by the graphics extension's code. You really did an amazing job on that! That becomes ever more clear the more I look at it ...! :smile:

**Comment by IonSwitz** [comment]
I didn't do any of the real math on that, I only optimized the code path as much as I could without changing the logic around too much. I am sure things could be optimized further, to make special cases faster, but the math in itself is not of my doing. :)

**Comment by PrimaryFeather** [comment]
Hehe, okay! Even that is impressive. =)
I'm sure I'll find good documentation about the issue somewhere — definitely a good time to dust off some of my long forgotten math "skills". ;-)
