### ISSUE TITLE
Improve performance using Inline metadata

### ISSUE THREAD

**Issue by vpmedia** [Gamua/Starling-Framework#636]
Hi,

There were some discussion about using the [ Inline ] metadata for additional performance improvements and I'm opening a feature request here for this.

I've reviewed the Adobe compiler documentation and it states that the [ Inline ] metadata have only effect if the Developer compiles the SWF directly from source code and not using as SWC library.
Tip: The method inlined must be either Final, Static or Global.

My question is that is there any blocking issue which stops you from using this feature anyway?
So users who are using the source code compilation could at least benefit from this..

I've checked and I can compile Starling source into SWC if I change this method as an example (Which would be a good candidate anyway):

        [Inline]
        public final function makeCurrent():void
        {
            sCurrent = this;
        }

I think this and some other methods would deserve inlining since they are called as an ENTER_FRAME basis.

Thanks!

**Comment by PrimaryFeather** [comment]
Since there still hasn't been any progress on Adobe's side regarding the inline feature, I'll close this issue for now. Should this ever work reliably, I will open it up again.
