### ISSUE TITLE
BlendMode.ADD causes black artifacts in Chrome

### ISSUE THREAD

**Issue by neuronix** [Gamua/Starling-Framework#639]
No artifact when testing in FlashDevelop, semi opaque black rectangles around the images with BlendMode.ADD in Chrome. The issue does not occur with BlendMode.SCREEN (which i'm using as a fallback).

**Comment by WuLinzhi** [comment]
I have the same problem with ATF,like this.If I use a png instead there is no problem.
![image](https://cloud.githubusercontent.com/assets/5546471/7610951/63ae6392-f9b3-11e4-9007-10d1b297fb89.png)

**Comment by neuronix** [comment]
PNG is pretty bad on mobile, so I used SCREEN instead of ADD, which is OK although it's less pretty.

**Comment by kheftel** [comment]
is it possible this is a PMA issue between ATF and PNG?

**Comment by PrimaryFeather** [comment]
It's very probably an PMA issue, agreed.
@WuLinzhi, the original issue was that the blending looked different only in Chrome. Is that the case with your problem, too? 
@neuronix, you never answered my questions on the issue! :wink:

**Comment by PrimaryFeather** [comment]
I didn't get any more feedback, but this is probable solved with Starling 2, which automatically converts all textures to PMA and treats them uniformly.
