### ISSUE TITLE
starling ios, press power button issue

### ISSUE THREAD

**Issue by sin-bufan** [Gamua/Starling-Framework#644]
i made a ios app using starling, when user press power button, trigger the following code to snap the starling stage:

```as3
var result:BitmapData = new BitmapData(rect.width * scaleFactor, rect.height * scaleFactor, true, 0x00000000);
Starling.context.clear()
Starling.context.drawToBitmapData(result);
```

but i get the entire stage snapshot in result.
why is that, and how could i avoid it?

**Comment by PrimaryFeather** [comment]
Lacking further replies, and since the bug looks like a Flash/AIR problem to me, I'll close this issue for now. Feel free to open it up again if you want me to look into it again!
