### ISSUE TITLE
ColorMatrixFilter slows the FPS down on certain Android devices

### ISSUE THREAD

**Issue by alexfilos** [Gamua/Starling-Framework#650]
Hello there,

First of all thanks for Starling - it's a huge contribution to games development community and amazing work!

The issue is that when I assign a ColorMatrixFilter to a Citrus State using the following code:

    var invertFilter:ColorMatrixFilter = new ColorMatrixFilter();
    this.filter = invertFilter;
    invertFilter.invert();

I get something like 30-40 FPS instead of 60 FPS I would normally get! This happens when testing on some Android devices like HTC One. I've also tested on iPad Mini and Mac Book Pro and there works alright with 60 FPS. Do you think this will be fixed on Starling 1.6 as a result of the optimisations you've made?

Thanks in advance :)

**Comment by PrimaryFeather** [comment]
Lacking any more feedback on this issue, I'll close it for now. Feel free to reopen it again.
