### ISSUE TITLE
 Performance Issue of onKey

### ISSUE THREAD

**Issue by plantabutterfly** [Gamua/Starling-Framework#658]
I am doing some performance test for my game on Scout, and find that when holding a key (say pressing 's' for 5 seconds), Starling.onKey becomes the most expensive procedure.

The reason behind is the game is a Platformer and have quite a large display hierarchy, and Starling.onKey is forced to loop everything single container inside Starling, even those container that is outside player's screen (sprite.visible = false).

Doing some research on internet, I figured out some people also have the similar problem.

http://forum.starling-framework.org/topic/keyboard-lag
http://forum.starling-framework.org/topic/keyboard-issue

I think the solution is keep a static protected const _onKeyList.Vector.\<DisplayObject\> in DisplayObject class.

When an displayobject calling addEventListener(keyEvent), the displayobject would add the object to the list (or remove if it is removeEventListener).

Now, Starling.onKey can now just loop through the list, instead of looping through the entire hierarchy.

**Comment by PrimaryFeather** [comment]
For reference: I just had another look at it, and I decided to postpone the change for Starling 2.0. There's no clean way to make it fast while still broadcasting the event; and if I change it back to the previous behavior (dispatching only on the stage), I fear that I might break a lot of code. On the other hand, I didn't receive a whole lot of complaints about the issue.

Thus, I have to ask you to keep that manually inserted "broadcast" vs. "dispatch" change mentioned above, at least until Starling 2.0 is out, which will break a lot of stuff anyway. I hope you understand!

**Comment by plantabutterfly** [comment]
@PrimaryFeather Thanks for notifying! Of course, I understand, I would feel kinda guilty if Starling is broken after fixing this issue. In fact, this issue is not that important that must fix immediately, I already suppose this is just an issue for future improvement. :)

**Comment by PrimaryFeather** [comment]
Thanks for your understanding! :smile:

**Comment by b005t3r** [comment]
Was this fix for some other reason reverted? I can see KeyboardEvents are still broadcasted instead of simply being dispatched and it hurts performance a lot when holding down a button (which is what I need to implement).

**Comment by b005t3r** [comment]
Ah, I see you changed it for the 2.0 only. It would be great if you could do the same for the older version (current master) or at least make it conditional (switched using a new property). As it is now, it makes a task as simple as scrolling the map using keyboard impossible because the performance drops massively. Plus, according to the official docs, dispatching the event instead of broadcasting it is how it is supposed to work (see Starling.as docs).

**Comment by PrimaryFeather** [comment]
I just added a property to the 1.x branch, allowing to deactivate the broadcasting. I hope that helps!

**Comment by b005t3r** [comment]
Thanks, Daniel!
