### ISSUE TITLE
Change the default value of Starling.handleLostContext to true

### ISSUE THREAD

**Issue by joshtynjala** [Gamua/Starling-Framework#663]
It seems to me that handling lost context automatically is a better default today. It's much more common to enable this behavior than to keep it disabled, so let's save everyone a little bit of time and switch to a more reasonable default. As we've discovered, lost contexts are more common than originally expected on iOS, so usually, handleLostContext should be enabled there too. I assume that the main reason it was false before was because it required a lot of resources to keep BitmapData in memory. However, with the ability to restore textures with onRestore, there doesn't need to be any memory impact. AssetManager and Texture.fromEmbeddedAsset() set up onRestore automatically.

It might make sense to wait until a major version update. However, I feel like this change would be pretty safe if it happened sooner. The vast majority of developers are probably explicitly setting handleLostContext to true in their apps already, or they might still be making an exception for iOS. Regardless, the behavior will not change in these existing apps because the handleLostContext property is being set explicitly, overriding the default behavior. I suspect that the minority who wants handleLostContext to be false shouldn't require too much extra effort to support. If they're handling lost context manually, they'll probably be advanced enough to figure it out on their own pretty quickly. I imagine that this change would be very prominent in the announcement of a new version, so most people would see it before they upgraded. The solution for these developers is pretty obvious: add one line of code that sets handleLostContext to false.

**Comment by PrimaryFeather** [comment]
I just wrote that "Context Loss" article:
http://wiki.starling-framework.org/manual/context_loss

Furthermore, I revisited the whole manual, updating and correcting whatever jumped into my eyes.
Thanks again for the heads-up, guys!

**Comment by joshtynjala** [comment]
That looks great, Daniel. Thank you!

**Comment by ivanavdieienko** [comment]
Could you, please, change the description. It still tells that FALSE is the default value. Thank you.

**Comment by PrimaryFeather** [comment]
Ah, thanks a lot for the heads-up! Indeed, I overlooked that. Fixed! → https://github.com/Gamua/Starling-Framework/commit/50359ae31dbad88b5fdb02b2a11bdf5923b22323
