### ISSUE TITLE
DisplacementMapFilter texture size and the view port

### ISSUE THREAD

**Issue by neolit123** [Gamua/Starling-Framework#664]
hello,

i think there might be a small problem with the DMF class.

say we have a simple Main / Game test project:
https://dl.dropboxusercontent.com/u/1627980/starling/test_dmf0.zip

it consists of Main that has a resize handler, and each time the app resizes, it resizes the viewPort to fit the native stage, while the Starling stage remains at 400x300px.

it also updates the root class (Game).
the Game class display lists only has an Image (test.png - 400x300px) that has a DisplacementMapFilter (map.png - 400x300px).

when the native stage resizes the base image resizes fine, but the DMF texture remains at the same size as the .PNG size (native size).

looking at DisplacementMapFilter.as this happens because activate() calls updateParameters() with the native texture size.

two questions:

1) 
if i change it to the following it works but i'm not sure it's desired:
updateParameters(texture.width, texture.height);

can that be considered as a bug and would the change break other logic?

2) 
now, the bigger issue arises - how do we auto-resize the DMF texture, without forcing the user to manually re-create the DMF on each resize.

if i apply the change in 1) and remove the Game(_starling.root).update(); call in Main, i can see the DMF texture starts resizing based on mip map levels, but it never fits the stage (on demand) the same way as the base image (test.png) does.

any ideas how to solve that?

**Comment by neolit123** [comment]
> if i apply the change in 1) and remove the Game(_starling.root).update(); call in Main, i can see the DMF texture starts resizing based on mip map levels, but it never fits the stage (on demand) the same way as the base image (test.png) does.

so i was wrong above - it's not mipmap levels, but rather FragmentFilter in updatePassTextures() checks for a certain scale delta and only *then* updates the pass textures sizes.

i'm able to solve the auto-DMF texture resize via these two changes:

in DisplacementMapFilter::activate(...):
```
updateParameters(texture.width, texture.height);
```

instead of:
```
updateParameters(texture.nativeWidth, texture.nativeHeight);
```

in FragmentFilter::updatePassTextures(...)
```
var needsUpdate:Boolean = mPassTextures.length != numPassTextures || scale != mLastPassScale;
```

instead of:
```
var needsUpdate:Boolean = 
mPassTextures.length != numPassTextures ||
Math.abs(mPassTextures[0].nativeWidth  - width  * scale) > 0.1 ||
Math.abs(mPassTextures[0].nativeHeight - height * scale) > 0.1;
```

and "mLastPassScale" is then updated to "scale" in the "if (needsUpdate)" branch.

this achieves the result i want - DMF auto-scales with the stage.
question is, does it makes sense to you?

i can create a pull request if it's any good.
if not, perhaps you can suggest a better solution? :)

thanks

**Comment by PrimaryFeather** [comment]
Just a quick note: I'm already looking into, sorry for the delay! I agree, something's not working as planned here. I'll try out your changes and have a look at other options, then I'll get back to you!

**Comment by neolit123** [comment]
thanks

**Comment by PrimaryFeather** [comment]
Okay, I found the root of the problem! 

As you can see in the commit changes, only the DMF needed to be updated. The problem occurred when the global scale factor and the pass texture scale factor differed; the calculation of the maximum UV coordinates used the Starling scale factor on one side of the division, and the texture scale factor on the other. Now, I'm making up for that with an additional multiplication.

Thanks a lot for your great sample project! That made it very easy for me to reproduce the issue. And, again, sorry for the delay! 

Let me know if that works for you! :-)

**Comment by neolit123** [comment]
after a quick test it works nicely,

and this is a much cleaner solution. i was considering testing more in the DMF class, but for some reason i though it was a deeper problem.

thanks again!

**Comment by PrimaryFeather** [comment]
You're welcome! I'm happy to hear it works! :smile:
Don't worry, it took even me a while to get to the root of the problem, and I created those classes! ;-)
