### ISSUE TITLE
Single sprite ATF spritesheet sizing issue in AssetManager

### ISSUE THREAD

**Issue by yuhengh** [Gamua/Starling-Framework#667]
We have a small problem when upgrading to the newest Starling
We have a single sprite ATF spritesheet, with the SubTexture named the same as the file name.
And I ended up seeing the ATF texture with the wrong size (showing as the size of the file instead of the size of the sub texture)
The atf file is loaded into the mTextures and then mTextureAtlas when the xml is processed but without removing from mTextures.

In an older version of AssetManager we have
addTextureAtlas(name, new TextureAtlas(texture, xml));
removeTexture(name, false);

In the newer version of AssetManager there's only
addTextureAtlas(name, new TextureAtlas(texture, xml));

I think that might be the issue. Is it possible to add that line back in?

**Comment by PrimaryFeather** [comment]
Hm, yes, that will be the root of the problem. I thought that it might be useful to some developers to have access to the atlas texture via the asset manager; but you're not the first reporting problems with this, so I'll probably restore the old behavior. I'll look into it!

**Comment by PrimaryFeather** [comment]
Please let me know if that's better! :smile:

**Comment by yuhengh** [comment]
Looks good. Thanks Daniel!
