### ISSUE TITLE
Button: restore DOWN state after rollout&rollin

### ISSUE THREAD

**Issue by Maligan** [Gamua/Starling-Framework#668]
Button, doesn't restore down state after pressed mouse make rollout & rollin.
There is small obscurity based on `buttonRect` and `MAX_DRAG_DIST`, but afaik restore down state after rollout & rollin is a good practice.

I use this code addition in `Button#onTouch()` to add functionality (based on prev `else if` block)
``` as3
...
else if (touch.phase == TouchPhase.MOVED && state == ButtonState.UP)
{
	var buttonRect:Rectangle = getBounds(stage);
	if (touch.globalX > buttonRect.x &&
		touch.globalY > buttonRect.y &&
		touch.globalX < buttonRect.x + buttonRect.width &&
		touch.globalY < buttonRect.y + buttonRect.height)
	{
		state = ButtonState.DOWN;
	}
}
...
```

**Comment by PrimaryFeather** [comment]
I actually think this is a good idea — thanks for the suggestion! I'll probably add that soon.

**Comment by kheftel** [comment]
This would be more similar to how feathers buttons work, and most buttons in windows (and I would assume other OSes but can't remember off top of head)

**Comment by PrimaryFeather** [comment]
Yes, I just checked in iOS, and it behaves like that, too.

**Comment by PrimaryFeather** [comment]
Now it works just like in Feathers and iOS. Thanks again for bringing this to my attention! And please let me know if everything works for you. :smile:
