### ISSUE TITLE
Add reverse mode of MovieClip

### ISSUE THREAD

**Issue by martin3361** [Gamua/Starling-Framework#669]
very needed feature for many devs - flag for reverse playing of movie clip
current workaround - get the textures vector, reverse it and create new movie clip - too complex

**Comment by PrimaryFeather** [comment]
Would the following work for you?

```as3
var mc:MovieClip = ...;
mc.play(); // starts to play frames 0, 1, 2, 3

mc.pause(); // stopping at frame 1
mc.reverse();
mc.play(); // continuing at frame 1, but now 1, 0, 3, 2
```

**Comment by henke37** [comment]
Might as well allow changing the speed while at it.

**Comment by martin3361** [comment]
I think it would be better if there's just one flag of a MovieClip : reversed:Boolean, and the Juggler would play it backwards if true...

**Comment by PrimaryFeather** [comment]
I decided on a "reverseFrames" method that reverses all frames. I know that's not 100% what you wanted, @martin3361, but I hope it's still useful to you.

**Comment by PrimaryFeather** [comment]
@henke37, the speed can already be changed. Just use the "set fps" property.
