### ISSUE TITLE
Bug: The mNextTween property is not clear on reset()

### ISSUE THREAD

**Issue by Fraggle** [Gamua/Starling-Framework#670]
Hello Daniel,

I just stumbled upon a bug while using tween pooling.
The reset() method of Tween does not resetted the mNextTween property, it can cause problems from time to time.

Thanks again for the Framework!

Seb

**Comment by PrimaryFeather** [comment]
You're totally right! Wow, that little bug has been in there for quite a while. Thanks a lot for the heads-up, Sebastian!

**Comment by Fraggle** [comment]
21 minutes to fix it, I love open source ! :-)

**Comment by PrimaryFeather** [comment]
Haha, simple fixes are done right away, miracles might take a littler longer! :grin:
