### ISSUE TITLE
TextField dispose issue.

### ISSUE THREAD

**Issue by agnithegreat** [Gamua/Starling-Framework#675]
I have a lot of cells with a textfield inside, appearing and disappearing on a field. So, when I create a new TextField inside CellView, I need to dispose it on cell.destroy(). So, it looks like:

In constructor:
```ActionScript
_label = new TextField(100, 100, "", "numbers", -1, 0xFFFFFF);
_label.batchable = true;
_container.addChild(_label);
```

In cell.destroy():
```ActionScript
_label.removeFromParent(true);
_label = null;
```

It was not GC'ed accurately, I added a line before:
```ActionScript
_label.removeChildren(0, -1, true);
_label.removeFromParent(true);
_label = null;
```

Seems like you need to remove all children on TextField dispose.

**Comment by PrimaryFeather** [comment]
Hm ... theoretically, the GC should mark the complete object tree, so this shouldn't be necessary. I'm not removing object's children in the dispose method of other Starling objects, either.

How did you find out that it's not GC'ed accurately?

**Comment by agnithegreat** [comment]
It's strange: usually GC destroys TextFields carefully, but sometimes it may count over several hundreds of instances. No idea how it depends on situation.

**Comment by PrimaryFeather** [comment]
Okay, thanks for the update! Let me know if you run into this again; if there's anything I can do, I'd be happy to help! I'll close this issue for now, though.
