### ISSUE TITLE
BitmapFont Bidirectional TextField integration

### ISSUE THREAD

**Issue by HendrixString** [Gamua/Starling-Framework#679]
hi Daniel,

please have a look at the following repository:
https://github.com/HendrixString/Starling-Bidi-TextField
- this is a Bidirectional (RTL and LTR) BitmapFont TextField implementation
  as outlined at http://unicode.org/reports/tr9/
- i wrote it a year ago or more as a text engine for a commercial application that had
  50K downloads. I made some order in my sources and decided to interest you in
  integrating this into Starling, (i do request regardless that BitmapFont and TextField have their
  properties protected to make the components more of an extension ).

please tell me what you think.
the company I work for decided to go Native for most of our projects and we
ended up with tons of open source contribution being uploaded to my GitHub account.

**Comment by PrimaryFeather** [comment]
Hi Tomer,
thanks a lot for sharing this class with me! I'm sure this would be interesting for many developers; and the TextField (+ BitmapFont) classes are on my list of TODOs to be overhauled soon, so that's a big help. :smile:

**Comment by HendrixString** [comment]
sure,

if you need help with integration, you can use me for this task. this can be a very nice feature
for Starling  (;
