### ISSUE TITLE
TextField, question!

### ISSUE THREAD

**Issue by SnkyGames** [Gamua/Starling-Framework#681]
Hello, was curious, wouldn't it be better if textfields 'touchable' property was false by default?

**Comment by vpmedia** [comment]
I agree about this, textfields should be non-touchable by default.
At the moment I've use a factory method to setup my textfields.

**Comment by PrimaryFeather** [comment]
Hm, do you really think this would be intuitive? In Starling *all* other display objects are touchable by default, so what makes TextFields special?

**Comment by SnkyGames** [comment]
Oh they are all touchable? Well that's interesting. My personal issue is whenever I went to make anything with text involved, I always wondered why I can't sometimes touch something on screen if say I adjusted the textfield width and height, this textfield would always get in the way of the thing I was trying to touch. Nothing indicates it to me for a while, 'til it clicks in my head that the textfield should not be touchable.

I just do not see why it is touchable by default, if there is not any touch functions associated with it by default also, just my thoughts! Thanks for stencils! I look forward to 2.0, take your time! <3
I guess another reason: let's consider me still a starling noob, how many noobs will come to the conclusion that they would also need to turn touch off for textfields, if they ran into the same problem of this obstructing their underlying object?


Thanks

**Comment by vpmedia** [comment]
It's fine for me how it is now, I understand the concept behind it..
Also i've made some of my base classes before 'touchGroup' has been added.
Why disable? For me, one reason was what SnkyGames already described (overlapping textfields are blocking touch surfaces), the other one was performance optimization.

**Comment by PrimaryFeather** [comment]
Hm ... one thing I could do is to change the hitTest so that it only accepts a touch within the actual text bounds, instead of the complete text field. I guess this would prevent your confusion, right? You were probably surprised that you could touch it within the complete bounds?

**Comment by SnkyGames** [comment]
I'm not sure about it in-depth, but it was definitely the touchable property for me. :D I just thought it may be worth a mention, I'm sure you'll know the best course of action!

**Comment by PrimaryFeather** [comment]
Okay, thx! :wink:

**Comment by PrimaryFeather** [comment]
Ooops, hit the "close" button too soon! :wink:
I decided to leave this behavior unchanged, at least in the 1.x tree, to avoid confusion from developers who are used to the current behavior.
