### ISSUE TITLE
Updating AGALMiniAssembler to v3

### ISSUE THREAD

**Issue by vpmedia** [Gamua/Starling-Framework#686]
Hi!

With the new standard constrained profile (FP16) I think the as3 source script has also been changed:

https://github.com/adobe-flash/graphicscorelib/blob/master/src/com/adobe/utils/v3/AGALMiniAssembler.as

Do you think it can be updated in the Starling Framework also?

Thank You!

**Comment by PrimaryFeather** [comment]
Thanks for making me aware of that! I moved those changes over to Starling.
