### ISSUE TITLE
BGR_565 texture contours with a scaled stage

### ISSUE THREAD

**Issue by neolit123** [Gamua/Starling-Framework#690]
hello Daniel,

i have a question about sub textures and scaling. let's say, i have a texture atlas with some small (62x62px) "565" packed textures on a pink background padded by 1 pixel.

in the Starling root Sprite, Image classes are used to arrange the sub-textures.
the Starling stage is constant while the viewport just scales to make a fit on the Native stage (e.g. via RectangleUtil.fit(), not pixel perfect).

EDIT: i should probably add that in my test the Starling stage is bigger than the viewport.

what i'm observing when dragging the edge of the projector window to reduce it, is pink contours appearing at the edges of the Image elements. what i assume is that this is probably unavoidable due to sub-pixel scaling. could i attempt to somehow round the size of viewPort to prevent that?

the strange part is that if i use the pixel perfect scale in RectangleUtil.fit() on the stage and animate said Image elements the pink contours start appearing again.

if you want, i can possibly (hopefully) reproduce that in a demo project and post it here?

AIR 16.0.0.292, a very recent Starling from git.

**Comment by neolit123** [comment]
https://dl.dropboxusercontent.com/u/1627980/starling/test_scale_atlas.zip

- starling.swc is at 03d6cbbde0 (updated AGALMiniAssembler for new 'StandardConstrained' profile).
- build.sh can be used to compile it
- adl Main-app.xml (AIR 16) to run it

resizing the app window demonstrates that pink outlines.

**Comment by PrimaryFeather** [comment]
Hi Lubomir,
yes, that's unfortunately a frequent problem that has it's root in the way OpenGL makes texture lookups. With linear texture sampling, it frequently happens that a pixel outside the actual bounds of your sub-texture is included in the lookup, and that's what you're seeing.

The only reliable workaround for this is to extrude your textures. If you're using Texture Packer, there is an "extrude" setting that allows you to repeat the outermost pixels of the texture. The subtexture itself does not change its size; it's just the neighbor pixels that get updated. Most of the time, this fixes such problems.

Please try it out and let me know if that helps! :smile:

**Comment by neolit123** [comment]
i see, so there is not way to tell the graphics library (OpenGL, DirectX) to avoid interpolating (bi-/tri- linear sampling) the texture outer pixels from our end (Stage3D).

just tried editing the textures in the atlas and it seems to work OK with 2 pixels for the above test project. i was considering either morphological erosion (/ extrusion) or transparent atlas backgrounds (requires format change) as workarounds, but i wasn't sure if something else can be done.

thanks a lot for the explanation!

**Comment by PrimaryFeather** [comment]
> i see, so there is not way to tell the graphics library (OpenGL, DirectX) to avoid interpolating (bi-/tri- linear sampling) the sub-texture outer pixels from our end (Stage3D).

You can turn off interpolation completely, via `image.smoothing = TextureSmoothing.NONE` — but that's probably not what you want, except you're working on a retro-8bit title. :wink:

All the best for your project!
