### ISSUE TITLE
Minor documentation request for explaining Starling showStats memory

### ISSUE THREAD

**Issue by jamikado** [Gamua/Starling-Framework#692]
It might be useful to say a few words in the showStats documentation
http://doc.starling-framework.org/core/starling/core/Starling.html#showStats
about what the memory reported here actually is (not reporting GPU memory use) and maybe throwing a bone to tell people to profile with Adobe Scout for a complete breakdown of memory use.

I'd even go so far as to suggest even removing the memory stat from the showStats. Too many people ask about what the memory is reporting without bothering to check the source code of Starling to confirm.

**Comment by PrimaryFeather** [comment]
Agreed, this needed to be documented. Thanks for the suggestion!

I'm hesitant to remove it altogether, though. Ideally, I'd be able to display the data that Scout does, but that's currently not possible, afaik. And collecting the data manually from the texture instances is error-prone.
