### ISSUE TITLE
[Request] Device font in TextField with anti-aliasing

### ISSUE THREAD

**Issue by ShiMeiWo** [Gamua/Starling-Framework#701]
Some of East Asian characters(Kanji, Traditional Hanzi, Hangul, Thai alphabet, etc) have many stroke, "dotty-characters" of device font can make our eyes strained.
I suggest to add "useDeviceFontWithAntiAliasing" property to TextField Object and if the property is true, render the text texture with anti-aliased characters.

One of ideas of the implementation:
http://forum.starling-framework.org/topic/antialiasing-with-device-fonts#post-78844

Thanks.

**Comment by PrimaryFeather** [comment]
Thanks a lot for the suggestion! I can totally see that this would be useful for East Asian characters. 

I can't promise a date yet, though! In the meantime, I suggest you create a helper method that uses a "flash.text" TextField to create a texture with this trick.

**Comment by ShiMeiWo** [comment]
> In the meantime, I suggest you create a helper method that uses a "flash.text" TextField to create a texture with this trick.

Thank you very much, Daniel! :)

**Comment by PrimaryFeather** [comment]
I know it's been quite a while, but there is an update for this issue! :smile:

The current Starling version makes it easy to apply this manual anti-aliasing technique. You simply create a new `ITextCompositor` that extends the standard _TrueTypeCompositor_. The subclass now simply doubles the scale factor of the texture — like here:

```as3
public class HighResTrueTypeCompositor extends TrueTypeCompositor
{
    public function HighResTrueTypeCompositor()
    {}

    override public function fillMeshBatch(meshBatch:MeshBatch, width:Number, height:Number,
                                           text:String, format:TextFormat,
                                           options:TextOptions = null):void
    {
        options.textureScale *= 2;
        super.fillMeshBatch(meshBatch, width, height, text, format, options);
    }
}
```

With that prepared, you simply tell the TextField class to use this compositor either for all TextFields, or only for those using a specific font:

```as3
// use for all text
TextField.defaultCompositor = new HighResTrueTypeCompositor(); 

// use only for "Arial"
TextField.registerCompositor(new HighResTrueTypeCompositor(), "Arial");
```

That's it!

![font-comparison](https://user-images.githubusercontent.com/547347/32940010-ad0f52e2-cb81-11e7-8d78-c3a372431739.png)
