### ISSUE TITLE
Feature request - TouchProcessor.as

### ISSUE THREAD

**Issue by SnkyGames** [Gamua/Starling-Framework#702]
Hello, I posted a link below, I think it's quite an interesting topic, I find it amazing how all these 'little' quirks have already been taken care of, but I do believe ( as the thread will discuss ), that what Jeff suggested should be implemented for everyone, I wanted to make myself a Cancelled / Aborted Touch Phase, but Jeff is right, a 'began' event should have a pairing 'ended' event, his solution suggests I believe.. One extra variable in the Touch.as class, perhaps being "interrupted:Boolean" ( default: false ).

Then I believe the onInterruption function will set this variable to true in this little code block:

```as3
{
        touch.phase = TouchPhase.ENDED;
        touch.interrupted = true;
}
```

you will know better than me where it will be then be reset back to false, but I'm assuming it would be here:

```as3
// dispatch events
processTouches(mCurrentTouches, mShiftDown, mCtrlDown);
if (mCurrentTouches.length > 0)
{
        // reset interruption on all touches
        for each (var touch:Touch in mCurrentTouches)
        {
            touch.interrupted = false;
        }
}
```

Now I believe if this is all correct so far, an example use case of the new changes would be as follows:

```as3
public function touchEnded( x_:Number , y_:Number , interrupted_:Boolean = false ):void 
{
        if ( true == interrupted_ ) 
        {
            //do interrupted stuff, in my case, reset actions to a default state, 
            //as if the initial Touch never took place
            
            return; // this maybe useful, to skip the code below ( below code being normal touchEnded calls
            //do default touchEnded things if the 'touch' was not interrupted
        }
}
```

Well anyway, thanks for a great framework. ( I wrote all the spaces/tabbing out manually! wtf github, why you ruin my codeblocks! )

( reference )
http://forum.starling-framework.org/topic/touch-question-for-anyone-and-everyone#post-79065

**Comment by SnkyGames** [comment]
I've tested this now, did it WITHOUT the second patch of code I suggested for resetting the variable back to false.

        public function onInterruption( event:Object = null ):void
        {
            if (mCurrentTouches.length > 0)
            {
                // abort touches
                for each (var touch:Touch in mCurrentTouches)
                {
                    if (touch.phase == TouchPhase.BEGAN || touch.phase == TouchPhase.MOVED ||
                        touch.phase == TouchPhase.STATIONARY)
                    {
						touch.EndedForced = true;
                        touch.phase = TouchPhase.ENDED;
                    }
                }

                // dispatch events
                processTouches(mCurrentTouches, mShiftDown, mCtrlDown);
            }

            // purge touches
            mCurrentTouches.length = 0;
            mQueue.length = 0;
        }
    }

Also made the function public, and the 'event' argument to have a default option, so I could call this manually for a 'pause' screen I was making. 

_se.touchProcessor.onInterruption(); //Call a Forced 'ended' phase, on all touches
All seems to be working correctly, and without problem, have not currently tested, your default method via handledeactivated, if this function get's triggered.

**Comment by PrimaryFeather** [comment]
Agreed, this makes sense! I renamed the property "cancelled" so that it's easily recognized as a replacement for a "CANCEL" phase, as used in other frameworks. 

Thanks for the suggestion! :-)
