### ISSUE TITLE
AssetManager disposes / throws errors when enqueueing same asset simoultaneously.

### ISSUE THREAD

**Issue by geretti** [Gamua/Starling-Framework#703]
The AssetManager has a nifty feature that disposes of an old asset (and its stage presence) if a new asset with the same name is loaded.

A problem arises however if the very same asset gets enqueued at the same time (frequent when loading lists containing duplicate assets). The asset in question gets enqueued more than once and the following happens (line 301, addTexture() in AssetManager.as)

[AssetManager] Warning: name was already in use; the previous texture will be replaced.
Error #2044: Unhandled ErrorEvent:. text=Error #3677: Texture decoding failed. Internal error.

I would advise that the AssetManager iterate through the currently enqueued asset list before actually enqueueing. Additional enqueueing of the same asset would result in only added listeners, which would in turn all receive the onComplete event from the first (and effectively only) enqueueing.

**Comment by kheftel** [comment]
Why are you loading a list with duplicate assets in it?

**Comment by geretti** [comment]
Here's a few different scenarios:
- User joins the game with players already inside it. If multiple players use the same skin, multiple enqueueing happens.
- UI has 2 small grid lists, where the same elements appears on both lists.
- Blank elements in lists.

**Comment by PrimaryFeather** [comment]
Thanks for the report!
I could not reproduce the problem yet, though. Could add sample code that showcases the problem? A quick test of enqueuing images from different URLs with the same name worked without a problem.

Thanks in advance!

**Comment by kheftel** [comment]
I avoid duplicates in my project by checking to see if assets are there before loading.

**Comment by geretti** [comment]
I haven't tried to load over the web. This is a disk load (resolvePath).

In this example, the textures are 256x256 individual .ATF files. The "_data.asset" is the filename on disk.
This is run several times by a container class for Medals:

        GameAsset.getMedalTexture(_data.asset, _onMedalLoad);

And this is the static function called. "_medalAssets" is a AssetManager static field.

        static public function getMedalTexture(name:String, onComplete:Function):Texture
		{
			if (!_medalAssets) _medalAssets = new AssetManager(GameConfig.ASSET_SCALE);
            _medalAssets.verbose = _verbose;

			var texture:Texture = _medalAssets.getTexture(name);

			if (texture) {
				if (onComplete) onComplete(texture);
				return texture;

			} else {
				_medalAssets.enqueue(_mediaDir.resolvePath(MEDALS_PATH + name + FILE_EXT));
				_medalAssets.loadQueue(
						function (ratio:Number):void
						{
							if (ratio == 1 && onComplete) onComplete(_medalAssets.getTexture(name));
						}
				);
				return null;
			}
		}


This is what's called on the same enter_frame by all these individual containers.

       _medalAssets.enqueue(_mediaDir.resolvePath(MEDALS_PATH + name + FILE_EXT)); 

so multiple enqueueing for the same name happens at once, ultimately throwing the error in the GameAsset class.

**Comment by PrimaryFeather** [comment]
Thanks, that information helped. The problem arose only with ATF textures. They were added to the AssetManager before the asynchronous decoding was ready; and the circumstances here caused "dispose" to be called on the textures before they were actually ready. That lead to the exception.

Please let me know if that helps in your code, too! =)

**Comment by geretti** [comment]
Works like a charm now! Thank you!
