### ISSUE TITLE
Unregistering BitmapFont

### ISSUE THREAD

**Issue by Maligan** [Gamua/Starling-Framework#705]
For my app I must often register/unregister BitmapFont.

Problem occurs when:
1) Register BitmapFont
2) Create TextField and set fontName equals BitmapFont name (internaly TextField set `mIsRenderedText` flag to `true`)
3) Unregister bitmap font
4) Invalidate TextField
5) Catch error "Bitmap font not registered"

If I never register BitmapFont, flag `mIsRenderedText == false`, and TextField succefuly use native text engine.

I understand this is specific and rare problem, but TextField can work without exception if I reassign fontName property after removing BitmapFont, this fact confuse me.

**Comment by PrimaryFeather** [comment]
I'm not sure I fully understand this request. What do you mean by "invalidate TextField"?
And how should the TextField be rendered when the bitmap font has gone? Or would you like to fall back to a device font in that case?

**Comment by PrimaryFeather** [comment]
Nevermind, I think I understand what you mean. The latest change should avoid that problem. Please try it out and let me know if that was what you meant! Thanks in advance. :smile:

**Comment by Maligan** [comment]
Yes this fix solves my problems!
Thank you for your responsiveness, Daniel!

**Comment by PrimaryFeather** [comment]
You're welcome! I'm glad I could help. :smile:
