### ISSUE TITLE
Filter cache undispose after flatten the container

### ISSUE THREAD

**Issue by Niaobao** [Gamua/Starling-Framework#707]
I find that if you use a filter then flatten the sprite, the GPU menmory will leak. But now I solve the problem. So I hope this can be helpful.

I've post here
http://forum.starling-framework.org/topic/filters-cause-error-3691?replies=4#post-79654

in Sprite
private function disposeFlattenedContents():void
{
if (mFlattenedContents)
{
for (var i:int=0, max:int=mFlattenedContents.length; i<max; ++i)
mFlattenedContents[i].dispose();

mFlattenedContents = null;
}
}

should change to
private function disposeFlattenedContents():void
{
if (mFlattenedContents)
{
for (var i:int=0, max:int=mFlattenedContents.length; i<max; ++i){
if(mFlattenedContents[i].texture){
mFlattenedContents[i].texture.dispose();
}
mFlattenedContents[i].dispose();
}

mFlattenedContents = null;
}
}

https://github.com/Gamua/Starling-Framework/compare/master...Niaobao:patch-1
is this link correct? It's my first time to use Github. Not sure. :D

**Comment by PrimaryFeather** [comment]
Thanks a lot, @Niaobao! That's an excellent catch. I used a slightly different fix (to make sure the texture never gets forgotten), but the gist it the same. Thanks a lot for your efforts and for pointing me towards this! Good work! :smile:

**Comment by chadrem** [comment]
I believe I am encountering a GPU memory leak that the same or similar to the one in this issue.  I am using the latest Starling and latest Feathers as of today (Wed Jun 10 11:59:23 EDT 2015) with the latest Adobe Air 18 beta SDK.

Starling latest commit: ````68aa0813dc8f822ec07b83401c65f627aecc17d2````
Feathers latest commit: ````1a8e67c31d25d88b29d10b1b888bba8055ca967c````

My code does the following...

1. Creates a Feathers Scale9Image using a texture from Starling's asset manager.
2. Applies a BlurFilter to the scale9image.
3. Adds the image as a child.
4. flatten's the image.
5. On a one second timer it disposes the parent sprite and recreates it along with the Scale9Image child and filter.

After a few hundred iterations of the above, Scout reports GPU memory in the mid 500MB range and the app crashes.  No crash (or memory leak) occurs if I comment out the line where I apply the filter (image.filter = new BlueFilter...).

The below code is what creates the image and filter.  The parent of the ````_image```` (which is a Sprite) gets disposed and recreated on the timer.

    var rectangle:Rectangle = new Rectangle(150, 150, 70, 70);
    var texture:Texture = assetManager.getTexture('image1');
    var scale9Texture:Scale9Textures = new Scale9Textures(texture, rectangle);
    _image = new Scale9Image(scale9Texture, 1.5);
    _image.width = 200;
    _image.height = 200;
    var filter:BlurFilter = new BlurFilter(1.5, 1.5, 2);
    _image.filter = filter;
    addChild(_image);
    flatten();

**Comment by chadrem** [comment]
@PrimaryFeather please let me know if I should open a new issue instead of commenting on this one.  Unfortunately I can't tell if it's the same problem, but it sure seems very similar.  Thank you.
