### ISSUE TITLE
[Feature] New blend mode

### ISSUE THREAD

**Issue by b005t3r** [Gamua/Starling-Framework#710]
I came across a blend mode I find quite useful in my project, I think it could also be useful for others.

I called it "mask" and it erases everything that's not under a currently drawn object (it applies this object's alpha channel to the image below).

```as3
        private static var sBlendFactors:Array = [ 
            // no premultiplied alpha
            { 
                // ...
                "mask"     : [ Context3DBlendFactor.ZERO, Context3DBlendFactor.SOURCE_ALPHA ]
            },
            // premultiplied alpha
            { 
                // ...
                "mask"     : [ Context3DBlendFactor.ZERO, Context3DBlendFactor.SOURCE_ALPHA ]
            }
        ];
// ...
        /** Opposite of ERASE blend mode. */
        public static const MASK:String = "mask";
```

**Comment by kheftel** [comment]
sorry, I'm having trouble following. what exactly does it do? an example might help.

**Comment by PrimaryFeather** [comment]
Yes, a sample image would be great! Thanks in advance! =)

**Comment by b005t3r** [comment]
Well, it does the opposite of ERASE - pixels which are covered by non-transparent pixels of display object currently being draw are preserved and the ones under transparent pixels are erased (each output pixel is multiplied by source pixel alpha value, source color data is not used; erase does the opposite, it multiplies output by 1 - sourceAlpha).

The effect would be almost exactly like using CALayer's mask property on iOS:

https://developer.apple.com/library/prerelease/ios/documentation/GraphicsImaging/Reference/CALayer_class/index.html#//apple_ref/occ/instp/CALayer/mask

Do you still need an example image? :)

**Comment by PrimaryFeather** [comment]
And, just like "ERASE", it's best used in RenderTextures, right?
I think I can imagine what the output should look like; but if you've got a minute, a sample image would still be nice, if it's not too much to ask. :wink:

**Comment by b005t3r** [comment]
Yes, I forgot to add this - it probably makes sense to use it when rendering to texture only.

Here's the example image. On the left default alpha blending is used to draw the circle over the starling image. On the right circle is draw using MASK mode.
 
![mask](https://cloud.githubusercontent.com/assets/757150/7511051/616a8482-f4a2-11e4-9b9b-98b660d84a57.png)

**Comment by PrimaryFeather** [comment]
Thanks a lot for the sample image! Now it's 100% clear — thanks! 
I agree, that would be useful for other developers as well. I'll probably merge that soon!

**Comment by b005t3r** [comment]
Cool, thanks!

**Comment by jamikado** [comment]
I realize Daniel has already said he will add it, but just for those reading (in case this wasn't obvious from the current API), you don't actually have to modify the starling.display.BlendMode source code to add this or other custom blend mode settings to try it out.  There is the BlendMode.register method that allows you to add these settings at runtime without requiring source code mods.  Just in case someone came up with new blendmodes or wanted to experiment more...

**Comment by PrimaryFeather** [comment]
Exactly! I totally forgot to mention that ... thanks Jeff! :smile:

**Comment by kheftel** [comment]
Ah, so it's mostly useful for render textures.  Thanks for the explanation and sample image!  This should be a nice complement to the pixelmask extension (http://wiki.starling-framework.org/extensions/pixelmask).

**Comment by b005t3r** [comment]
I never used pixel mask, but it probably works in a very similar way - it renders its children onto a texture and then renders the texture using a custom blend mode.
