### ISSUE TITLE
Strange offset applied when rendering an object using FragmentFilter to texture

### ISSUE THREAD

**Issue by b005t3r** [Gamua/Starling-Framework#711]
I'm rendering an object with filter attached to a texture. The object itself renders correctly, but the filter below (drop shadow) looks clipped. Also, how it is clipped changes along with pivot change.

Here's the object rendered with pivot at top-left:
![filter_no_align](https://cloud.githubusercontent.com/assets/757150/7514318/b1e7c61c-f4bc-11e4-9790-e24fa841fe09.png)

And here's the same object (different background, not important) rendered with pivot centered horizontally and vertically:
![filter_align](https://cloud.githubusercontent.com/assets/757150/7514335/cb4bdfe4-f4bc-11e4-846b-e121ce5d0930.png)

As you can see, the shadow is clipped, so my guess is when rendering the first pass the object was not aligned correctly (but the object itself renders onto the texture without any clipping).

**Comment by PrimaryFeather** [comment]
The object on which the filter is used is a normal "Image" instance, right?

**Comment by b005t3r** [comment]
Yes, normal Image, nothing fancy.

**Comment by b005t3r** [comment]
I just noticed, clipping changes when I resize app's window (images are quite large, sorry for that):

![frame_small](https://cloud.githubusercontent.com/assets/757150/7515308/26d1ea80-f4c6-11e4-9daa-60aacd5943ac.jpg)
![frame_big](https://cloud.githubusercontent.com/assets/757150/7515309/26f8db72-f4c6-11e4-8797-f41dcc759bae.jpg)

**Comment by b005t3r** [comment]
Also, I'm using a lot of Feathers controls here, maybe it's somehow connected with how ScrollContainer or some other control works?

**Comment by PrimaryFeather** [comment]
Hm, hard to say — could be some side effect, but not necessarily. Can you manage to recreate the problem with a small, pure Starling sample?

**Comment by b005t3r** [comment]
This is definitely connected with Feathers. I changed the layout and as you can see, everything renders as it should, but when I scroll a bit with window resized shadow gets clipped again:

![frame_big_left](https://cloud.githubusercontent.com/assets/757150/7515764/0f95420a-f4ca-11e4-8c2a-c4515e6b942b.png)
![frame_small_left](https://cloud.githubusercontent.com/assets/757150/7515765/0fbd65a0-f4ca-11e4-912e-e5efe08ca2d7.png)

I'm adding @joshtynjala to this conversation.

**Comment by b005t3r** [comment]
I removed rendering to texture and there's still clipping, but different:

![no_texture](https://cloud.githubusercontent.com/assets/757150/7516003/3d7765d4-f4cc-11e4-9782-c2bc8f960181.jpg)
I create my filter using: ```BlurFilter.createDropShadow(50)```

**Comment by joshtynjala** [comment]
ScrollContainer uses clipRect. Would that affect how filters render in any way?

**Comment by PrimaryFeather** [comment]
@joshtynjala The idea would be that it doesn't — but I won't rule out a bug on Starling's side. In this situation, the render target changes, which means there could be a problem with updating the scissor coordinates. 

@b005t3r, which version of Starling/Feathers are you using? Have you tried the latest dev revisions? I *think* I fixed something related to filters and clipRects a while ago ...

**Comment by b005t3r** [comment]
I pulled both Starling and Feathers yesterday. I'm also using AIR 17.

I tested with outdated versions (don't know how outdated though) and the result was exactly the same.

**Comment by b005t3r** [comment]
Maybe it would be a good idea to connect current clip rect stack with render target, so each render target would get a separate clip rect(s)?

**Comment by PrimaryFeather** [comment]
It is connected, actually, but maybe there's some problem with that. (The 'applyClipRect' method of RenderSupport does that.)

Have you tried if you can reproduce the problem with a pure Starling sprite, using a clipRect, and a filter? That would be a huge help.

**Comment by b005t3r** [comment]
I can prepare a sample app using Starling and Feathers, and the same layout I use in my app. I'm not sure if I will be able to reproduce this problem with Starling only - maybe it's about something specific to Feathers.

Would that help?

**Comment by PrimaryFeather** [comment]
As a first step, I'd prefer it if you could try if a simple clipRect + filter combination (without Feathers) can already reproduce the problem. Perhaps the issue is not as obscure as it seems. If it's not easily reproducible that way, we can still put Feathers in the equation.

**Comment by b005t3r** [comment]
I prepared a small test with Straling and clipRects only, as you asked. Results are a bit different than with Feathers, but you can still clearly see there are problems when using filters and clipRect combo:

https://dl.dropboxusercontent.com/u/23855128/ClipRectTest.zip

**Comment by PrimaryFeather** [comment]
Ah, perfect — that's what I was looking for. Thanks a lot for your efforts!
I'll have a look at it and will get back to you as soon as I know more.

**Comment by PrimaryFeather** [comment]
Okay, I understand what causes the problem: it's the combination of "offset" (of the drop shadow) and "clipRect". I probably always tested with a pure blur (no offset) or other filters, that's why I didn't notice. As a quick workaround, if you create your filters with `BlurFilter.createDropShadow(0)`, the problem should go away.

Of course, not the final solution, but a start. :wink:

**Comment by b005t3r** [comment]
Do you think that's the only thing that causes the problem? With Feathers changing containers size, scrolling and changing pivot gave me different clipping, so there's probably more to it than just shadow's offset.

**Comment by PrimaryFeather** [comment]
Hm, well, at least that's the first thing I found, there might be other problems, of course. 
But it should be easy to check: does the problem go away if you set the shadow offset to zero in your original project?

**Comment by b005t3r** [comment]
I just checked and with scrolling, when the container is smaller than my display object and only part of it is displayed, I can see the clipping happening.

Also, one thing I noticed with the sample project I gave you. With default filter implementation and how clipping is currently designed to work with filters, you render only the part of the object which is currently visible on the screen - the part which is off screen won't be rendered to texture. But with filters like the blur one this is not the right approach - you can see the top-left starling has the left wing off screen and its shadow is clipped which looks rather odd, because you know the wing's shadow should be there (you know the wing does not end where the screen ends :) ).

I think you should calculate the filter's output position and apply clipping/offset using that rather that doing it based on filtered object's position. Of course, the current approach works for all other filters except blur used as a shadow :)

**Comment by PrimaryFeather** [comment]
<blockquote>Also, one thing I noticed with the sample project I gave you.</blockquote>

Haha, yes, that's the other thing I noticed. I need to change that logic, as well. 
Well, I'll have a look at the problems one at a time. :wink:

**Comment by PrimaryFeather** [comment]
Okay, now your demo project works just fine! Please verify that on your system and then try out if this fix helps with your original problem, as well. Thanks in advance! :smile:

**Comment by b005t3r** [comment]
Thanks for the fix, Daniel! Demo project works as it should on my machine, but my other app which uses Feathers still has some problems when objects with drop shadow filter are attached are set as ScrollContainer's children.

I can test some more tomorrow, check it this is not something on my side and prepare another test project using Feathers controls if that would help.

**Comment by PrimaryFeather** [comment]
Hm, okay — well, we're one step closer to getting this fixed, in any case. =)
Yes, please try if you can find out more, and if there's no other way to reproduce it, please create a simple Feathers-based project. Then either myself or Josh - or both - can look into it. Thanks!

**Comment by b005t3r** [comment]
Sure, will do!

**Comment by b005t3r** [comment]
OK, I prepared another test, this time with Feathers.

https://dl.dropboxusercontent.com/u/23855128/ClipRectFeathersTest.zip

I couldn't reproduce the bug with Feathers only controls, so I also added the same technique my app uses - top-left and bottom-right panels have display objects wrapped in a Sprite, which first renders its children to texture and then renders the texture itself to the screen. Top-right and bottom-left panels simply render images with filter attached.

Panels with contents rendered to texture show clipping of the object's shadow (you need to play with the window size and scroll bars position to see the clipping, but it is there), standard panels don't show any clipping.

**Comment by PrimaryFeather** [comment]
Please try out if the solution offered in #717 fixes this issue, too — and if so, please close the thread. Thanks!

**Comment by PrimaryFeather** [comment]
The filters of Starling 2 should be able to cope with all those issues. If not, please reopen or (better) create a new issue. :wink:
