### ISSUE TITLE
Error compiling for iOS (armv7 symbol not found) 

### ISSUE THREAD

**Issue by mariommoreno** [Gamua/Starling-Framework#713]
It looks like CharLocation or any other class out of a package are not supported by the architecture.

Solved: Extracting CharLocation to a new file CharLocation.as

**Comment by PrimaryFeather** [comment]
I'm not sure I understand the problem — you say that you got the error "armv7 symbol not found", and could solve it by moving "CharLocation" to its own file?

**Comment by mariommoreno** [comment]
I can't remember the exact error string, maybe it was: "Undefined symbols for architecture armv7".
But yes, I solved the problem after moving CharLocation to its own file, and the same for my "not public" classes I had in my project.

I was using ASCSDK 16.0.0  and packaging without "-interpreter" flag.

**Comment by PrimaryFeather** [comment]
Were you also using the latest AIR compiler? I remember some other developers mistakenly using the ASC1 compiler, but the latest AIR SDK, and this lead to weird problems, especially with the new enhanced packaging for iOS.

**Comment by mariommoreno** [comment]
I'm using asc2.0 (mxmlc-cli) v.16 because v.17 is crashing my app (flickers and disappears while loading assets but everything is touchable. But this is another issue I will report if I can't follow with v16 compiler).

Anyway the error appears during the packaging process: call adt -package -target ipa-test....

**Comment by PrimaryFeather** [comment]
Hm, that's interesting. It's weird that I haven't heard any other reports of that happening. Perhaps it's some combination of things that the packager does not like. :-/

In any case, I wouldn't want to start changing the Starling source to accommodate bugs in the compiler or packager. Having those anonymous classes is perfectly valid AS3 code, after all.

I'll keep this under surveillance — and please post any new information you've got on the issue! 
We can reopen it any time.

But I won't change the Starling code for the time being. Ideally, you'd create a bug report on Adobe's bug base. Question is, though, if it will be possible to create a simple demo project that reproduces the error. It's very likely that simpler projects won't produce that problem.

**Comment by mariommoreno** [comment]
Ok, I understand.
I'll try to reproduce the error simplifying as much as possible.

**Comment by PrimaryFeather** [comment]
Thanks for your understanding — and good luck!
