### ISSUE TITLE
textfield formatting issue

### ISSUE THREAD

**Issue by gameaccount** [Gamua/Starling-Framework#716]
Hi - Jeff suggested submitting this issue (forum http://forum.starling-framework.org/topic/textfield-formatting-issue)

The probem starts when I create a starling textfield with isHtmlText set to true, and specify some leading (linespacing) in my text. For example:

<code>< textformat leading='10' >contents goes here< /textformat ></code>

That works fine and I get a textfield with extra space between lines.

But any subsequent starling textfields I create with also have the same leading, even if isHtmlText is to false.

I think I can see what's causing it. When you create a new TextFormat object in the starling textfield renderText() method and apply it to the static flash textfield (sNativeTextField), the leading is not specified in the TextFormat constructor. According to the flash textfield documentation, null leading should default to '0', but it isn't. 

You can replicate this by creating 3 starling textfields, one after the other, side by side, with the same text in each one. Add '< textformat leading='50' >' to the start of the second textfield so that extra linespacing appears between the lines. You should now see that the 3rd textfield has this extra spacing too.

I think this could be a flash textfield bug, but can I suggest changing your TextFormat object as a workaround, and explicity setting the leading to '0'?

From:

var textFormat:TextFormat = new TextFormat(mFontName, mFontSize * scale, mColor, mBold, mItalic, mUnderline, null, null, hAlign);

To:

var textFormat:TextFormat = new TextFormat(mFontName, mFontSize * scale, mColor, mBold, mItalic, mUnderline, null, null, hAlign, null, null, null, 0);

**Comment by PrimaryFeather** [comment]
Thanks a lot for making me aware of this!
I agree that this looks like a code in the Flash runtime. I can easily change that!

One thing, though: I can't reproduce the problem. At least on OS X (Flash Player) and iOS, the leading value is always reset with the latest Starling version, i.e. the leading of one TextField did not influence the others. What are your platform/device/version details?

**Comment by gameaccount** [comment]
Hi - I'm using Starling 1.6 (downloaded a few weeks ago).

I see this issue on a Windows 7 PC (AIR desktop) and a Nexus 5 running Android 5. Here's a screenshot from my Windows PC: https://www.dropbox.com/s/lf6ka7kej9etdh9/leading01.jpg?dl=0

I used the following code to produce it:

<code>
			var aText:TextField = new TextField(this.width * 0.2, this.height * 0.5, "test A\nsecond line\nthird line");
			aText.border = true;
			this.addChild(aText);
			
			// add gold balance field
			var bText:TextField = new TextField(this.width * 0.2, this.height * 0.5, "<textformat leading='50'>test B<br>second line<br>third line");
			bText.x = aText.x + aText.width;
			bText.isHtmlText = true;
			bText.border = true;
			this.addChild(bText);

			var cText:TextField = new TextField(this.width * 0.2, this.height * 0.5, "test C\nsecond line\nthird line");
			cText.x = bText.x + bText.width;
			cText.border = true;
			this.addChild(cText);
</code>

**Comment by PrimaryFeather** [comment]
Interesting! With this code, I can reproduce the problem. I must have done something in a different way ... I'll try to find out the reason and then make the change, as requested. Thanks again!

**Comment by PrimaryFeather** [comment]
I actually took this opportunity to add a dedicated "leading" property to the TextField class. So while this is now fixed, you actually don't have to use the `<textformat>` hack any longer. :wink:

**Comment by hejiacong** [comment]
why not add support textFormat.letterSpacing too,i think they are a pair with the leading property

**Comment by PrimaryFeather** [comment]
Yes, this will come too, eventually. Starling 2.0 will see more options for text, and probably a "TextFormat" class. ;-)
