### ISSUE TITLE
Crashing during loading using AssetManager

### ISSUE THREAD

**Issue by shanemccartney** [Gamua/Starling-Framework#721]
I can confirm that the IO Error does happen on mobile I am not sure on why or the circumstance. However we are finding that the onIOError causes a null exception reference error see a logged stack trace below.

TypeError: Error #1009
1	at Function/AssetManager.as$7:anonymous()
2	at starling.utils::SystemUtil$/executeWhenApplicationIsActive()
3	at Function/complete()
4	at Function/onIoError()
5	at flash.events::EventDispatcher/dispatchEvent()
6	at flash.net::URLLoader/onComplete()

Unfortunately we don't get a line number for the anonymous function throwing the error. But as its anonymous its one of the methods you are creating anonymously most probably the error is due to these lines in the Asset Manager. Actually its quite an easy error to follow to prove this!

asset.bitmapData.dispose();

or

asset.clear();

You will see that in the complete method you pass null as the asset in the case of error, but the complete handler will try to access this as seen above causing an exception meaning that an error can't be handled without causing the app to crash.

Read more here http://forum.starling-framework.org/topic/assetmanager-failing-to-load-textures?replies=10#post-80965

**Comment by shanemccartney** [comment]
Also looking into this a bit further I have other issues with how errors are handled here for example :+1: 
 mNumRestoredTextures++;

 if (mNumLostTextures == mNumRestoredTextures)
                                dispatchEventWith(Event.TEXTURES_RESTORED);

This is happening even if the restoring of a texture fails as it doesn't take into any consideration the try catch above it. This is different but also related to the error handling issues with the AssetManager

**Comment by shanemccartney** [comment]
You can see my proposed changes in this version of the AssetManager https://www.dropbox.com/s/v68su47xqlqujf5/AssetManager.as?dl=0

**Comment by honzabrecka** [comment]
@shanemccartney Can you prepapre a PR, please, so we can easily review your proposed changes?

**Comment by shanemccartney** [comment]
I don't have the time right now, really I am just making you aware of a big and quite obvious error with exceptions being thrown by the Asset Manager

**Comment by PrimaryFeather** [comment]
Sorry for the long delay - the report received me while I was on vacation.
In any case, I added a fix! I could not open the dropbox link, but your description was detailed enough so that I could easily reproduce it.

Thanks for making me aware of this issue!
