### ISSUE TITLE
The Documentation APi?

### ISSUE THREAD

**Issue by blackjyn** [Gamua/Starling-Framework#723]
Please include the API in the repo like FeathersUI did . thanks

**Comment by PrimaryFeather** [comment]
I'll look into it, thanks for the suggestion!

**Comment by blackjyn** [comment]
:+1: , thanks for considering :)

**Comment by honzabrecka** [comment]
I'm against the suggestion. Repo shouldn't contain anything that can be compiled.

**Comment by PrimaryFeather** [comment]
I agree, Honza: I wouldn't put it in the repo, but some other place.
I'm considering links to all zipped API references in the Wiki or on "doc.starling-framework.org".

**Comment by honzabrecka** [comment]
It would be cool if doc.starling-framework.org contained docs for all released versions (1.0, 1.1, ..., 1.7) and for master. Something like this:

doc.starling-framework.org/ -> doc.starling-framework.org/v1.7rc
doc.starling-framework.org/master
doc.starling-framework.org/1.0
doc.starling-framework.org/1.1

**Comment by PrimaryFeather** [comment]
Yes, I also think that would make most sense! 
Plus some place where people can download zips for offline usage.

**Comment by PrimaryFeather** [comment]
It's still very basic - but usable! ;-)

http://doc.starling-framework.org/archive/

You can access the reference for all versions back to v1.3, browse them online, or download a zip-file.
