### ISSUE TITLE
"HOVER" TouchEvent should not be fired on deviced not supporting cursor

### ISSUE THREAD

**Issue by Francois-Tobo** [Gamua/Starling-Framework#727]
I had a problem where buttons stayed on there "over" state due to the reception of an "HOVER" TouchEvent just after the release of said buttons.

After a few exchange with Jeff, he came to the conclusion that "Hover" TouchEvent probably shouldn't be fired if Mouse.supportsCursor is false. Here is the reference on the Starling forums : 
http://forum.starling-framework.org/topic/touchevent-hover-event-fired-after-ended-event

**Comment by PrimaryFeather** [comment]
You're right, that artificial `HOVER` makes only sense on devices that support a mouse cursor. Thanks a lot for the report! :smile:
