### ISSUE TITLE
Invalid child index

### ISSUE THREAD

**Issue by raduev** [Gamua/Starling-Framework#730]
Hello, i have download latest Starling, and Feather libs, and now i get error on DisplayObjectContainer.as on line 144, when i addChild on ScrollContayner, tnx !

**Comment by PrimaryFeather** [comment]
Just to be sure: are you using the Feathers development version? The stable Feathers library always works with the latest stable Starling version (in this case, 1.6), but may fail with Starling's current dev-version.

Right, @joshtynjala?

Also, please add your complete callstack!

**Comment by joshtynjala** [comment]
Daniel made a change in addChild() in Starling 1.7 RC that required a change to the override of this function in ScrollContainer. The fix is included only with Feathers 2.2 beta at this time. The current stable version of Feathers, 2.1.1, is only compatible with Starling 1.6.

**Comment by raduev** [comment]
i user Feathers 2.1.1, and Starling 1.6

**Comment by raduev** [comment]
sorry, i recheck, 1.5 starling

**Comment by PrimaryFeather** [comment]
Thx, @joshtynjala! =)
