### ISSUE TITLE
Incoherence in ScrollContainer using displayListBypassEnabled=true

### ISSUE THREAD

**Issue by mariommoreno** [Gamua/Starling-Framework#734]
`displayListBypassEnabled` overrides `addChildAt`, but doesn't do the same with `addChild`. The problem is that `addChild` uses `mChildren.length` as index and `addChildAt` uses the `this.viewPort` as container, raising `RangeError: Invalid child index`.

**Comment by PrimaryFeather** [comment]
I guess this ticket was meant to be created in the Feathers project, right?
→ https://github.com/joshtynjala/feathers

**Comment by mariommoreno** [comment]
Uops! sorry! I just updated Feathers 1.7 and this stopped working.

**Comment by PrimaryFeather** [comment]
No worries! ;-)

I think you'll need the very latest Feathers version to use the latest Starling version! I think Josh already fixed that problem there.
