### ISSUE TITLE
Separating Glow and Blur filters

### ISSUE THREAD

**Issue by GRIM2D** [Gamua/Starling-Framework#737]
Please separate glow, shadow, blur filters. Sometimes I need to change parameters of glowing effect using tween. 

```actionscript
var glow:GlowFilter = new GlowFilter(0xFFFFFF, 0);
var tween:Tween = new Tween(glow, 1);
tween.animate("alpha", 1);
Starling.juggler.add(tween);
object.filter = glow;
```

**Comment by PrimaryFeather** [comment]
This is already planned for the filter update (scheduled for Starling 2).

In the meantime, I recommend you simply subclass "BlurFilter" and add getters and setters for color and alpha, which call the method "setUniformColor" on the BlurFilter. With those properties, you'll then be able to animate the glow.

If you need any help with that, just let me know.

**Comment by PrimaryFeather** [comment]
Done! :ballot_box_with_check: 
That's now a part of Starling 2.
