### ISSUE TITLE
Add subScale parameter in SubTexture

### ISSUE THREAD

**Issue by LorenzGit** [Gamua/Starling-Framework#740]
Sometimes one Texture scale factor is not enough for multiple SubTextures, it would be great to have a subScale parameter, like this:

SubTexture.as
SubTexture(parent:Texture, region:Rectangle=null,
   ownsParent:Boolean=false, frame:Rectangle=null,
   rotated:Boolean=false, subScale:Number = 1)

mSubScale = subScale

/** @inheritDoc */
public override function get width():Number { return mWidth / mSubScale; }

/** @inheritDoc */
public override function get height():Number { return mHeight / mSubScale; }

**Comment by PrimaryFeather** [comment]
Yeah, I agree that this would be useful. I'll probably add that, though I can't give you a date yet.
In the meantime, anyone else looking for this feature, please add your votes below! Thanks in advance! =)

**Comment by PrimaryFeather** [comment]
That's now part of Starling 2.0! You'll find the new `scaleModifier` parameter at the end of the argument lists of the `SubTexture` constructor as well as `Texture.fromTexture()`.

Thanks again for the suggestion!
