### ISSUE TITLE
Request: Better documentation for AssetManager.dispose();

### ISSUE THREAD

**Issue by kevinfoley** [Gamua/Starling-Framework#742]
The function documentation for AssetManager.dispose() does not indicate that the dictionaries are preserved. Users who have missed the purge() function may assume that dispose() will also clear the dictionaries.

**Comment by PrimaryFeather** [comment]
You're right, it was necessary to document that better. Thanks for the heads-up!

In general, Starling's "dispose" methods never (that is: rarely) nullify any member variables. You're supposed to destroy any references to the object you called "dispose" on and let the Garbage Collector do that. "dispose" will simply destroy those things the Garbage Collector doesn't care about, or those that take up a lot of memory and can be destroyed manually (e.g. ByteArrays and XMLs) to free up the memory quickly. (Nullifying references does not remove the object's memory; the GC still has to destroy them before this will happen.)
