### ISSUE TITLE
[Request] Add atlas getter in AssetManager.as

### ISSUE THREAD

**Issue by geretti** [Gamua/Starling-Framework#743]
My project requires iterating over the multiple loaded atlases to retrieve a specific atlas, given a texture name.
For that reason I've added this code on line 236 (after getTextureAtlas)

        public function getAtlases():Dictionary
        {
            return mAtlases;
        }

Could be useful to others! Here's my game code that requires that getter:

            var atlas:TextureAtlas;
            var texture:Texture;
            var atlases:Dictionary = _assetManager.getAtlases();

            for each (var atl:TextureAtlas in atlases)
            {
                var tex:Texture = atl.getTexture(weaponAsset);
                if (tex) {
                    texture = tex;
                    atlas = atl;
                    break;
                }
            }

**Comment by PrimaryFeather** [comment]
For consistency with the rest of the class, I added a "getTextureAtlasNames" method instead, working analogue to "getSoundNames", "getTextureNames", etc. It should solve the same problem, though. :-)

Thanks for the suggestion, and I hope my solution helps you!

**Comment by geretti** [comment]
Perfect. Thanks!

**Comment by PrimaryFeather** [comment]
You're welcome!
