### ISSUE TITLE
[Rendering] Strange behaviour

### ISSUE THREAD

**Issue by GRIM2D** [Gamua/Starling-Framework#745]
```actionscript
package {

    import display.core.Game;

    import flash.display.Sprite;
    import flash.display.StageAlign;
    import flash.display.StageScaleMode;
    import flash.display3D.Context3DProfile;
    import flash.events.Event;
    import flash.geom.Rectangle;

    import starling.core.Starling;

    [SWF(frameRate="60", backgroundColor="0x000000")]
    public class Main extends Sprite {

        public static var STAGE_WIDTH:Number  = 0;
        public static var STAGE_HEIGHT:Number = 0;
        public static var SCALE:Number;

        public static function scale(px:Number):Number { return px * SCALE }

        private var engine:Starling;

        public function Main() {
            stage.scaleMode = StageScaleMode.NO_SCALE;
            stage.align     = StageAlign.TOP_LEFT;

            init();
        }

        private function init():void {
            STAGE_WIDTH  = stage.fullScreenWidth;
            STAGE_HEIGHT = stage.fullScreenHeight;
            SCALE        = (STAGE_WIDTH * STAGE_HEIGHT) / (2208 * 1242);
            trace("[Main]", "Scaling:", SCALE.toFixed(2));

            Starling.handleLostContext = true;
            Starling.multitouchEnabled = true;

            engine = new Starling(Game, stage, new Rectangle(0, 0, STAGE_WIDTH, STAGE_HEIGHT), null, "auto", Context3DProfile.BASELINE_CONSTRAINED);
            engine.start();
        }
    }
}
```

This happens only on device. iPad Air 2. iOS 8.4

Starling 1.7:
![thumb_img_0143_1024](https://cloud.githubusercontent.com/assets/6705445/9005456/caafd428-3797-11e5-8f9a-b4bd8bcfb8e3.jpg)
![thumb_img_0144_1024](https://cloud.githubusercontent.com/assets/6705445/9005457/cab1816a-3797-11e5-930f-648471e7a6b2.jpg)
![thumb_img_0145_1024](https://cloud.githubusercontent.com/assets/6705445/9005455/caae6ade-3797-11e5-9072-45f5989a00bf.jpg)

I'm not using mask, or something either. It's strange. Because, when I run in debug mode or run with 'Fast package' checked, I get correct screen. But, when running with standard packaging (not release), I get screens above.

Compiled with Starling 1.6
![thumb_img_0146_1024](https://cloud.githubusercontent.com/assets/6705445/9005458/cab21dfa-3797-11e5-92cc-2337e1ab6a02.jpg)

**Comment by GRIM2D** [comment]
Tried <code>Starling.handleLostContext = false</code>, <code>Context3DProfile.BASELINE_CONSTRAINED</code>, <code>Context3DProfile.BASELINE</code>, <code>Context3DProfile.STANDARD</code> - no effect

**Comment by PrimaryFeather** [comment]
That's really odd, I haven't heard of such a problem before.
In your game, are you using any special display objects (any extensions or custom render methods)?

Could you create a minimal demo that showcases the problem? That would surely help.

**Comment by PrimaryFeather** [comment]
Since I didn't get any more feedback, I have to close the issue. I hope you solved it! Otherwise, feel free to open the issue again, so that we can work on a solution.
