### ISSUE TITLE
Using a special version of VectorUtil.removeAt / insertAt for BitmapFont.arrangeChars

### ISSUE THREAD

**Issue by Fraggle** [Gamua/Starling-Framework#750]
Hi again,

The splice there is creating a lot of temporary vector of CharLocation.
Maybe it could be better with custom insert/remove functions?

Seb

**Comment by PrimaryFeather** [comment]
In fact, I just saw that this is a place where "splice" can be avoided very easily — with several calls of "pop"! :smile:

Thanks for the suggestion!
