### ISSUE TITLE
Button.AlphaWhenDisabled only works if setting it before disabling a button

### ISSUE THREAD

**Issue by erlendne** [Gamua/Starling-Framework#751]
Hi,

Issue and details/sourcecode in the post below. Jeff suggested I post it here aswell.

http://forum.starling-framework.org/topic/alphawhendisabled-does-nothing-in-my-android-app

**Comment by PrimaryFeather** [comment]
Indeed, I totally overlooked that!
Thanks a lot for the heads-up, @erlendne, and for taking the time to create an issue here. Cheers!
