### ISSUE TITLE
QuadBatch.renderCustom ignores mForceTinted

### ISSUE THREAD

**Issue by id-ilych** [Gamua/Starling-Framework#753]
mForceTinted that was added to improve performance by reducing state changes seems to be ignored in QuadBatch.renderCustom which is called from QuadBatch.render. Am I missing something?

**Comment by PrimaryFeather** [comment]
It does get used, but only indirectly. :wink:

When "mForceTinted" is enabled, then the [addQuad](https://github.com/Gamua/Starling-Framework/blob/master/starling/src/starling/display/QuadBatch.as#L307) and [addQuadBatch](https://github.com/Gamua/Starling-Framework/blob/master/starling/src/starling/display/QuadBatch.as#L338) methods will always set "mTinted" to true. That value is then used during rendering.

I hope that explains it! :smile:
