### ISSUE TITLE
TextField align behavior (autoSize & hAlign)

### ISSUE THREAD

**Issue by Maligan** [Gamua/Starling-Framework#761]
Greetings!

Today I swam in starling code and find one confused thing:
TextField with `autoSize != "none"` ignore `hAlign` and `vAlign` values e.g.

---
In this sample TextField 100x100 **without** autoSizing feature:
```actionscript3
var textField:TextField = new TextField(100, 100, "Hello\nStarling");
textField.border = true;
textField.hAlign = HAlign.RIGHT;
textField.vAlign = VAlign.BOTTOM;
```
Result:
![none](https://cloud.githubusercontent.com/assets/1263469/9718448/688a264e-5584-11e5-82bf-d0f10319d40e.png)

---
In this sample TextField 100x100 **with** autoSizing feautre
``` actionscript3
var textField:TextField = new TextField(100, 100, "Hello\nStarling");
textField.border = true;
textField.hAlign = HAlign.RIGHT;
textField.vAlign = VAlign.BOTTOM;

textField.autoSize = TextFieldAutoSize.NONE;			// Enable atuoSize
```
Result:
![bothdirection](https://cloud.githubusercontent.com/assets/1263469/9718453/7eee239a-5584-11e5-9554-7f2e0aee9332.png)

As you can see there is no align to right side

---
In this sample used trick: textField define bounds with *with autoSizing* and after set textField bounds to this values but *without autoSizing*
``` actionscript3
var textField:TextField = new TextField(100, 100, "Hello\nStarling");
textField.border = true;
textField.hAlign = HAlign.RIGHT;
textField.vAlign = VAlign.BOTTOM;

textField.autoSize = TextFieldAutoSize.BOTH_DIRECTIONS; // Enable autoSize for measuring
var bounds:Rectangle = textField.bounds;                // Save auto measured size
textField.width = bounds.width;                         // Use auto measured width
textField.height = bounds.height;                       // Use auto measured height
textField.autoSize = TextFieldAutoSize.NONE;            // Disable autoSize
```
Result:
![none resized](https://cloud.githubusercontent.com/assets/1263469/9718455/86bf12c8-5584-11e5-9dac-aae557d89792.png)

---

Native flash text field does not have a similar behavior, and for me this is no expected behavior (not only for me, I find [this unanswered post](http://forum.starling-framework.org/topic/setting-horizontal-autosize-forces-left-align) on starling forum)

**Comment by PrimaryFeather** [comment]
Thanks for the report!

If you look at the [documentation](link) of the `autosize` property, you'll see that this is documented:

    [...] has implications on alignment: horizontally auto-sized text will always be left-, vertically auto-sized text will always be top-aligned.

However, I admit that this was written with single-line TextFields in mind. With a single line, horizontal alignment doesn't make any sense when the TextField is automatically sized to the width of the text.

Multiple lines, however, change that. As your sample shows, alignment does matter here. I think this should be easy to solve on Starling's side — I'll try it out and get back to you when I know more.

Thanks for pointing me at that problem!

**Comment by PrimaryFeather** [comment]
For TrueType fonts, it's a very easy fix; you just have to make a simple change starting in line 272:

```as3
if (isHorizontalAutoSize) width = int.MAX_VALUE;
if (isVerticalAutoSize)  height = int.MAX_VALUE;
```

But for bitmap fonts, it's a little more difficult; I'd need to move the whole autosize logic into the BitmapFont class, i.e. add a new parameter to the "BitmapFont.fillQuadBatch" method. In Starling 2.x, I'd like to change that method so that it takes something like a "TextFormat" object; I can then fix the alignment issue, as well.

Until then, I'll leave this as it is, to keep the behavior at least consistent between TTF and Bitmap fonts. But if you just need TTF in your case, it's an easy temporary fix you can make yourself (as shown above), or you stick with the workaround you posted yourself.

I hope you can live with that!

**Comment by Maligan** [comment]
Thank you for reply, Daniel!

For my purposes I override TextFIeld class and all works fine!
I make this issue to inform you about this small misbehavior =)

**Comment by PrimaryFeather** [comment]
Perfect, thanks! :smile:

**Comment by b005t3r** [comment]
Daniel, do you think you could add this things to 1.x version as well? I could really use them in my project right now :smile:

**Comment by PrimaryFeather** [comment]
Sorry, that's not so easy — as you can see in the changelist 259ca63, this was not a quick fix but a complete rewrite of text-rendering ... :wink: 

Thus, I'd rather keep this 2.0-exclusive. However, if you find a smaller fix, I might be willing to accept a pull request in the 1.8 branch. :mailbox_with_mail:
