### ISSUE TITLE
Change splice in all places to Vector.removeAt (new in AIR 19)

### ISSUE THREAD

**Issue by CrazyFlasher** [Gamua/Starling-Framework#769]
Can you?

**Comment by PrimaryFeather** [comment]
No, unfortunately that's not possible — at least not in the 1.x branch. I need to keep backwards compatibility with older AIR and Flash versions. (Starling 1.7 can be used even with Flash Player 11.4)

However, I will do that in Starling 2.0, which will require a very recent runtime version.
And even in Starling 1.x, I already removed many of the most critical occurrences of "splice" with `ArrayUtil.removeAt()`and `VectorUtil.removeXyzAt()`.

**Comment by PrimaryFeather** [comment]
Starling 2 replaces "splice" with those new methods all over the place. :smile:
