### ISSUE TITLE
Sprite's flatten() ignores/does not use QuadBatch's forceTinted 

### ISSUE THREAD

**Issue by b005t3r** [Gamua/Starling-Framework#774]
When flattening a ```Sprite```, ```forceTinted``` is not set on any of the ```QuadBatche```s created, which is effect creates too many batches. Also ```forceTinted``` is not copied when cloning a batch.

A fix is simple:
```
@@ -148,6 +148,7 @@ package starling.display
             clone.mSyncRequired = true;
             clone.blendMode = blendMode;
             clone.alpha = alpha;
+            clone.forceTinted = forceTinted;
             return clone;
         }
         
@@ -535,6 +536,10 @@ package starling.display
             var batch:QuadBatch = object as QuadBatch;
             var filter:FragmentFilter = object.filter;
 
+            var profile:String = Starling.current.profile;
+            var forceTinted:Boolean = (profile != "baselineConstrained" && profile != "baseline");
+            var newQuadBatch:QuadBatch;
+
             if (quadBatchID == -1)
             {
                 isRootObject = true;
@@ -542,8 +547,14 @@ package starling.display
                 objectAlpha = 1.0;
                 blendMode = object.blendMode;
                 ignoreCurrentFilter = true;
-                if (quadBatches.length == 0) quadBatches.push(new QuadBatch());
-                else quadBatches[0].reset();
+                if (quadBatches.length == 0) {
+                    newQuadBatch = new QuadBatch();
+                    newQuadBatch.forceTinted = forceTinted;
+                    quadBatches.push(newQuadBatch);
+                }
+                else {
+                    quadBatches[0].reset();
+                }
             }
             else
             {
@@ -614,12 +625,16 @@ package starling.display
                 }
                 
                 quadBatch = quadBatches[quadBatchID];
-                
-                if (quadBatch.isStateChange(tinted, alpha*objectAlpha, texture, 
+
+                if (quadBatch.isStateChange(tinted, alpha*objectAlpha, texture,
                                             smoothing, blendMode, numQuads))
                 {
                     quadBatchID++;
-                    if (quadBatches.length <= quadBatchID) quadBatches.push(new QuadBatch());
+                    if (quadBatches.length <= quadBatchID) {
+                        newQuadBatch = new QuadBatch();
+                        newQuadBatch.forceTinted = forceTinted;
+                        quadBatches.push(newQuadBatch);
+                    }
                     quadBatch = quadBatches[quadBatchID];
                     quadBatch.reset();
                 }
```

As a side note, I noticed that even with this fix quads with ```blendMode``` set to ```BlendMode.AUTO``` are batched on a separate batch, which makes sense (maybe sprites parent is responsible for setting the right ```blendMode```), but it would be great to, just for convenience, be able to override ```BlendMode.AUTO``` on all batched children with a mode passed to ```flatten()```, e.g.:
```as3
sprite.flatten(false, BlendMode.NORMAL);
```

**Comment by b005t3r** [comment]
Formatting is messed up and I have no idea how to fix it, sorry.

**Comment by PrimaryFeather** [comment]
I added the fix, thanks a lot for making me aware of this!

The blend mode change is not an option right now, though. I didn't have a look at the blend mode change, though — the whole flattening stuff will work differently in Starling 2.0, so it doesn't make much sense to put much effort into the old branch, regarding this issue. I hope you understand that. ;-)

**Comment by b005t3r** [comment]
Sure, thanks for the quick fix!

BTW, is there a post or something where you mention all the things which will be changed or made better in Starling 2.0? I have a couple of ideas I'd like to share, just don't know where I could do this.

**Comment by PrimaryFeather** [comment]
If you're talking about having an architecture similar to your excellent Batch Renderer, don't worry: Starling 2.0 will work very similarly. =)

As a sneak peek, here are a few of the new class names:

* VertexData
* VertexDataFormat
* IndexData
* Mesh
* MeshBatch
* IMeshBatch
* Effect
* MeshEffect

"Mesh" is going to replace "Quad" as the most basic building block, and is storing arbitrary geometry. "MeshBatch" could also be called "MeshRenderer", but I sticked "batch", since it's the same concept as in the 1.x version. An "Effect" combines shaders and buffers and does the actual rendering.

... that said: for more ideas, feel free to post them in e.g in #773!

**Comment by b005t3r** [comment]
So no more quads, but meshes with 1 or more triangles? Plus user defined vertex format? This is exactly the thing I need :+1: :-)

As for my ideas, (it's about batching and if I'm honest, I'm not sure how much of an improvement this can really be) I'll put those in the thread you provided.

**Comment by PrimaryFeather** [comment]
<blockquote>So no more quads, but meshes with 1 or more triangles? Plus user defined vertex format? This is exactly the thing I need :+1: :-)</blockquote>

Exactly! You'll probably even be able to overrule all of the default rendering and do it all yourself, even for standard objects. That's the part I'm working on right now. ;-)

Thanks, I'm looking forward to any ideas and suggestions! +1
