### ISSUE TITLE
Why not use “Worker”

### ISSUE THREAD

**Issue by liuhaitao32** [Gamua/Starling-Framework#781]
starling can be provided to the developers choose to use "Worker" . "Worker" can be used in the calculation , rendering and processing material (class AssetManager).

**Comment by PrimaryFeather** [comment]
It can't be used for rendering, unfortunately — you can't access Stage3D from a worker thread. However, there might be other uses (especially in the AssetManager, as you suggested), so it's definitely something I'd like to look into.

**Comment by PrimaryFeather** [comment]
I decided that using workers is better left to the application code, and Starling shouldn't rely on them. So I'm closing this issue.
