### ISSUE TITLE
Problem about SystemUtil.executeWhenApplicationIsActive

### ISSUE THREAD

**Issue by hejiacong** [Gamua/Starling-Framework#783]
The code in SystemUtil line 66
````javascript
private static function onActivate(event:Object):void
        {
            sApplicationActive = true;
            
            for each (var call:Array in sWaitingCalls)
                call[0].apply(null, call[1]);
            
            sWaitingCalls = [];
        }
````
if there is one call in sWaitingCalls throw exception,the code  "sWaitingCalls = []" will never reach.
When next active time,the sWaitingCalls run from the 1st call,and stop at the exception one,
next time repeat again.
add some try catch code my be better?

**Comment by PrimaryFeather** [comment]
You're right, good catch! I'll change that.
Thanks for making me aware of that!
