### ISSUE TITLE
Using Context3DBufferUsage in QuadBatch

### ISSUE THREAD

**Issue by vroad** [Gamua/Starling-Framework#784]
Even though some people saying that you won't benefit much from setting bufferUsage, I think that it's not bad to give GPU driver a hint. Would you mind adding support for it?

In my OpenFL port, I'm using STATIC_DRAW only for flattend sprites. For everything else I'm using DYNAMIC_DRAW.

**Comment by PrimaryFeather** [comment]
I'll have a look at it, thanks for the suggestion!
I know that I never saw any performance difference on my test devices, but of course this doesn't have to be the rule. Out of curiosity, did you find a device where this leads to better performance?

**Comment by vroad** [comment]
No, I haven't found one yet.
This may not have much meaning on mobile devices, which uses unified memory architecture.
Adobe AIR for Android uses client side array and does not use VBO. I saw this with Adreno Profiler.
OpenFL implementation uses VBO for all platforms though.

On deskop computers with dedicated video memory, setting this may have effect on caching or memory allocation, but I'm not sure. I couldn't find any document which describes what GPU driver actually does based on this.
Even if that is true, that may not improve performance noticeably in most cases.

**Comment by PrimaryFeather** [comment]
Fixed with #844.
