### ISSUE TITLE
Utility function: insertIntAt

### ISSUE THREAD

**Issue by ylazy** [Gamua/Starling-Framework#786]
Hi! I have just download the framework. In the class VectorUtil, I see this function:
```
/** Inserts a value into the 'int'-Vector at the specified index. Supports negative
         *  indices (counting from the end); gaps will be filled up with zeroes. */
        public static function insertIntAt(vector:Vector.<int>, index:int, value:uint):void
```

I think the third param should be: value:int instead of value:uint
Did I miss something?

**Comment by PrimaryFeather** [comment]
Good catch! Indeed, that was nonsense. Typical copy-paste error, I guess. :wink:
I fixed it right away, thanks a lot for the heads-up!
