### ISSUE TITLE
Memory Leak in Scaffold project

### ISSUE THREAD

**Issue by subdan** [Gamua/Starling-Framework#788]
I've compiled and run “Scaffold Mobile” app. Every several seconds memory increase by 0.1. Why it happens? 
When I started the app:
![Image](http://subdan.ru/work/85.png)
After several minutes:
![Image](http://subdan.ru/work/116.png)

**Comment by TranzRail** [comment]
I have this very issue with an app I'm developing. Can a developer look into this and report back please?

For reference, I'm publishing with latest AIR SDK and Starling, and my assets are being played using the Starling GAF Player (http://gafmedia.com/).

**Comment by PrimaryFeather** [comment]
The "MEM" information in the statistics display is a little misleading, unfortunately. It uses "System.totalMemory", which is not ideal. In ActionScript, you're often working with temporary objects that add up until the garbage collector finds it's a good time to clean up. When that happens, the memory consumption will drop again.

Starling does its best to create as few temporary objects at runtime as possible. Still, a few things will always be there, e.g. Flash's "EnterFrameEvent" or the string concatenations necessary to create the stats display. 

If you notice that memory grows and does not shrink again when the garbage collector is starting to work, analyze your app with Scout. It will show you exactly which objects are allocated in which moment. Then you can work on that step by step.

**Comment by TranzRail** [comment]
I'm aware of the above (thanks for the reminder). However, this was "less" of an issue on AIR 17 (e.g. observing the mem usage and waiting for GC to kick in was much less noticeable). For reference, the app I'm running is a basic test app for testing my animations after they've been converted from SWF to GAF for use in Starling.

I'll look at doing a longer, heavier test with Scout and see if it becomes a real problem. If so, I'll report back with any findings.

**Comment by PrimaryFeather** [comment]
That's interesting, I hadn't heard that the GC's behavior changed with the recent releases — that's of course possible! 

Yes, it would be great if you could check it out with Scout and tell me about anything you find! There are, for sure, still some allocations in Starling that can be avoided. I'll gladly look into that. Just re-open the issue when you find something you think is worth fixing.

Thanks in advance! :smile:

**Comment by subdan** [comment]
Thanks for explanation, Daniel.

**Comment by PrimaryFeather** [comment]
You're welcome! BTW, here is a good explanation about all memory-related things going on in Starling:
http://wiki.starling-framework.org/manual/memory_optimization

Perhaps it helps!
