### ISSUE TITLE
Version 2.0 does not recover automatically after the loss of context

### ISSUE THREAD

**Issue by Klug76** [Gamua/Starling-Framework#798]
The ``handleLostContext`` property no longer exists (now always enabled?). But, after the loss of context, (for example, run any fullscreen game, e.g. Quake), app displays the message "Context3D not available! Possible reasons: wrong renderMode or missing device support" and then does not work. The ``stopWithFatalError`` function is called. Is there a way to continue the work (os - windows 7)?

**Comment by PrimaryFeather** [comment]
So, as mentioned in #799, disabling `starling.enableErrorChecking` fixed this for you, right? In that case, I'll close the issue.
