### ISSUE TITLE
Attach starling.swc to each release

### ISSUE THREAD

**Issue by honzabrecka** [Gamua/Starling-Framework#802]
Hi Daniel, I think it would be sweet if each release (https://github.com/Gamua/Starling-Framework/releases) has attached compiled swc file and list of changes. Then starling/bin/* file could be removed and gitignored. It doesn't make sense to have it as a part of the repo when it's not synced with source code. I can do if you want.

**Comment by PrimaryFeather** [comment]
I think that's an excellent idea, and that's definitely the way to go. (I think when I added the SWC file to the repository, GitHub didn't have the concept of releases you could attach something to.)

The 2.0 release is probably a good opportunity to start with that. 
Thanks for the offer, but I'll probably make that gitignore change with the release, as it's really not much trouble.

If I run into anything where some help would speed things up for me, I'll gladly get back to that offer, though!! :smile:

**Comment by PrimaryFeather** [comment]
I've integrated this a while ago via this commit: 5cf8350e788e41cfaf952a1053f1c3c963004b09
(There's now a "package" ant task that creates a zip file I'm using for the release).

Thus, I'll close this issue. Thanks again for the suggestion!
