### ISSUE TITLE
Feature Request: Inverted mask

### ISSUE THREAD

**Issue by b005t3r** [Gamua/Starling-Framework#803]
Is it possible to add something like `invertMask` property to `DisplayObject`? It would make all the pixels outside of mask visible and those under the mask not rendered. Currently it's really hard to achieve a such effect with regular masking and complex masks.

I'd like to see this in the current version and 2.0 as well, of course :smile:

**Comment by 22Round** [comment]
+1
currently have a same issue :(((

**Comment by PrimaryFeather** [comment]
So far, I have failed to get inverted masks to work in all circumstances; it's tricky as soon as you nest different masks together.

What I might be able to do is provide some kind of extension that does this — with the mentioned limitations. I just don't want to add an API to the core that just works *sometimes*.

Won't be before the 2.0 release, though! I need to get that out the door. :wink:

**Comment by b005t3r** [comment]
And when's the release planned? :)

As for the logic behind this idea, here's how I see it.

If a display object has maskInverted set, its mask and mask of all its children are inverted (black pixels drawn instead of white). Every time a child object inverts mask, pixels get switched between black and white.

So when the first mask is pushed you need to set stencil buffer's background depending on if the mask is inverted or not to black or white and draw with white or black pixels. When a new mask is pushed, you simply switch the color used to draw to stencil buffer.

Shouldn't be that complicated, but RenderSupport (and this other thing in v2.0) has to track the current stencil pixel color (which is doesn't currently).

**Comment by PrimaryFeather** [comment]
Starling 2 tracks the stencil reference value, but it's still not as easy as that, I'm afraid. You not only have to draw, you also have to *erase* the mask later, and end up with the exact same stencil buffer you had before that mask was drawn. :dizzy_face: 

The plan is to make a beta release this week!

**Comment by b005t3r** [comment]
Hmm, OK, it does sound a bit impossible :)

**Comment by matej-snivam** [comment]
+1
any updates on this one?

**Comment by PrimaryFeather** [comment]
None, at the moment, sorry! As described above, I don't think it's possible to implement this in a general way (supporting nested masks). An extension with limited capabilities might be feasible - but I haven't found the time yet to look into that. Anybody interested, keep posting, so that I can update the priority on this.

**Comment by martin3361** [comment]
+1 I also need this. Any ideas how to work it around currently?

**Comment by b005t3r** [comment]
I started thinking about it again and it really seems not only doable, but also not very different from how the masks work currently.

Currently you paint the region below the mask black when applying the mask and back white when removing it (by black I mean 1 point darker, by white I mean 1 point lighter).

Now, with inverted masks you also need to track if the state is inverted or not. If it's not, nothing changes, if it's inverted you paint black/white outside the masked region (not below it). If a child changes the inverted state you have to change it back (toggle it) when poping child's state, after you painted the buffer white.

WIth this approach whatever parts of the region are still left completely white (pixel values of 0) are painted to the back buffer, everything else is ignored.

**Comment by martin3361** [comment]
@b005t3r great, I'm not into such detail into how the Starling implementation of masks work, but can you hint how to use a such functionality? Thanks

**Comment by b005t3r** [comment]
You mean an inverred mask in your custom object? It's quite easy, just copy what Starling does, but reverse what's painted and what's not. I did this for v1.8, here's how:

```as3
    private function renderOverlay(support:RenderSupport, parentAlpha:Number):void {
        enableCutoutsMask(support);

        var oldBlendMode:String = support.blendMode;

        support.pushMatrix();
        support.transformMatrix(_overlayImage);
        support.blendMode = BlendMode.NORMAL;

        _overlayImage.render(support, parentAlpha * alpha);
        support.finishQuadBatch();

        support.popMatrix();
        support.blendMode = oldBlendMode;

        disableCutoutsMask(support);
    }

    private function enableCutoutsMask(support:RenderSupport):void {
        if(_cutoutBatch.isEmpty())
            return;

        var context:Context3D = Starling.context;
        if (context == null) return;

        support.finishQuadBatch();

        context.setStencilActions(Context3DTriangleFace.FRONT_AND_BACK, Context3DCompareMode.EQUAL, Context3DStencilAction.INCREMENT_SATURATE);

        _cutoutBatch.render(support, 0.0);
        support.finishQuadBatch();

        context.setStencilReferenceValue(1);
        context.setStencilActions(Context3DTriangleFace.FRONT_AND_BACK, Context3DCompareMode.NOT_EQUAL, Context3DStencilAction.KEEP);
    }

    private function disableCutoutsMask(support:RenderSupport):void {
        if(_cutoutBatch.isEmpty())
            return;

        var context:Context3D = Starling.context;
        if (context == null) return;

        support.finishQuadBatch();

        context.setStencilActions(Context3DTriangleFace.FRONT_AND_BACK, Context3DCompareMode.EQUAL, Context3DStencilAction.DECREMENT_SATURATE);

        _cutoutBatch.render(support, 0.0);
        support.finishQuadBatch();

        context.setStencilReferenceValue(0);
        context.setStencilActions(Context3DTriangleFace.FRONT_AND_BACK, Context3DCompareMode.EQUAL, Context3DStencilAction.KEEP);
    }
```

**Comment by martin3361** [comment]
@PrimaryFeather can you consider putting this into your next commit, please? Thanks

**Comment by b005t3r** [comment]
@martin3361, this is NOT a remedy for this problem, but if you inverted masks for just one object, you can do it like so.

**Comment by matej-snivam** [comment]
You can paint quads of your objects on render texture with BlendMode.ERASE than make an image with texture mask extension and you use that as mask. It works pretty good actually. I can post an example of you need 

Matej

**Comment by martin3361** [comment]
@matej-snivam can I ask for example, please? Thanks

**Comment by PrimaryFeather** [comment]
@b005t3r 

> if it's inverted you paint black/white outside the masked region (not below it).

If I remember correctly, that's exactly the problem: you can't draw _outside_ the masked region. All you can do is define what happens in the pixel buffer _inside_ that region when you're drawing.

Admittedly, I'm not exactly into the topic right now, but I think that was part of what made a general solution not possible / thinkable.

**Comment by b005t3r** [comment]
Hmm, you might be right, I don't see a way of drawing it this way :/

However, this doesn't make it impossible, just the solution would be less flexible. First thing that comes to my head - make possible to set the masking mode possible only on the first object with masking enabled. With standard masking, everything works as it does now. With inverted masking, you  only draw those pixel which match stencil reference value of 0. If an object tries to change the current masking mode, this is impossible and an exception has to be thrown.

**Comment by martin3361** [comment]
@b005t3r unfortunately, I use Starling 2.0 so I could not get this to work

**Comment by matej-snivam** [comment]
I can send example tomorrow. 

Matej

**Comment by matej-snivam** [comment]
https://gist.github.com/93f70b44ad1d6120237d6e595d61a2f5Here is an example. You can see that I have the line and the boxes, and I want to delete the line under the boxes. The way I do it is by drawing quad  of boxes on render texture the size of the line with BlendMode.ERASE. Than I use TextureMaskStyle to make that part empty.

**Comment by martin3361** [comment]
@matej-snivam Thanks, worked like a charm!

**Comment by PrimaryFeather** [comment]
This feature was added in Starling 2.2. Closing this issue!
