### ISSUE TITLE
Mask rendered with scissor rectangle not positioned the same as mask rendered with stencil buffer

### ISSUE THREAD

**Issue by joshtynjala** [Gamua/Starling-Framework#804]
Hi, Daniel. I think i found a bug in the mask implementation in Starling 2.0.

	var image:Image = new Image(Texture.fromEmbeddedAsset(EMBEDDED_TEXTURE));
	image.mask = new Quad(200, 200);
	//image.mask.rotation = 0.001;
	image.x = 100;
	image.y = 100;
	this.addChild(image);

If you uncomment the line that sets the rotation of the mask, the result is expected to look nearly the same. Instead, you can see that the scissor rectangle masking starts at the stage's origin, while the stencil buffer masking starts at image's origin.

**Comment by PrimaryFeather** [comment]
Damn, you're right! I'll look into it right away.

**Comment by PrimaryFeather** [comment]
Sorry for that! That should do it — I tested it with Feathers, and it seems to work fine.

**Comment by joshtynjala** [comment]
Thank you, Daniel! It appears to be working properly now.

**Comment by PrimaryFeather** [comment]
Hm, well, I was a little too quick with my commit. It works now in the standard cases, but I just found some other problems. I think I got a solution, but I'll clean it up a little more before committing it tomorrow.

**Comment by PrimaryFeather** [comment]
Okay, now it should work in all circumstances, and it's also a little more efficient before.
Fingers crossed! :wink:

**Comment by vaudevillian** [comment]
Hey,

I just wanted to add: even after the commits linked to this issue I still got the exact same error joshtynjala also had. It was noticeable that it had something to do with the screen resolution. Luckily, following commit fixed this problem: https://github.com/Gamua/Starling-Framework/commit/3e3ef8243e4d10063691aa8971143b132167686a

Just in case anyone else is currently having this problem...
