### ISSUE TITLE
Better memory management (QuadBatch.dispose())

### ISSUE THREAD

**Issue by b005t3r** [Gamua/Starling-Framework#805]
Could you change ```QuadBatch.dispose()``` this way:

```as3
public override function dispose():void
{
    Starling.current.stage3D.removeEventListener(Event.CONTEXT3D_CREATE, onContextCreated);
    destroyBuffers();
    
    if(mVertexData != null) {
        mVertexData.numVertices = 0;
        mVertexData = null;
    }
    
    if(mIndexData != null) {
        mIndexData.length = 0;
        mIndexData = null;
    }
    
    mNumQuads = 0;
    
    if (mTexture && mOwnsTexture)
        mTexture.dispose();
    
    super.dispose();
}
```

It releases VertexData and IndexData (which consume the most of the memory used by QuadBatches) even if QuadBatch itself is not released (e.g. due to a bug in Adobe's GC, like this one: http://forum.starling-framework.org/topic/bug-things-not-getting-disposed). It has no negative impact or performance or anything.

**Comment by PrimaryFeather** [comment]
Sorry for the late reply, I was busy with the 2.0 release!
I saw your post, and I'll look into it as soon as time permits!

**Comment by b005t3r** [comment]
Great, thanks!

**Comment by PrimaryFeather** [comment]
BTW, it might be slightly better in Starling 2, anyway, because of the use of ByteArrays for Index- and VertexData. I'd expect them to be much easier to handle for the garbage collector; and I'm always clearing them in the dispose method, which reduces memory consumption right away, even without GC.

**Comment by b005t3r** [comment]
You're probably right, but I'd still need it in the 1.x line - we're close to finishing a project using Starling 1.7 and it would be very risky and time consuming to switch to 2.0 now (however we probably will in the future).

**Comment by PrimaryFeather** [comment]
Yeah, I can understand that. Switching would not be a smart idea at that point in development.

**Comment by PrimaryFeather** [comment]
IonSwitz just posted a similar report in the [Starling Forum](http://forum.starling-framework.org/topic/flash-player-20-garbage-collection-problem), and he found the problem popped up beginning with AIR 20. Could you try if that's the same for you? I.e. if it happens with AIR 19, for example.

**Comment by b005t3r** [comment]
I'm using AIR 17 and the report from Adobe's forums I linked to is for an even older version (it's from 2013): https://forums.adobe.com/thread/1132161

It clearly states that Adobe's GC is somewhat broken. It can't tell if a value is a memory address (pointing to an object) or a numeric values, so everything is treated as if it was a memory address, which might led to a situation where some object will never be released by GC if some numbers "point" to these objects. So the only way to be sure an object will be released is to set its reference count to 0 (such object won't have to be marked and then swept). For QuadBatches all the memory consumed is used up by vertex and index data and these are never referenced outside QuadBatch itself, so simply setting these to null resolves a huge part of the memory usage problem.

In my project I have a lot of custom batching, so a lot of QuadBatches is created and without this fix I'm getting dangerously close to the memory limit on older iOS devices and after a longer while the app exceeds this limit easily.

Also, even if there was no bug, this is still would be a good change I think, because it simply means less marking and sweeping for the GC (because huge chunks of memory are released automatically).

**Comment by b005t3r** [comment]
So how about this change, Daniel? It can hardly break anything (maybe for people who reuse disposed objects, but they shouldn't do that anyway) and it would make my life a bit easier :)

**Comment by PrimaryFeather** [comment]
Here you are. :smile:
Sorry for the delay!

**Comment by b005t3r** [comment]
Thanks!
