### ISSUE TITLE
Skip frames if nothing has been changed

### ISSUE THREAD

**Issue by maximgavrilov** [Gamua/Starling-Framework#807]
For UI-oriented applications (especially mobile ones) it is very common to skip rendering if nothing has been changed. It is possible to add check function to Stage object and test this condition as prerequest in `Starling:render()` (together with `contextValid` check). Naive implementation (just copy-paste from `DOC:render`):

 ```
public function isNeedsRender(painter:Painter):Boolean
{
    var numChildren:int = _children.length;
    var frameID:uint = painter.frameID;
    var selfOrParentChanged:Boolean = _lastParentOrSelfChangeFrameID == frameID;
    for (var i:int=0; i<numChildren; ++i)
    {
        var child:DisplayObject = _children[i];

        if (child._hasVisibleArea)
        {
            if (selfOrParentChanged)
                child._lastParentOrSelfChangeFrameID = frameID;

            if (child._lastParentOrSelfChangeFrameID != frameID &&
                    child._lastChildChangeFrameID != frameID &&
                    child._tokenFrameID == frameID - 1)
            {
                // cache
            }
            else
            {
                return true;
            }
        }
    }
    return false;
}
```

**Comment by PrimaryFeather** [comment]
Ah, you mean that you just keep the back buffer as it is if there's not a single change on the stage, right? Great idea, thanks!! That will definitely be added. :smile:

**Comment by maximgavrilov** [comment]
Yes, it seems that even enough just:
```
public function isNeedsRender(painter:Painter):Boolean
{
    var frameID:uint = painter.frameID;
    return _lastParentOrSelfChangeFrameID != frameID &&
                    _lastChildChangeFrameID != frameID &&
                    _tokenFrameID == frameID - 1;
}
```

And at `Starling:render()`:
```
if (!contextValid || !_stage.isNeedsRender(_painter))  
    return;
```

**Comment by Klug76** [comment]
It would be nice if any game can switch to this mode at run-time, for example if a user open the menu.

**Comment by PrimaryFeather** [comment]
This should now work automatically, if you opt into the feature! Be sure to read my commit notes about some details, though. :smile:

**Comment by PrimaryFeather** [comment]
@maximgavrilov I just want to thank you again for this great suggestion — this turned out to be my (and many other's) favorite feature of Starling 2. :smile:
