### ISSUE TITLE
Error #3646: AGAL validation failed

### ISSUE THREAD

**Issue by TROTech** [Gamua/Starling-Framework#812]
Hi Daniel,

The latest commit (b9fb909, March 15), produces the following error when I build.

> [Fault] exception, information=Error: Error #3646: AGAL validation failed: Can not read from output register for source operand 1 at token 2 of fragment program.

Rolling back to the earlier commit (f032069, March 11), resolves the issue.

**Comment by PrimaryFeather** [comment]
Thanks a lot for making me aware of this! I overlooked that yesterday. It's now fixed!
