### ISSUE TITLE
Tween's cary over time easy to omit

### ISSUE THREAD

**Issue by b005t3r** [Gamua/Starling-Framework#814]
If you call reset() on your tween's onComplete handler and there is any carry over time left (so this tween's advanceTime() should be called again with this value), the carry over time is going to be used with the just reset tween which won't have any effect.

I think the simplest fix is to call advanceTime() with carry over time before calling onComplete or dispatching any events, but it's for some reason done otherwise.

**Comment by PrimaryFeather** [comment]
Thanks for the report! Could you please add some sample code I can use to check this out, so that I'm sure I'm understanding this right? Thanks in advance!

**Comment by b005t3r** [comment]
Sure, there you go:

```as3
var tween:Tween = new Tween(null, 5);

tween.onUpdate = function():void { trace("onUpdate"); };
tween.onComplete = function():void { trace("onComplete"); tween.reset(null, 5); };
```

After "onComplete" is traced, "onUpdate" won't be traced and the carry over time will be carried over to the reset tween (so the "new" tween will be advanced a bit).

**Comment by PrimaryFeather** [comment]
Fixed both in 1.8 and the master branch. Thanks again for the report! :smile:

**Comment by b005t3r** [comment]
Not sure it this is "the fix" :)

I think the problem is that onComplete is called too soon, it should be called after carry over time is resolved. Your fix fixes the symptoms, but I'm not sure if it fixes the problem.

**Comment by PrimaryFeather** [comment]
Why do you mean that onComplete is called too soon? It's called exactly when "currentTime" has reached the maximum. When there's a carry-over time in that state, it must be ignored, since the tween is  finished.

Or am I overlooking something?

**Comment by PrimaryFeather** [comment]
E.g. think of a tween that has a duration of one second. When I advance it by "1.1" (as in the unit test I updated), the tween must call "onComplete" and then stop. Would I create a new tween (instead of reset the old) and add that to a juggler, it would react just the same.

**Comment by b005t3r** [comment]
Ah, OK, I thought that when there's a carry over time the tween should still execute at least once before it finishes.

**Comment by PrimaryFeather** [comment]
Ah, I see! No, there's no use in that. The tween can safely stop right away. :smile:
