### ISSUE TITLE
Hand cursor stick after a tween and removeChild()

### ISSUE THREAD

**Issue by ANVoevodin** [Gamua/Starling-Framework#815]
Hi. Example:
```as3
var _sprite:Sprite = new Sprite();
var _quad:Quad = new Quad(100, 100, 0x000000);
_quad.useHandCursor = true;
_sprite.addChild(_quad);
_stage.addChild(_sprite);
_quad.addEventListener(TouchEvent.TOUCH, function (e:TouchEvent):void {
	if (e.getTouch(_quad, TouchPhase.ENDED)) {
		Starling.juggler.tween(_sprite, 0.5, { alpha:0, onComplete:function ():void {
			_stage.removeChild(_sprite);
		}});
	}
});
```
When "_stage.removeChild(_sprite);" is done, a hand cursor stick! In above case after "removeChild" if I move a cursor then it gets arrow, but in my project it stays "hand" for ever.
Starling 2.0

**Comment by PrimaryFeather** [comment]
With "forever", you mean until the mouse cursor is moved again, right?

At least that's what happens in my tests: when the quad is removed, the hand cursors stays, but as soon as I move the mouse one pixel, the normal cursor is restored. Is that different to the result you receive?

**Comment by ANVoevodin** [comment]
I have the same result BUT in my example only. I have real game where the hand cursor still stays. The normal cursor is restored when I move the cursor over another object with useHandCursor. So, I think these "problems" are similar and if I'll solve the problem from example then the problem from my game will be solved too :). It is solvable issue?
Sorry for my English))

**Comment by PrimaryFeather** [comment]
In Starling, changes to the mouse cursor only happen when the cursor is actually moving; not when something below it changes. That's not optimal, but I didn't find an inexpensive (read: fast) way to do that dynamically.

So the behavior I described (and that's visible in the demo) is expected — but what's happening in your app is definitely not. However, I'd need some way to reproduce the error in a standalone sample to be able to fix that. So if you find out what triggers the problem, I'll do all I can to fix it. Yeah, I know: it's probably not going to be easy to find the exact set of circumstances — but thanks in advance for trying!!

**Comment by PrimaryFeather** [comment]
I'll close this issue for now — but if you find a way to reproduce it, please just open it up again, and I'll look into it!
