### ISSUE TITLE
TextField inheritance in Starling 2.0

### ISSUE THREAD

**Issue by Maligan** [Gamua/Starling-Framework#817]
Hi, Daniel!

For my purpose I inherit `starling.text.TextField` by custom class and I faced such problem:
I can't find simple way to inject my code before/after `recompose()` method:

All `_requiresRecomposition`, `setRequiresRecomposition`, `recompose` are private and
- I can't identify is TextFiled invalidated or not.
- I can't create my own flags.
- I can't inoke my code directly from recompose method.

Only way I can find without override all public setters is call `setRequiresRecomposition` each time after `setRequiresRedraw`, but this is poor solution.

Can you add/change some protected API for this purpose?

**Comment by PrimaryFeather** [comment]
Yes, `setRequiresRecomposition` should actually be protected — that's an error on my side. Is it enough for your purposes if I change that, or do you need more access?

**Comment by Maligan** [comment]
Yes, it will be enough.
Thank you for fast reply!

**Comment by PrimaryFeather** [comment]
Here you go! Let me know if you run into anything else. As you probably noticed, the TextField was changed quite a bit since Starling 1.8, so I'm happy about any code reviews. :wink:
