### ISSUE TITLE
TextField with bitmap font doesn't work with style

### ISSUE THREAD

**Issue by yuhengh** [Gamua/Starling-Framework#819]
In Starling 2.0, the custom style has no effect on the bitmap font.

var textField:TextField = new TextField(200, 100, "TextField", new TextFormat("mini", 20, 0xff0000));
textField.style = new ColorOffsetStyle(0.5, 0.5, 0.5);

**Comment by PrimaryFeather** [comment]
Ooops! It seems that was untested. :wink:
Now it should work — thanks a lot for the heads-up!
