### ISSUE TITLE
TextField change autoSize bug in Starling 2.0

### ISSUE THREAD

**Issue by Maligan** [Gamua/Starling-Framework#820]
Hi Daniel, again!

I continue my code diving into amazing Starling 2.0 text engine code, and find interesting bug:
Values of `_meshBatch.x / _meshBatch.y` is changed within `updateText()` method, if used auto sizing.
But if text field doesn't use auto size `_meshBatch` position doesn't reset to zero.

You can catch missing text with next code:

```as3
var textFiled:TextField = new TextField(200, 200, "Hello World");
textFiled.border = true;
textFiled.autoSize = TextFieldAutoSize.HORIZONTAL;

// Use timeout - textField must be composed once
setTimeout(function():void
{
	textFiled.autoSize = TextFieldAutoSize.NONE
}, 1000);
```

After one second - you gain empty text filed, because `_meshBatch` has bad position

**Comment by PrimaryFeather** [comment]
A very good find, thanks a lot! I fixed that right away. :smile:

**Comment by Maligan** [comment]
Oops... This is not enough :-)

What  about reset position only in one dimension?
For example, if changes from `BOTH` to `HORIZONTAL`

**Comment by PrimaryFeather** [comment]
Oh my, yes, I see what you mean. Ooops! :wink:
I'll provide a fix asap.

**Comment by PrimaryFeather** [comment]
This time, it's just always reset to `0, 0` before doing anything with it. That should do it. Thanks again! :smile:
