### ISSUE TITLE
Distance field fonts

### ISSUE THREAD

**Issue by henke37** [Gamua/Starling-Framework#828]
As @PrimaryFeather mentioned on #374, Starling might be getting distance field fonts as per [the Valve paper](http://valvesoftware.com/publications/2007/SIGGRAPH2007_AlphaTestedMagnification.pdf).

Might as well formally track this in case @PrimaryFeather has a memory failure.

**Comment by PrimaryFeather** [comment]
Implemented with 8fc325f!

**Comment by subdan** [comment]
Hello, Daniel. Do you plan to implement the support of multi-channel signed distance field?
https://github.com/Chlumsky/msdfgen
http://computergraphics.stackexchange.com/questions/306/sharp-corners-with-signed-distance-fields-fonts/2151#2151

**Comment by PrimaryFeather** [comment]
Yes, I discovered this recently, and I think this would be a great addition! Especially because, if I read this correctly, it's not very much effort on the shader-side to have this added. Thanks for bringing it up, I'll definitely look into it!

**Comment by subdan** [comment]
Great to hear that!

**Comment by subdan** [comment]
Hello, Daniel. Do you have any news about support of multi-channel signed distance field?

**Comment by PrimaryFeather** [comment]
I was really busy with getting the Starling Handbook ready during the last weeks. But that's now soon going to be finished, and then I can look into this — finally! Thanks for the reminder.

**Comment by subdan** [comment]
Cool! I'll be waiting for the book and this feature.

**Comment by soimy** [comment]
@PrimaryFeather Do we have MSDF support now? I'm trying to extend this [msdfgen-bmfont](https://github.com/Jam3/msdf-bmfont) to generate MSDF/SDF .fnt and .png from ttf fonts.

**Comment by PrimaryFeather** [comment]
Not yet, sorry! I just added a new issue for this so that it's easier to vote for it (and so that I can't overlook it :wink:). → #994

**Comment by PrimaryFeather** [comment]
I just added support for MSDF, and it's working great! It would be great of some of you could give it a test run. :smile:

For more information, see #994.

**Comment by subdan** [comment]
Great to hear that! Thanks, Daniel. I'll try this feature and get back to you with the results.

**Comment by subdan** [comment]
Daniel, how to correctly set softness and threshold for DistanceFieldStyle? I generated msdf font and it looks very pixelated.
![screen shot 2017-08-26 at 19 34 59](https://user-images.githubusercontent.com/410293/29743223-ae13959a-8a95-11e7-8fdf-e12849c0570c.png)

**Comment by PrimaryFeather** [comment]
Thanks for trying it out!

The constructor of the _DistanceFieldStyle_ contains arguments to control softness and threshold. Have you tried a higher value for `softness`? (`threshold` is best left at `0.5`).

**Comment by subdan** [comment]
Yes, I set softness to 1/distance-range and now it looks better.

**Comment by subdan** [comment]
My question is: how to calculate correct “softness” value?

**Comment by PrimaryFeather** [comment]
Actually, `1.0 / distance-range` should be perfect! With that set, Starling will make sure that it keeps the same crispness, no matter the scale of the object.

**Comment by subdan** [comment]
I generated Arial Regular msdf font. I want to render this font with small font size. “distanceRange” for this font = 3. But when I set softness=1/3 text looks pixelated.
![1_3](https://user-images.githubusercontent.com/410293/29743826-b32b2870-8aa1-11e7-9d9d-2265664bbe27.png)
I set sofness to 1 and text looks better.
![1](https://user-images.githubusercontent.com/410293/29743833-c50f9ff8-8aa1-11e7-90b4-2d136009b423.png)

**Comment by PrimaryFeather** [comment]
I'd like to try that out myself! Could you tell me the exact command line arguments you used when creating that texture?

**Comment by subdan** [comment]
`msdf-bmfont --reuse -o ~/Downloads/atlas.png -m 512,256 -s 42 -r 3 -p 1 -t msdf ~/Downloads/Arial.ttf -f fnt`

**Comment by PrimaryFeather** [comment]
Mhm, it seems that the spread (or distance range) is sometimes a little smaller than the requested "3". I guess this is tool dependent. In any case, you can see that by looking at the texture that's created with `sdf` type.

In general, I recommend using a higher spread, because it gives the distance field style more pixels to work with. But either way, it seems there's a little of fine-tuning involved to figure out the optimal softness value.

**Comment by soimy** [comment]
@PrimaryFeather Not sure this will help but `distanceRange` means range from glyphs' inside fading to outside distance (Range 0-1, glyph edge's value is 0.5).  Maybe all the `spread` shall be `distanceRange / 2` ?

**Comment by PrimaryFeather** [comment]
Ah, so it's the distance from the inside to the outside — thanks for the clarification, soimy, I misunderstood that. Yes, then `spread` will be `distanceRange / 2`, and the ideal value for `smoothing` would be `2 / distanceRange`! 

In your case, @subdan, this would mean the optimal value is `2 / 3` = `0.66667`. Seems reasonable!

**Comment by PrimaryFeather** [comment]
(Deleted previous comment, since it was wrong.)

Actually, the definition of `distanceRange` seems to be exactly the same as the definition of `range`. So in your case, a softness of 1/3 is exactly the right value — BUT only if you display the font with the size you created the font with! (In your case: `42`).

Try it out: if you display your Arial with that font size (or `BitmapFont.NATIVE_SIZE`) it will look perfectly fine. You can even scale it up or down, the crispness will always stay correct.

But if you create a TextField with a font size of, say, `12`, it will look pixelated. In that case, you need to multiply by the ratio of font size and original font size, as well. (I.e. `(1.0 / 3.0) * (42.0 / 12.0)`.)

I wasn't aware of that myself — it seems I always tested with the native size. :wink:

**Comment by subdan** [comment]
Thanks, Daniel. This is exactly what I was looking for.

**Comment by subdan** [comment]
Hello, Daniel. I have issue with smoothing value again. I created MSDF font with default size 42. Next, I created TextField:

```
var tf:TextField = new TextField(300,200,"Hello");
tf.x = 30;
tf.y = 30;
tf.format = new TextFormat("Bold", 16, 0x000000,Align.LEFT);
tf.style = new DistanceFieldStyle((1.0 / 3.0) * (42.0 / 16.0));
(tf.style as DistanceFieldStyle).multiChannel = true;
addChild(tf);
```

The text looks blurry. Why?

**Comment by PrimaryFeather** [comment]
Have you tried just adding the TextField, without creating the style manually? Starling should figure out the perfect smoothing value automatically, and create the style behind the scenes.

**Comment by subdan** [comment]
```
var tf:TextField = new TextField(12,12,"100 000 ₽");
tf.autoSize = TextFieldAutoSize.BOTH_DIRECTIONS;
tf.format = new TextFormat("Bold", 16, 0x000000,Align.LEFT);
addChild(tf);
```

👎 

![screen shot 2017-09-09 at 13 48 30](https://user-images.githubusercontent.com/410293/30239447-9831fd04-9565-11e7-8c9f-a4c04ad1965b.png)

**Comment by PrimaryFeather** [comment]
Could you please upload the font files so I can see what's going on?

**Comment by subdan** [comment]
[PT_Sans_Bold.zip](https://github.com/Gamua/Starling-Framework/files/1289743/PT_Sans_Bold.zip)

**Comment by soimy** [comment]
@subdan Just took a look in your bitmap font. Please update `msdf-font-xml` to the latest version, which is `2.3.0` for now. There will be no `<distanceField>` node in the generated .fnt file earlier than `2.3.0`

**Comment by subdan** [comment]
@soimy updated to 2.3.0 but the fnt file doesn't contains distanceField node

**Comment by subdan** [comment]
@soimy How to update to 2.3.0? 
I used `npm install msdf-bmfont-xml` but `msdf-bmfont --version` returns 2.2.3

**Comment by soimy** [comment]
@subdan if you installed `msdf-bmfont-xml` globally via `npm install -g msdf-bmfont-xml`, you should use the following command to upgrade it:
```bash
npm update -g msdf-bmfont-xml
```

**Comment by subdan** [comment]
The font still looks blurry.
![screen shot 2017-09-09 at 17 40 54](https://user-images.githubusercontent.com/410293/30241131-17c4ff4c-9586-11e7-8a5f-27b828a8aa07.png)

**Comment by PrimaryFeather** [comment]
Again, @subdan, I need the bitmap font files you created to be able to look into it.

**Comment by subdan** [comment]
@PrimaryFeather I decided to use regular bitmap fonts because Feathers doesn't support MSDF fonts.

**Comment by PrimaryFeather** [comment]
I'm sure Josh will add support for this feature in the future, though. So if you've got a minute, maybe you can still send me those font files? I'd love to find out what's going on and — if possible: fix it.

Thanks a lot in advance!

**Comment by subdan** [comment]
@PrimaryFeather Ok. I will send you the files within a day.

**Comment by subdan** [comment]
I removed all my MSDF experiments. So I started again.
Now the font isn't blurry. So all is ok.

On the top — MSDF font.
On the bottom — TTF Font.
TTF font looks sharper.

![screen shot 2017-09-11 at 21 08 50](https://user-images.githubusercontent.com/410293/30290173-1e853d76-9737-11e7-85c0-c6ae7be1945a.png)

**Comment by PrimaryFeather** [comment]
Hm, that's interesting. When I render the distance field font you posted (with size `100`), it looks like this:

![screen shot 2017-09-12 at 08 53 16](https://user-images.githubusercontent.com/547347/30312060-3b6ae966-9798-11e7-8ba7-d73f9042a374.png)

Which seems just as sharp as your TTF rendering. Is there anything else going on in your demo?
I don't think the problem has to do with pixelsnapping, since that's enabled by default for all TextFields (and it should not make a difference, anyway, with distance field rendering).

**Comment by soimy** [comment]
@subdan Did you render bitmap font with feathers? It seems that josh just commit a fix on that.
BowlerHatLLC/feathers#1633

**Comment by subdan** [comment]
@soimy No, I didn't. I will check it tomorrow.

**Comment by subdan** [comment]
@PrimaryFeather I run my demo on iPhone Retina simulator in IntelliJ IDEA.

**Comment by subdan** [comment]
@soimy Seems that Josh didn't yet add support for MSDF fonts.
![screen shot 2017-09-12 at 23 40 05](https://user-images.githubusercontent.com/410293/30347227-0d1570f0-9814-11e7-8d0b-5776c0868bad.png)
The label isn't centred.

**Comment by PrimaryFeather** [comment]
@subdan Ah, the "retina" part was exactly the information I needed. Thanks, that helped me fix this problem! Please try again: a Starling TextField with a distance field font should now look just fine on a retina display.

**Comment by subdan** [comment]
Wow! Now it looks as sharp as TTF font. Thank you, Daniel!
![screen shot 2017-09-13 at 22 48 35](https://user-images.githubusercontent.com/410293/30397491-c06d9aa8-98d5-11e7-9e35-fb3e5a6b3e42.png)

**Comment by PrimaryFeather** [comment]
I'm happy to hear (and see) that! :smile:
Thanks for the update!
