### ISSUE TITLE
BitmapFont, missing characters display the font name

### ISSUE THREAD

**Issue by alamboley** [Gamua/Starling-Framework#831]
Hi Daniel,

A nicer warning: display the font name in the trace https://github.com/Gamua/Starling-Framework/blob/master/starling/src/starling/text/BitmapFont.as#L313

Sorry for not making a PR but I'm on a 1.8.x project ;-)

**Comment by PrimaryFeather** [comment]
Haha, no problem! Yes, will do! If it helps, I can also make this change in the 1.8 branch?

**Comment by alamboley** [comment]
Finally I made the PR ;) Could be useful for some people too on 1.8!
