### ISSUE TITLE
Bug in setChildIndex()

### ISSUE THREAD

**Issue by b005t3r** [Gamua/Starling-Framework#835]
I think this line: https://github.com/Gamua/Starling-Framework/blob/master/starling/src/starling/display/DisplayObjectContainer.as#L238 should be changed to something like this:

```as3
if(index < oldIndex)
     _children.insertAt(index, child);
else
     _children.insertAt(index - 1, child);
````

because the child at ```oldIndex``` was already removed and indices could change.

**Comment by PrimaryFeather** [comment]
No, this actually works as it is! As shown by this test:

```as3
var parent:Sprite = new Sprite();
var childA:Sprite = new Sprite();
var childB:Sprite = new Sprite();
var childC:Sprite = new Sprite();
var childD:Sprite = new Sprite();
var childE:Sprite = new Sprite();

parent.removeChildren();
parent.addChild(childA);
parent.addChild(childB);
parent.addChild(childC);
parent.addChild(childD);
parent.addChild(childE);

parent.setChildIndex(childD, 1);
trace(parent.getChildIndex(childD)); // -> 1

parent.removeChildren();
parent.addChild(childA);
parent.addChild(childB);
parent.addChild(childC);
parent.addChild(childD);
parent.addChild(childE);

parent.setChildIndex(childB, 3);
trace(parent.getChildIndex(childB)); // -> 3
```

The first test is clear, since the object is moved "upwards". The second test, moving the object "downwards", may look surprising, but if you think it through in your head, it works out.

**Comment by b005t3r** [comment]
Well, the thing is how is this supposed to work? :)

Because if you're changing a given object's index you want to put it between two specific objects (or before/after a specific object). In your second examples you'd want to put ```childB``` before ```childD```, but you're placing it after ```childD``` and before ```childE```.

I think it's a bit counterintuitive, but if that's how it's supposed to work, I can live with that :)

**Comment by PrimaryFeather** [comment]
> In your second examples you'd want to put childB before childD, but you're placing it after childD and before childE.

Well, what's for sure is that you want it to have index `3` afterwards, and there's simply no other way to do so! If you'd put childB before childD, it would have index `2`, would it not?

    0 1 2 3 4
    A C B D E 

The only way to let it have index `3` is this:

    0 1 2 3 4
    A C D B E

See what I mean?

**Comment by PrimaryFeather** [comment]
That said: yes, I agree that it's counter-intuitive to see where it ends up. :wink:
But it's simply the only correct way of doing it, as far as I can see!

**Comment by b005t3r** [comment]
Well, I can't imagine a real world scenario where you simply want a child to have an arbitrary index with no reason :)

I always imagined it'll end up being used like so:
```as3
parent.setChildIndex(child, parent.getChildIndex(otherChild)); // put 'child' before 'otherChild'
```

I was porting your code just recently and to be honest I dropped this method entirely (i can easily be replaced with a simple remove/addAt pair) because it wasn't clear how this should work, so I created this issue just as a heads-up. I never had to use it in my code so far.

**Comment by PrimaryFeather** [comment]
Yeah, it's definitely not a method that's used often. :wink:
I guess I just ported it over because it was in the original Flash API.

It works just like that, and (as described above) I think it's doing the correct thing; even though it might lead to confusions.
