### ISSUE TITLE
Android skipUnchangedFrames

### ISSUE THREAD

**Issue by harry248** [Gamua/Starling-Framework#836]
When skipUnchangedFrames is enabled and the app is put to the background (followed by a call to Starling.stop(true)) and back to the foreground (followed by a call to Starling.start()) only a black screen is being shown, when the stage contains only static contents. This happens only on Android (tested on a Galaxy S7 with Android 6.0.1).

Calling Starling.setRequiresRedraw immediately after Starling.start() does not work. The call has to be delayed by some ms to make it work.

Perhaps a call to Starling.start() should always result in a redraw being forced?

**Comment by PrimaryFeather** [comment]
Thanks a lot for the report! 
Yes, I'd also think that forcing a redraw whenever calling `start` is a good idea. I'll look into it!

**Comment by PrimaryFeather** [comment]
I'm now calling `setRequiresRedraw` via a 1 ms timeout, and that seems to fix the issue. It only popped up on Android; iOS, Windows and OS X didn't seem to have a problem.

It's not the most beautiful solution, but I can't think of any cleaner workaround. I guess the ACTIVATE event is just dispatched one frame too soon on Android.

In any case: please let me know if this works for you!

**Comment by PrimaryFeather** [comment]
Update: it seems this doesn't work for [all users](http://forum.starling-framework.org/topic/starling-20-black-screen-after-returning-from-background?replies=4#post-94056). Maybe I'll have to raise the timeout value — or does anybody have another idea for a workaround?

**Comment by kevinfoley** [comment]
It's very cheesy, but a simple workaround:

    setTimeout(setRequiresRedraw, 1);
    setTimeout(setRequiresRedraw, 2);

The second call will catch stragglers, and the performance cost is inconsequential (at worst, you render a couple of frames you didn't technically need to render).

**Comment by PrimaryFeather** [comment]
I decided to go with the simplest possible solution: just raising the timeout to 100ms. That's still short enough to not be noticed by a user (activation takes much more than that, anyway), but should be late enough that everything is set up for rendering.
