### ISSUE TITLE
Alpha do not work with TextField (Starling 2.0)

### ISSUE THREAD

**Issue by sjabberwocky** [Gamua/Starling-Framework#837]
You can simple create text field and change it's alpha for reproducing this issue.
```
            var title : TextField = new TextField(200, 100, "Test test test");
            title.alpha = 0.1;
            addChild(title);
```
Also you can try fadeOut with tween.

**Comment by PrimaryFeather** [comment]
Damn, it's a shame I overlooked that. :unamused: 

This will probably require a version `2.0.1` some time. But let's wait a couple more days, in case something else pops up. In any case: thanks a lot for pointing me at that!

**Comment by sjabberwocky** [comment]
Thank you for so fast fix!

**Comment by PrimaryFeather** [comment]
You're welcome! :smile:
