### ISSUE TITLE
TextField.textBounds returns wrong x/y position when autosized - Starling 2.0

### ISSUE THREAD

**Issue by timoisalive** [Gamua/Starling-Framework#840]
I'm creating a textfield with autosizing enabled and adding it on a parent. If I query the textBounds immediately after, I get funky x/y readings.

```actionscript
var tf:TextField = new TextField(100, 100, "foobar");
tf.autoSize = TextFieldAutoSize.HORIZONTAL;
addChild(tf);
trace(tf.textBounds);

tf.autoSize = TextFieldAutoSize.VERTICAL;
trace(tf.textBounds);
tf.autoSize = TextFieldAutoSize.BOTH_DIRECTIONS;
trace(tf.textBounds);
tf.autoSize = TextFieldAutoSize.NONE;
trace(tf.textBounds);

//[trace] (x=-49979, y=41, w=40.5, h=16.5)
//[trace] (x=2, y=-49984, w=35, h=31)
//[trace] (x=-49979, y=-49991, w=40.5, h=16.5)
//[trace] (x=2, y=-7, w=35, h=31)
```

**Comment by timoisalive** [comment]
This is new in Starling 2.0, forgot to mention...

**Comment by PrimaryFeather** [comment]
Thanks a lot for the report! I'm already looking into it.

**Comment by timoisalive** [comment]
Awesome, thanks Daniel! :)

**Comment by PrimaryFeather** [comment]
That should do it! Please pull and give it a try. :smile:

**Comment by timoisalive** [comment]
Nice, works perfect!

I see you had fixed another glitch meanwhile too, thanks a bunch for amazing job Daniel! 👍

**Comment by PrimaryFeather** [comment]
Wonderful, I'm glad to hear that! Thanks for the nice words! :blush:
