### ISSUE TITLE
Using stylesheets with TextField

### ISSUE THREAD

**Issue by timoisalive** [Gamua/Starling-Framework#843]
I had hacked stylesheets into TextField in Starling < 2.0, but now it's a bit more cumbersome with the text compositor.

I understand stylesheets are not for bitmap text, but are there some issues why stylesheets are not enabled for TrueTypeCompositor? After all, it shouldn't be much more than just passing the stylesheet to the native textfield instance, right?

**Comment by PrimaryFeather** [comment]
There's no specific reason for stylesheets not being part of the API yet, besides that I haven't come around to it and it wasn't requested often. :wink:

I'll look into it! Do you have any time frame when you need that feature?

**Comment by timoisalive** [comment]
I'm actually doing it myself at the moment and I probably will need it pretty soon if I end up updating the production with Starling 2.0.

Since the TextField is not really designed to be extended (which is totally fine), I need to overlay TextField, TextOptions and TrueTypeCompositor and that's of course a bit of extra work whenever pulling the latest from Starling repo...

This is what I'm doing in the TrueTypeCompositor.renderText:
```actionscript
if(options.styleSheet == null) {
	sNativeTextField.styleSheet = null;
	sNativeTextField.defaultTextFormat = sNativeFormat;
} else {
	sNativeTextField.styleSheet = options.styleSheet;
}
```
I'm passing the styleSheet in the TextOptions, and it's working otherwise, but the style sheet text renders in half size for some reason...

**Comment by timoisalive** [comment]
Update; the styleSheet works fine on mobile, but on my Mac (retina) desktop, the text renders in half size. Some kind of scale factor issue perhaps...

**Comment by PrimaryFeather** [comment]
Hm, that's interesting. Retina on Desktop unfortunately works a little different than on mobile in Stage3D, probably you're seeing the effect of such a difference. Perhaps the [pixelSize](http://doc.starling-framework.org/current/starling/rendering/Painter.html#pixelSize) property on `Starling.painter` helps.

**Comment by timoisalive** [comment]
Hi Daniel, I noticed you've got 2.1 RC out already! Any chance to push this in 2.1 anymore...?

**Comment by PrimaryFeather** [comment]
Hm, I better not add any big changes now that the RC is out — you know how it is, that's bound to go wrong! :bowtie: 

However, I can make that the first feature to implement after the 2.1 release — you could simply work with that version then, it will be just as stable as 2.1. (In general, I'm always trying to keep the head revision working, even on the master branch.)

Would that work for you? Sorry for the delay, in any case!

**Comment by timoisalive** [comment]
Sure, sounds like a good idea, and really awesome if you think it's possible right after 2.1! Cheers! :D

**Comment by PrimaryFeather** [comment]
Sorry for the long time you had to wait for this — but better late than never. :smile:
Please try out if this works for you! I tested it with HiDPI as well, and that didn't cause any problems.

**Comment by timoisalive** [comment]
Thanks Daniel a lot for this! It seems to work just like my hack, even for the scaling issue on my Mac. But that's not a problem, and it could be something in my project, so no need to worry about it for my sake at least. Thanks again! :)

**Comment by PrimaryFeather** [comment]
You're welcome! Hm, it's weird that scaling doesn't work right in your case. If it turns out it's something I can fix on my side, don't hesitate to open up this issue again and let me know!

Cheers!

**Comment by timoisalive** [comment]
It is! I'll let you know if/when I figure what's the deal with it..
