### ISSUE TITLE
Allow to specify buffer usage for an effect

### ISSUE THREAD

**Issue by Varnius** [Gamua/Starling-Framework#844]
When effect sets up its vertex/index buffers its usage always defaults to 'staticDraw'. Thus, it would be good to have appropriate arguments to specify buffer usage in Effect.uploadVertexData/Effect.uploadIndexData methods.

Something along these lines:
```actionscript
public function uploadVertexData(vertexData:VertexData, bufferUsage:String = 'staticDraw'):void
public function uploadIndexData(indexData:IndexData, bufferUsage:String = 'staticDraw'):void
```

**Comment by PrimaryFeather** [comment]
Thanks for the suggestion! I actually planned to do just that from the beginning, but I somehow overlooked it.

Please let me know if that works for you! That will be part of Starling 2.0.1, which will probably come out a little later this week.
