### ISSUE TITLE
Suggest tweaking Starling.mustAlwaysRender to ignore invisible native children

### ISSUE THREAD

**Issue by serjek** [Gamua/Starling-Framework#847]
Thing is, native stage children even with visible == false are forcing Starling.mustAlwaysRender to return true. Suggest ignore them when calculating mustAlwaysRender value.
Feather's TextInput uses native stage children for measurements thus forcing Starling to render every frame.

See this issue for details.
#https://github.com/BowlerHatLLC/feathers/issues/1340

**Comment by PrimaryFeather** [comment]
That should do it. Thanks a lot for the report!
