### ISSUE TITLE
Setting quad dimension to -1 and back to positive number causes Quad to disappear

### ISSUE THREAD

**Issue by joshtynjala** [Gamua/Starling-Framework#850]
Code to reproduce:

	var quad:Quad = new Quad(100, 100, 0xff00ff);
	this.addChild(quad);
	
	var otherQuad:Quad = new Quad(100, 20, 0x00ff00);
	otherQuad.y = 120;
	otherQuad.addEventListener(TouchEvent.TOUCH, function(event:TouchEvent):void
	{
		var touch:Touch = event.getTouch(otherQuad, TouchPhase.BEGAN);
		if(!touch)
		{
			return;
		}
		trace(quad.width, quad.height);
		if(quad.width !== 100)
		{
			quad.width = 100;
			quad.height = 100;
		}
		else
		{
			quad.width = -1;
			quad.height = -1;
		}
	});
	this.addChild(otherQuad);

Thanks, Daniel!

**Comment by PrimaryFeather** [comment]
Good find, thanks!!
