### ISSUE TITLE
Sometimes, non-loop MovieClip doesn't dispatch Event.COMPLETE

### ISSUE THREAD

**Issue by jessadacharoen** [Gamua/Starling-Framework#851]
This issue happens very often on web version of my game.

I tried printing log from advanceTime function and found that there is a chance when advanceTime function ends with the following parameter values:
_currentFrameID = finalFrameID
hasEventListener(Event.COMPLETE) = true
dispatchCompleteEvent = false
_currentTime = totalTime

When it enters advanceTime function again, it will fall into "if (_currentTime == totalTime)" condition, and then return out of the function immediately without checking for hasEventListener(Event.COMPLETE) nor trying to dispatch Event.COMPLETE. Therefore, the Event has never been dispatched.

```as3
public function advanceTime(passedTime:Number):void
{
    if (!_playing) return;

    // The tricky part in this method is that whenever a callback is executed
    // (a frame action or a 'COMPLETE' event handler), that callback might modify the clip.
    // Thus, we have to start over with the remaining time whenever that happens.

    var frame:MovieClipFrame = _frames[_currentFrameID];

    if (_wasStopped)
    {
        // if the clip was stopped and started again,
        // sound and action of this frame need to be repeated.

        _wasStopped = false;
        frame.playSound(_soundTransform);

        if (frame.action != null)
        {
            frame.executeAction(this, _currentFrameID);
            advanceTime(passedTime);
            return;
        }
    }

    if (_currentTime == totalTime)
    {
        if (_loop)
        {
            _currentTime = 0.0;
            _currentFrameID = 0;
            frame = _frames[0];
            frame.playSound(_soundTransform);
            texture = frame.texture;

            if (frame.action != null)
            {
                frame.executeAction(this, _currentFrameID);
                advanceTime(passedTime);
                return;
            }
        }
        else return; // Here it returns without dispatching Event.COMPLETE
    }

    var finalFrameID:int = _frames.length - 1;
    var restTimeInFrame:Number = frame.duration - _currentTime + frame.startTime;
    var dispatchCompleteEvent:Boolean = false;
    var frameAction:Function = null;
    var previousFrameID:int = _currentFrameID;
    var changedFrame:Boolean;

    while (passedTime >= restTimeInFrame)
    {
        changedFrame = false;
        passedTime -= restTimeInFrame;
        _currentTime = frame.startTime + frame.duration;

        if (_currentFrameID == finalFrameID)
        {
            if (hasEventListener(Event.COMPLETE))
            {
                dispatchCompleteEvent = true;
            }
            else if (_loop)
            {
                _currentTime = 0;
                _currentFrameID = 0;
                changedFrame = true;
            }
            else return;
        }
        else
        {
            _currentFrameID += 1;
            changedFrame = true;
        }

        frame = _frames[_currentFrameID];
        frameAction = frame.action;

        if (changedFrame)
            frame.playSound(_soundTransform);

        if (dispatchCompleteEvent)
        {
            texture = frame.texture;
            dispatchEventWith(Event.COMPLETE);
            advanceTime(passedTime);
            return;
        }
        else if (frameAction != null)
        {
            texture = frame.texture;
            frame.executeAction(this, _currentFrameID);
            advanceTime(passedTime);
            return;
        }

        restTimeInFrame = frame.duration;
    }

    if (previousFrameID != _currentFrameID)
        texture = _frames[_currentFrameID].texture;

    _currentTime += passedTime;

    // I log all parameters here
}
```

**Comment by PrimaryFeather** [comment]
Thanks a lot for the report!

If you can reproduce this locally, what would help most is the following:

* Tell me the number of frames and frameRate you're using.
* Are there any other special conditions in your clip? (A frame action, a custom frame duration, etc.)
* Log the "advanceTime" steps that MovieClip is going through until the error appears.

That way, I should be able to reproduce the problem. I've tried, but I couldn't come up with the correct set-up yet. Thanks a lot in advance!

**Comment by PrimaryFeather** [comment]
One more thing: you're not setting `currentTime` to a specific value somewhere else in your code, right? Because if you set that to the length of the movie, no event will be dispatched; that happens only when the `totalTime` is passed from `advanceTime()`.

**Comment by jessadacharoen** [comment]
No, I'm not setting cerrentTime. I tried printing log in currentTime set function too, just in case, saw nothing enters in there.

frameRate is 30 fps. No frame action. No custom frame duration. They aren't looping.

Note that I can't reproduce this on simulator yet, it only happens on .swf playing by Flash Player on Facebook canvas.

I log additional values for you,

before while loop:
passedTime = 0.03499999999999659
restTimeInFrame = 0.0016666666666632635
_currentTime = 0.9650000000000034

last line in while loop:
passedTime = 0.033333333333333326
_currentTime = 0.9666666666666667
before _currentTime += passedTime:
passedTime = 0.033333333333333326
_currentTime = 0.9666666666666667

last line in the function:
_currentTime = 1
totalTime = 1
_currentFrameID = 29
finalFrameID = 29
dispatchCompleteEvent = false

**Comment by PrimaryFeather** [comment]
Thanks a lot — that information was exactly what I needed. I'd never have managed to reproduce this problem without that information; it's a floating point issue that's really mean. I added a workaround that will fix the issue.

Thanks a lot for the report and your help reproducing the issue!
