### ISSUE TITLE
Show GPU memory in StatsDisplay

### ISSUE THREAD

**Issue by henke37** [Gamua/Starling-Framework#864]
While it's hardly the fancy feature I asked for, the new ability to track gpu memory consumption at all allows basic profiling by checking the total memory use.

**Comment by PrimaryFeather** [comment]
Yes, that's definitely coming.
One thing I didn't find a nice solution for yet is the naming of the indictors. Right now, it's a simple FPS, MEM, DRW; but what should I add for GPU memory? Perhaps somebody else has an idea. I'd love to be able to keep it small and concise.

Otherwise, I'll have to expand all of them to longer words.

**Comment by kheftel** [comment]
GRAM? GMEM?

**Comment by PrimaryFeather** [comment]
Yes, something like that - I'll probably not be able to keep all of them just 3 letters. Probably "MEM" and "GMEM". Thanks, Kawika!

**Comment by kheftel** [comment]
I suppose "GRM" or "GPU" or "GME" or "GMM" is possible but none of those
seem intuitive to me

**Comment by PrimaryFeather** [comment]
Yeah, that's not self-documenting. Perhaps I should just make all of them longer - wouldn't hurt to have a little more clarity.

**Comment by henke37** [comment]
WRAM and VRAM?

**Comment by kheftel** [comment]
What does the W in WRAM stand for?

**Comment by henke37** [comment]
It's Video ram and Working ram

**Comment by kheftel** [comment]
ah. makes sense now that you explain it :)

**Comment by PrimaryFeather** [comment]
Finally, I got around to doing this! Sorry for the long wait.
Here's what it looks like now:

![statsDisplay](https://cloud.githubusercontent.com/assets/547347/17026909/0c14300c-4f62-11e6-9107-7da782f37918.png)
