### ISSUE TITLE
Painter.drawFromCache but BatchProcessor._batches is empty

### ISSUE THREAD

**Issue by fangwy** [Gamua/Starling-Framework#867]
![cache](https://cloud.githubusercontent.com/assets/19532592/15471969/563577e6-212b-11e6-8234-19495ba51136.png)

**Comment by PrimaryFeather** [comment]
Thanks for creating the ticket!

I do believe you that this is happening; there must be a specific situation that causes this problem, that I didn't anticipate. However, from the call stack alone, I can't reproduce the problem. 

I have to ask to you try to dig deeper and find out what exactly you are doing that's triggering the error. Ideally, I'd need a minimal sample code that I can start on my development machine and get the same exception. That's the only way I can solve this.

Thanks a lot in advance!

**Comment by vaudevillian** [comment]
Hi everyone,

this sounds very familiar to me. In my case, it was resolved by this: http://forum.starling-framework.org/topic/multiple-starling-instances-the-painterframeid?replies=1#post-93053

Maybe have a look at this, fangwy

**Comment by PrimaryFeather** [comment]
Ah, you're right! That brought up exactly that error — thanks, vaudevillian!
In that case, fangwy, you'd just have to update to the head revision.

**Comment by fangwy** [comment]
Hi Daniel,
update to the head revision，fixed the problem. Thank you!

**Comment by PrimaryFeather** [comment]
That's great news! :smile:
