### ISSUE TITLE
MeshBatch bug(?)

### ISSUE THREAD

**Issue by deCompany** [Gamua/Starling-Framework#868]
From this post on the forum: [http://forum.starling-framework.org/topic/strange-issue-bug-with-meshbatch](url)
Briefly: meshBatch is not being redrawn with starling.showStats turned off.

Sorry, I'm very new here so I cannot figure out how do I attach an archived project files. Here is a link to a cloud storage: [https://cloud.mail.ru/public/nnpp/uBTXVMWP3](url) (it's a blue button under the big yellow zip icon). Please watch the comments in both .as files (showStats thing on Main.as and _meshBatch.clear() on TestScene.as).

I am not sure if it is a bug or is it me doing meshBatching the wrong way - just wanted to let you know that such a behaviour is possible.

ps sorry, the links seem not to work too so please copy/paste the url )

**Comment by PrimaryFeather** [comment]
Thanks a lot for creating the ticket! I'll have a look at your sample and will report back when I know more.
BTW, there's no way to attach a file directly here, so a link to cloud storage is fine. :)

**Comment by PrimaryFeather** [comment]
That should do it! Thanks again for the report. 
Please try it out and let me know if this fixes the problem for you! :smile:

**Comment by deCompany** [comment]
Daniel, I am sorry but what do I do to try it? ) Is it starling.swc from "The latest release" here (v2.0.1) that has this fix? If so it seems like nothing changed - no redraws without showStats=true and no everyframe redraws.
If not please tell me where do I find it.

**Comment by PrimaryFeather** [comment]
Ah, no, the SWC is only updated for a release, not during normal development.
So you have to download and compile the latest source manually. 

My recommendation: set up "git" on your development machine and do a "git clone" on the Starling repository. Once that's done, you can update to the latest starling version anytime via a simple `git pull`. Instead of linking to the `starling.swc` file, just add the source path to Starling to your app.

**Comment by deCompany** [comment]
Sorry, Daniel, I cannot make the whole construction running ) I am a graphic designer and have little experience in programming. Hope it all works great with the mentioned fix so we'll see it with the next release version.
Many thanks for your work on Starling!

**Comment by PrimaryFeather** [comment]
Okay, don't lose any more time on it, then — I tested the fix with your sample and I'm optimistic that I found the real issue behind your problem. I'll probably make a "2.0.2" release in a while, and the problem should go away then, when you upgrade.

Again, thanks for your help! :-)
