### ISSUE TITLE
2 weird unicode characters in source code

### ISSUE THREAD

**Issue by SlavomirDurej** [Gamua/Starling-Framework#876]
When importing Starling from github I always get these 2 errors in the source code due to this weird " Â  "character in the code for Sprite3D:

![image](https://cloud.githubusercontent.com/assets/4057817/15852764/5a0039a4-2c9a-11e6-89e9-d81f4751e052.png)

and in starling.display.DisplayObject:

![image](https://cloud.githubusercontent.com/assets/4057817/15852818/7d1fd16a-2c9a-11e6-9a73-fa01857d8988.png)

this breaks the compiler (at least for me, but perhaps other users have the same issue).

It's easy enough to delete it from both of these places, but I have to do this each time I import new version of Starling..

If it's not too much trouble , would you mind deleting it?

**Comment by JohnBlackburne** [comment]
It does not break it for me but I had a look and they are non-break spaces instead of normal ASCII spaces, which are rather redundant in source code.

**Comment by PrimaryFeather** [comment]
Weird, I have no idea how those ended up in the code. I replaced them with conventional spaces — please check if that fixes your warnings!

Thanks a lot for the report. :smile:

**Comment by SlavomirDurej** [comment]
all looks good now Daniel, thanks for fixing!

**Comment by PrimaryFeather** [comment]
Perfect! You're welcome! :smile:
