### ISSUE TITLE
Sprite3d and mask works unpredictable

### ISSUE THREAD

**Issue by rzer** [Gamua/Starling-Framework#880]
When you apply mask on Sprite3d everything is fine before you use rotationX, rotationY property. In some cases (combinations of parent positions) it works fine, in others clipRect moved right, and down.

Example with bug: https://www.dropbox.com/s/njx5d7fewqqwny6/TestStarling.zip?dl=0

**Comment by PrimaryFeather** [comment]
Good catch! Please give it a try with the new version — I hope I've got all combinations of 3D and non 3D masks covered now.

**Comment by rzer** [comment]
Now it's works perfect. Thanks for your work Daniel!

**Comment by PrimaryFeather** [comment]
You're welcome! I'm glad I could help! :smile:
