### ISSUE TITLE
TextField#style property get/set is inconsistent

### ISSUE THREAD

**Issue by Maligan** [Gamua/Starling-Framework#897]
Houston, we have a small problem:

```as3
var textField:TextField = new TextField(...)
textField.style = new DistanceFieldStyle();
DistanceFieldStyle(textField.style); // Type Coercion failed: cannot convert MeshStyle to DistanceFieldStyle.
```

**Comment by PrimaryFeather** [comment]
Thanks for the report! I can reproduce the error — expect a fix next week.

**Comment by PrimaryFeather** [comment]
That should do it. Along the way, I found another problem (19a20cb122970927b5e91b4a20d9f9cf4ddc0b25), thus the delay. 

Please let me know if that works for you!
