### ISSUE TITLE
Add autoSize to TextOptions

### ISSUE THREAD

**Issue by neuronix** [Gamua/Starling-Framework#903]
Custom TextCompositors may require knowing if the textfield has autoSize enabled. One can cheat and look at height == 10000 but that's dirty.

TextOptions seems to have been made for this, so autoSize should be added to the list of values.

Thanks Daniel!

**Comment by PrimaryFeather** [comment]
Actually, the original idea was to simplify the life of the developer writing a custom compositor; that he wouldn't need to care about "autoSize", but have that handled by the TextField itself.

But I already saw this idea fail when it came to HTML fonts, which can be aligned on both sides (and thus, crippling any post-autosize logic).

I guess you ran into something similar?

**Comment by neuronix** [comment]
My initial implementation of TLFCompositor used TLFTextField which renders beautifully but is horribly slow (especially when using autoScale extensively). So I made a new version based on the old TLFSprite extension but it requires a few extra adjustments and workarounds.

**Comment by PrimaryFeather** [comment]
I see, thanks for the additional information! I'll look into it. 👍

**Comment by PrimaryFeather** [comment]
That should do it! Please let me know if that works for you.

**Comment by neuronix** [comment]
Looks great, thanks Daniel! :)
