### ISSUE TITLE
Bad performance, low fps on some PC in Chrome web browser

### ISSUE THREAD

**Issue by kolobok55** [Gamua/Starling-Framework#929]
We have an game in different social network wrotten with Starling, but in some cases (don't know why) in same Chrome browser version and flash player has different fps. 
The problem can repeated with this link app
http://ycanvas.yoz.sk/maps/
On my notebook in Chrome it has 4 fps, but in Mozilla 60 fps.
I have seen this problem on the forum from 2014, but did not see solutions

**Comment by PrimaryFeather** [comment]
When you log the output of `Starling.context.driverInfo` on such a device, what's your result? Such a big difference in FPS would indicate that it's running in software mode for some reason.

**Comment by PrimaryFeather** [comment]
I just realized that with the lastest Chrome version, hardware acceleration was disabled on my 2011 MacBook Air as well — for whatever reason, they must have put it on a blacklist.

However, that was easily changed with the instructions from this stackoverflow thread:
http://apple.stackexchange.com/questions/150212/hardware-acceleration-for-flash-videos-in-google-chrome

Does that help in your case, too?

**Comment by PrimaryFeather** [comment]
Any news on this?

**Comment by IevotechAlexanderDorokhov** [comment]
Yeap, I have news: Windows 7 + Chrome PPAPI player (release & debug)  = very bad performance. 
Scout says that Context3D.setProgram(); execution is 90% of buget... So, it is not a Starling issue.

**Comment by kolobok55** [comment]
We think, that problem in chrome: in some cases disabled gpu acceleration. Watch the performance in Adobe Scout, more than 50% time lost in Starling "Render" -> Stage3d. In mobile version even with antialiasing = 16 is perfect performance.

**Comment by PrimaryFeather** [comment]
Since I haven't heard any news about Chrome performance issues for a while, I'll close this issue now.
