### ISSUE TITLE
QuadBatch null pointer exception

### ISSUE THREAD

**Issue by greymag** [Gamua/Starling-Framework#937]
There is a problem In branch `origin/v1.8.x` after replace Starling event with conventional in `QuadBatch`.
Now, if someone dispose `QuadBatch` in it's own context created listener, then `QuadBatch` will thrown 1009 error in `createBuffers()` (called from `onContextCreated`). Thats because `removeEventListener()` are not remove event listener while handle this event

**Comment by PrimaryFeather** [comment]
Thanks for the report! Could you maybe create a sample that I can use to reproduce the problem? I'm not sure I understand it 100% by the description alone.

**Comment by greymag** [comment]
Yes, of course. The code below will throw null pointer exception after 500 ms delay

```actionscript3
package
{
    import flash.display.Sprite;
    import flash.events.Event;
    import flash.utils.setTimeout;
    import starling.core.Starling;
    import starling.display.QuadBatch;
    import starling.events.Event;

    public class TestStarling extends flash.display.Sprite
    {
        private var _starling:Starling;
        private var _qb:QuadBatch;

        public function TestStarling()
        {
            Starling.handleLostContext = true;

            _starling = new Starling(starling.display.Sprite, this.stage);

            _starling.addEventListener(starling.events.Event.ROOT_CREATED, this.rootCreated);
            _starling.start();
        }

        private function rootCreated(e:*):void
        {
            _starling.stage3D.addEventListener(flash.events.Event.CONTEXT3D_CREATE, this.onContextCreated);
            _qb = new QuadBatch();

            setTimeout(function ():void {
                // initiate context lost
                _starling.context.dispose();
            }, 500)
        }

        private function onContextCreated(e:*):void
        {
            // dispose QuadBatch on context lost
            _qb.dispose();
        }
    }
}
```

**Comment by PrimaryFeather** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [QuadBatch NullPointer Exception](https://trello.com/c/60VBPgZA/5-quadbatch-nullpointer-exception)

**Comment by PrimaryFeather** [comment]
I just added a check that should avoid these problems.
Sorry for the delay!
