### ISSUE TITLE
atf not work on flashplayer 11.4

### ISSUE THREAD

**Issue by matrix3d** [Gamua/Starling-Framework#944]

**Comment by PrimaryFeather** [comment]
The ATF format was changed somewhere around Flash Player 11.8, so that's probably what you're seeing. You'd need to find an old version of the ATF tools (back in the day, they were not part of the AIR SDK, but of the "Adobe Gaming SDK").

But may I ask why you need support for Flash Player 11.4?

**Comment by matrix3d** [comment]
bcs,some man use the fp11.4.
so it is a as3lib conv the newatf 2 oldatf format?
just change the header

**Comment by PrimaryFeather** [comment]
I don't know of any such library, sorry! Unfortunately, I don't know if it was just the header they changed, or some internals, too. 

However, a lot of security issues have been closed since Flash Player 11.4 — it was released in 2012! So you should definitely recommend to your players to update to a newer version.

**Comment by matrix3d** [comment]
Does the old ATF format have performance problems? Or other problems? Web game
If there is no performance problems, with the old ATF also never mind.

**Comment by PrimaryFeather** [comment]
I don't think the change was related to performance issues, but that they added new features to the format. The only thing I think you can do is try to find an old version of the ATF tools. The question though, is if the textures created like that work with a new AIR version.

Again, my recommendation is to recommend users to upgrade their Flash Player. It's simply dangerous to use such an old version today.

**Comment by matrix3d** [comment]
thankyou and close
