### ISSUE TITLE
Add 'color' parameter to 'drawToBitmapData'

### ISSUE THREAD

**Issue by marpies** [Gamua/Starling-Framework#945]
It'd be great if we could specify the color the painter is cleared with before drawing to bitmap data. Currently it defaults to black and cannot be changed as needed.

**Comment by PrimaryFeather** [comment]
Thanks for the suggestion! You're right, that would indeed be useful, I'll add that!

**Comment by PrimaryFeather** [comment]
I finally could squeeze that in! Please try it out and let me know if that works for you. :smile:
