### ISSUE TITLE
Starling root should be disposed before context

### ISSUE THREAD

**Issue by neuronix** [Gamua/Starling-Framework#948]
Hi Daniel,

We noticed that the stage/context is disposed before the actual tree of display objects which can cause errors when disposing & recreating a Starling instance (app relaunch without exit to refresh data for example).

Our fix was to simply add: 
starling.root.dispose(); 
Before the call:
starling.dispose();

However, it would be better changed in the framework I think.

Kind regards,

Cameron

**Comment by PrimaryFeather** [comment]
Agreed! Thanks a lot for making me aware of this.
