### ISSUE TITLE
Flex SDK zip binaries removed :)

### ISSUE THREAD

**Issue by CrazyFlasher** [Gamua/Starling-Framework#949]
Build fails :)
I guess link should be changed to
https://github.com/apache/flex-sdk/archive/apache-flex-sdk-4.16.0.zip

UPD: nope..these are sources :(

UPD: http://www-us.apache.org/dist/flex/4.15.0/binaries/apache-flex-sdk-4.15.0-bin.zip working one

**Comment by PrimaryFeather** [comment]
Thanks a lot for looking for an updated URL for the binaries! Hopefully, that should fix the travis build. 👍
