### ISSUE TITLE
Back buffer can be left in unknown state

### ISSUE THREAD

**Issue by johncridges** [Gamua/Starling-Framework#964]
When setting Starling.shareContext false, the back buffer is not necessarily set back to the Starling viewport. I suggest the following change in Starling.as:
```

        public function set shareContext(value : Boolean) : void
        {
            if (!value) {
                _previousViewPort.setEmpty();
            }
            _painter.shareContext = value;
        }

```

**Comment by PrimaryFeather** [comment]
Thanks a lot for the heads-up and the suggested fix, John! Makes sense.
