### ISSUE TITLE
Exception, while stage is resized

### ISSUE THREAD

**Issue by CrazyFlasher** [Gamua/Starling-Framework#971]
Hi.
When I resize stage to very small on Windows AIR, I receive exception:
```Error: Error #3780: Requested width of backbuffer is not in allowed range 32 to 16384.```
Is there a good way to handle it?
I use latest release of Starling and AIR 25 merged with Flex 4.16.0.
Thanks

**Comment by CrazyFlasher** [comment]
Sometimes this error is replaced with this:
```
Error: Error #3710: Requested Stage3D Operation failed to complete.
```

**Comment by PrimaryFeather** [comment]
I recently fixed that (see 62502f1e12b20764066dcca77935f0da8548c565). If you update to the latest head revision, that error should not happen any longer.

(I try to get Starling 2.2 out soon, then you'll have a stable version with this fix, too. That said: the master branch is typically quite stable, too.)

Please try it out and report back if it still happens — or close the issue. Thanks! :smile:

**Comment by CrazyFlasher** [comment]
Works fine with latest Starling

**Comment by PrimaryFeather** [comment]
Perfect, thanks for trying it out! :smile:
