### ISSUE TITLE
Best codec for playing mp4 videos

### ISSUE THREAD

**Issue by CrazyFlasher** [Gamua/Starling-Framework#973]
Hi.
Playing videos in texture is a big pain for me.
I've wrote different implementations of video player. Also user Feathers video player, and there still a lot of problems on different Android devices.
With AIR 25, target-player=25, swf-version=36 and `<disableMediaCodec>true</disableMediaCodec>` I get black screen on older devices.
I tried to roll back to target-player=23, swf-version=34. Video is playable by with very low fps and lags.
Is there a reason in codec maybe?
Can you help me to solve the problem with video playback?

**Comment by PrimaryFeather** [comment]
Mhm, this is unfortunately still a big problem. All we can do is document any issues as good as we can and forward it to Adobe, so that they can fix it. I'll help you with that!!

First thing to check is the video and audio codec you are using. The official recommendation from Adobe is: h.264 with AAC audio encoding. Is that what you are using?

**Comment by CrazyFlasher** [comment]
Yes, we use h.264 but there is no audio track. We will try to add silent AAC audio.
Also I use this in manifest `<containsVideo>true</containsVideo>` and this `<disableMediaCodec>true</disableMediaCodec>` when I build with target-player=25, swf-version=36.
If I build without that `<disableMediaCodec>true</disableMediaCodec>` I get exceptions on all Android devices I tested:
```
[trace] [Starling] Context restored.
[Fault] exception, information=Error: Error #3605: Sampler 0 binds an invalid texture.
```

**Comment by PrimaryFeather** [comment]
> We will try to add silent AAC audio.
Worth a shot, in any case!

That rules out the standard problems, IMHO, so I'd say we report this to Adobe. Please create a report on [tracker.adobe.com](https://tracker.adobe.com) that contains a minimal sample (ideally, just using the Starling "Texture.fromNetStream" API and display the texture on an Image), and upload your sample video. Furthermore, list all the devices you tested on.

Then come back here and post the link to the issue; I will do my best to get Adobe to look into it.

**Comment by CrazyFlasher** [comment]
Before reporting, I decided to write own video player instead of Feathers one, and noticed through logs, that for some reason `NetStream.Play.Stop` is fired on one of our Androids before video is beign rendered.
Below is the source code:
```
/**
 * Created by CrazyFlasher on 5.12.2016.
 */
package com.crazyfm.devkit.assets.video
{
	import com.domwires.core.mvc.message.MessageDispatcher;

	import flash.events.NetStatusEvent;
	import flash.media.SoundTransform;
	import flash.net.NetConnection;
	import flash.net.NetStream;

	import starling.display.DisplayObject;
	import starling.display.Image;
	import starling.display.Sprite;
	import starling.textures.Texture;

	public class VideoPlayer extends MessageDispatcher implements IVideoPlayer
	{
		private var netStream:NetStream;
		private var netConnection:NetConnection;

		private var videoTexture:Texture;
		private var videoImage:Image;

		private var videoSprite:Sprite;

		override public function dispose():void
		{
			netStream.close();
			netConnection.close();

			netStream = null;
			netConnection = null;

			disposeImage();

			videoSprite.dispose();

			super.dispose();
		}

		[PostConstruct]
		public function init():void
		{
			netConnection = new NetConnection();
			netConnection.connect(null);

			netStream = new NetStream(netConnection);
			netStream.addEventListener(NetStatusEvent.NET_STATUS, onNetStatus);

			videoSprite = new Sprite();
		}

		private function onNetStatus(event:NetStatusEvent):void
		{
			log(event.info.code);

			switch (event.info.code)
			{
				case "NetStream.Play.StreamNotFound":
					log("Stream not found");

					dispatchMessage(VideoPlayerMessage.ON_COMPLETE);

					break;
				case "NetStream.Play.Stop":
					log("Stream complete");

					dispatchMessage(VideoPlayerMessage.ON_COMPLETE);
					break;
			}
		}

		public function play(url:String, volume:Number = 1):void
		{
			stop();

			log("play");

			initTexture(url, volume);
		}

		private function initTexture(url:String, volume:Number = 1):void
		{
			log("initTexture");

			videoTexture = Texture.fromNetStream(netStream, 1, onStreamReady);

			videoTexture.root.onRestore = function ():void
			{
				log("restore context");
				initTexture(url, volume);
			};

			netStream.soundTransform = new SoundTransform(volume);
			netStream.play(url);
		}

		private function onStreamReady():void
		{
			disposeImage();

			videoImage = new Image(videoTexture);
			videoSprite.addChild(videoImage);

			dispatchMessage(VideoPlayerMessage.ON_STARTED);
		}

		private function disposeImage():void
		{
			if (videoImage)
			{
				var videoImageTexture:Texture = videoImage.texture;

				if (videoImage.parent)
				{
					videoImage.removeFromParent();
				}

				if (videoImageTexture)
				{
					videoImage.dispose();
					videoImageTexture.dispose();
				}

				videoImage = null;
				videoTexture = null;
			}
		}

		public function stop():void
		{
			disposeImage();

			if (netStream)
			{
				log("stop");

				netStream.close();
			}
		}

		public function get canvas():DisplayObject
		{
			return videoSprite;
		}

		public function playFile(url:String, volume:Number = 1):void
		{
			throw new Error("not implemented");
		}
	}
}
```
Link to video:
`https://spotlight.ee/static/videoHints/level_0/37-step.mp4`

**Comment by CrazyFlasher** [comment]
Looks like the problem was, because videos didn't contain any audio track.
We've added silent AAC soundtrack and now it is playable.
I'll make more test and write again a little bit later.

**Comment by PrimaryFeather** [comment]
Wow, that's an interesting outcome! Definitely report this to Adobe, too — probably they just didn't have such video-only files in their test cases.
