### ISSUE TITLE
Is it possible to bring back all the themes from previous release?

### ISSUE THREAD

**Issue by born2net** [Gamua/Starling-Framework#982]
Is it possible to bring back all the themes from the previous release?

thanks,

Sean.

**Comment by PrimaryFeather** [comment]
Which themes do you mean? Starling does not have any themes. Or did you mean to open an issue in the Feathers project? https://github.com/BowlerHatLLC/feathers

**Comment by born2net** [comment]
Ha sorry :)
feathers
closing and tx!
