### ISSUE TITLE
Glow filter changes TextField font color?

### ISSUE THREAD

**Issue by CrazyFlasher** [Gamua/Starling-Framework#983]
Hi.
I need to apply red (0xFF0000) glow filter to text fields.
There original color of TextFields without filter:
![image](https://user-images.githubusercontent.com/1607138/27864442-4498aaa0-6197-11e7-934f-ac24183b731a.png)
When I apply filter, it changes font color also. Also glow should be red instead of black:
```
textField.filter = new GlowFilter(0xFF0000, 40, 1, 1.0);
textField.filter.cache();
```
![image](https://user-images.githubusercontent.com/1607138/27864472-6c8a2048-6197-11e7-8b1a-abaacf354634.png)

**Comment by CrazyFlasher** [comment]
When I changed context3d profile to `Context3DProfile.BASELINE` (previously it was `Context3DProfile.BASELINE_CONSTRAINED`), it became ok.
![image](https://user-images.githubusercontent.com/1607138/27865478-5f31f80e-619b-11e7-9625-a3a2228b73ee.png)
But is it the only solution?
As I remember, it's better to use `BASELINE_CONSTRAINED` for best compatibility with older devices, or I am wrong?

**Comment by jamikado** [comment]
BASELINE_CONSTRAINED was really added to support older desktop graphics hardware, specifically on Windows. If you are going for mobile app release I use BASELINE at a minimum myself.

**Comment by CrazyFlasher** [comment]
Yes, the game is for Android and iOS especially.
Thanks, Jeff!

**Comment by PrimaryFeather** [comment]
Yes, there is no downside in requring BASELINE on mobile — on the contrary, it will make sum things more efficient, and I have never heard of any mobile device not supporting it.

Still, it's weird that the filter doesn't work with that mode. I'll look into it!

**Comment by johnridges** [comment]
I would check into the use of the AGAL "seq" token in the CompositeFilter. I don't think the "seq" or "sne" tokens are supported as well as the other AGAL tokens (that's what I've heard). It would be better to use the "sge" token in this case, as it's faster in BASELINE.CONSTRAINED, better supported, and accomplishes exactly the same thing.

**Comment by PrimaryFeather** [comment]
> It would be better to use the "sge" token in this case, as it's faster in BASELINE.CONSTRAINED, better supported, and accomplishes exactly the same thing.

Oh, I wasn't aware of this! Do you have any source for this information?

**Comment by PrimaryFeather** [comment]
In any case, @CrazyFlasher, could you please test if changing the line found [here](https://github.com/Gamua/Starling-Framework/blob/master/starling/src/starling/filters/CompositeFilter.as#L176) from

```"seq ft5, v0, v0"```

to

```"sge ft5, v0, v0"```

fixes the problem? (It's actually just a hack to produce a `1` vector in the shader without having to manually pass it in.)

BTW, I can't reproduce the problem on my system, so it's very likely that the AGAL code simply doesn't work 100% equally on your system in constrained mode.

**Comment by johnridges** [comment]
FYI, here is a list of approximately how may "ALU instruction"s are used in each AGAL token in BASELINE_CONSTRAINED (where "C" is the number of components the instruction operates on):

abs | 1
add | 1
cos | 4+9C
crs | 3
div | 1+C
dp3 | 1
dp4 | 1
exp | C
frc | 1
kil | 1
log | C
max | 1
min | 1
mov | 1
mul | 1
m33 | 4
m34 | 4
m44 | 5
neg | 1
nrm | 7
pow | 3C
rcp | C
rsq | C
sat | 1
seq | 5
sge | 2
sin | 4+9C
slt | 2
sne | 5
sqt | 2C
sub | 1

**Comment by PrimaryFeather** [comment]
Wow, that's super useful information! Thanks a lot for sharing! 

I'll make that `seq` → `sge` change right away.

**Comment by johnridges** [comment]
Happy to help. You might also want to change the seq token in Effect.as as well (although I suspect it's rarely executed). I think those are the only two occurrences of the seq or sne tokens in Starling.

**Comment by PrimaryFeather** [comment]
You're right, it's better changed there, as well. I wonder if that code has ever been executed in a real-life app, but consistency alone is worth it. :wink:
