### ISSUE TITLE
Touch on container with glow filter

### ISSUE THREAD

**Issue by CrazyFlasher** [Gamua/Starling-Framework#985]
I have a Sprite with with TextField inside with glow filter.
![image](https://user-images.githubusercontent.com/1607138/28016243-33a20456-657c-11e7-8456-2c2ddd04d1e9.png)
TouchEvent added to container with TextField works fine.
But if I cache this filter, there is a wierd touch behaviour.
Looks like touch events are being dispatched twice, however only the top break point can be cached with debugger.
If I comment this line:
```
_textField.filter = new GlowFilter(parseInt(glowFilter[0]), glowFilter[1], glowFilter[2], glowFilter[3]);
//_textField.filter.cache();
```
everything works as expected

**Comment by PrimaryFeather** [comment]
Hmhm, I just noticed that this report somehow slipped my attention. 😨 
Is this still happening?

In theory, caching should have no influence whatsoever on touch behavior. 😕
