### ISSUE TITLE
Something like Tween.hasEndValue() or Tween.hasProperty()

### ISSUE THREAD

**Issue by esidegallery** [Gamua/Starling-Framework#993]
I think it would be useful to be able to check whether a tween is animating a given property, especially as calling Tween.getEndValue() throws an error if the property doesn't exist, and try/catch statements can be expensive.

Thank you!

**Comment by PrimaryFeather** [comment]
Indeed, that makes a lot of sense! Thanks for the suggestion!

I just added the new method `animatesProperty(property:String):Boolean`. That should do the trick!
