### ISSUE TITLE
Multichannel Distance Field Fonts

### ISSUE THREAD

**Issue by PrimaryFeather** [Gamua/Starling-Framework#994]
Multichannel Distance Field rendering uses three channels instead of just one in order to provide a better result. It would be useful to have Starling support that. 

References: 

* https://github.com/Chlumsky/msdfgen
* http://computergraphics.stackexchange.com/questions/306/sharp-corners-with-signed-distance-fields-fonts/2151
* https://github.com/Jam3/msdf-bmfont

**Comment by soimy** [comment]
Happy to announce the new npm module [msdf-bmfont-xml](https://github.com/soimy/msdf-bmfont-xml)
It is much more usable than the old one mentioned before including:
- can generate starling compatible .fnt file
- use a much efficient packing algorithm same as TexturePacker

**Comment by PrimaryFeather** [comment]
Awesome, thanks!!! I'll try to squeeze that into Starling as soon as possible, promised. :smile:

BTW, quick question: is there a flag in the XML file that tells me that this is a multichannel distance field? 

If there is no such standard yet, I'd suggest we add the flag "type" to the info element, like this:

```xml
<font>
    <info face="Arial" type="MCDF" .../>
</font>
```

Type could be one of the following:

* `Standard` (can be omitted)
* `DistanceField`
* `MultiChannelDistanceField`

That's just a suggestion, of course, and I don't know if there's already a standard used by other tools. If not, we could just set the standard. :smile:

In any case, this would help Starling know how to render the font, without any manual setup code required by the developer.

**Comment by soimy** [comment]
There is no such flag in the [definition](http://www.angelcode.com/products/bmfont/doc/file_format.html) of BMFont .fnt file.
It's easy to implement, just few line of code 😄

**Comment by soimy** [comment]
[msdf-bmfont-xml](https://github.com/soimy/msdf-bmfont-xml/) is evolving 👍 
Now it has a very accessible CLI interface:

![Console-Demo](https://raw.githubusercontent.com/soimy/msdf-bmfont-xml/master/assets/console-demo.gif)

And also added some very useful feature:
- Multi-font packing.
- svg packing for future editing.
- packer smart sizing

**Comment by PrimaryFeather** [comment]
I just added a new property to the _DistanceFieldStyle_: `multiChannel`. When you enable this property, the style can make use of multi-channel distance field textures! :smile:

That should work great with your fonts, too! For now, the style has to be applied manually, though. I'm looking into ways of automating this.

**Comment by PrimaryFeather** [comment]
I just noticed that you already added the "type" attribute. Thanks a lot for that! :smile:

Your tool really works great, and it's very easy to use! I especially like the idea of adding multiple fonts together via the config files. A fantastic idea!!

Here's a sample rendering of the standard `Georgia.ttf` font with the updated style.

<img width="791" alt="screen shot 2017-08-25 at 16 47 43" src="https://user-images.githubusercontent.com/547347/29719220-8ad61214-89b5-11e7-8d09-0f3ebe4a3705.png">

I used the following arguments to create the texture:

     msdf-bmfont -o Georgia.png Georgia.ttt

In most areas, that rendering looks great — a massive improvement over monochrome DFs, especially considering the small texture size (in this case, it's just using two thirds of a 512x256 texture).

There are some small problems around the "o" circles, though. Do you see that? On the right side of the last word ("so") and in the dot of the exclamation mark. 

Could that be a problem in my rendering, or is this an artefact produced by _msdf_? I also saw this in the _Ubuntu_ font.

**Comment by soimy** [comment]
Because multi-channel distance field is generated from vector shape and is very sensitive to shape error ( which is common issue on free online font ) I implemented point and curve segment tolerance to minimize the artifacts ( Issue soimy/msdf-bmfont-xml#1 ). The problem segment in 'O' might be a side-effect of the tolerance. I'm finding a better way to balance that ( Maybe expose tolerance value argument in CLI, or use a [modified msdfgen](https://github.com/ckohnert/msdfgen/). Anyway, gonna be fixed soon, stay tuned.

**Comment by soimy** [comment]
@PrimaryFeather Here is the test render of the new DistanceFieldStype and also:
![msdf-rendertest](https://user-images.githubusercontent.com/1550237/29739153-bbd11404-8a69-11e7-9220-f22a23015e0c.png)

**Comment by PrimaryFeather** [comment]
Thanks a lot for the additional information, and for trying out the updated style! That rendering looks fantastic. I'm really impressed by the results from the multi-channeld distance fields — it's amazing to get such crisp output from those small, funny-looking textures. :wink:

**Comment by jimmymjing** [comment]
Hello, it works perfectly for English ttf fonts, but when I change it to any Chinese ttf, it stops adding Chinese Characters into the png spritesheet...

**Comment by soimy** [comment]
@jimmymjing yes, you should use utf-8 charset file. check out [this](https://github.com/soimy/msdf-bmfont-xml/tree/master/assets/charset) for samples.

**Comment by jimmymjing** [comment]
Thanks so much! It works perfectly.

**Comment by jimmymjing** [comment]
There are some places that I would use small font size.. like 14 - 16px. But it turns out quite jagged on the edge of each letter.. Are there any parameters that I could twist? Thanks!

**Comment by PrimaryFeather** [comment]
In my tests, scaling to small sizes worked surprisingly well! See here, that's both the same font:

![screen shot 2017-08-31 at 14 19 49](https://user-images.githubusercontent.com/547347/29922810-85f3b282-8e57-11e7-9dd2-e0c6e3714777.png)
![screen shot 2017-08-31 at 14 19 27](https://user-images.githubusercontent.com/547347/29922812-892f8958-8e57-11e7-9f1f-57e31192f726.png)

Some things come to my mind:

* be sure to create the texture without mipmaps.
* Use a higher value for "distance range" (also called "spread").

**Comment by soimy** [comment]
@jimmymjing it's not recommended to use font size smaller than 32 for msdf output. You will find many collision on distanceRange spread over the stroke (especially some complex gylphs like chinese characters). If you really want smaller output size, try reduce distanceRange a little bit.

**Comment by PrimaryFeather** [comment]
(For reference, my two samples used the DF-bitmap-font created with a size of 42 points, and then scaled down in Starling.)

**Comment by Maligan** [comment]
Shen Yiming & Daniel - huge thanks! This is really great feature!
